Feat/96 category data
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #100
Opened 2022-11-05 10:32 UTC by CreoHwan

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 카테고리 코어 데이터 받아오기 위함
- 이미지 코어 데이트 업로드를 위함
- 기타 버그 수정을 위함

## Key Changes 🔥 (주요 구현/변경 사항)
- 카테고리 코어 데이터를 가져옵니다. segment 뷰로 갈 때, 카테고리 코어 데이터를 받아 옵니다.
- 이미지 path를 추가하여 코어 데이터에 업로드합니다.

- 방 생성 뷰에서, 데이터를 기존에는 roomID - 1 에 저장했는데, rommID에 저장하도록 변경했습니다.
- segment에서 첫번째 이미지를 가져오는 부분을 수정했습니다.
- segment에서 디테일 뷰로 넘어갈 때, 텍스트를 가져오는 부분을 수정했습니다.

## ToDo 📆 (남은 작업)
- [ ] todo

## ScreenShot 📷 (참고 사진)
![Simulator Screen Recording - iPhone 14 - 2022-11-05 at 19 30 33](https://user-images.githubusercontent.com/92836045/200115513-7656e987-cc08-4de9-a971-e7ea9c31c6b3.gif)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 코어 데이터 관련하여 조금 혼선이 있는 거 같아서, 최대한 정리해봤습니다. 감사합니다.

## Reference 🔗

## Close Issues 🔒 (닫을 Issue)
Close #96
Close #No.

2022-11-05 11:43 UTC, taek0622 requested changes
고생하셨습니다.
중간에 버그가 심하게 터졌었는데, 해당 부분까지 잘 해결된 것 같네요. 감사합니다.
도중에 수정이 필요해 보이는 부분이 몇 군데 있어서 리뷰 남겼습니다.
확인 부탁드려요~

2022-11-05 11:43 UTC, taek0622 commented on Samsam/ViewController/PostingCategoryViewController.swift
> +        cell.categoryTitle.text = "\(categoryName.categoryName())"
p3;
선언한 변수가 카테고리 이름을 따오기 위해서 선언된 것 맞지만, 아래에서 .categoryName으로 카테고리 이름을 따오고 있고, 해당 변수 자체는 카테고리 자체를 의미하는 것이기 때문에 category 등의 다른 이름으로 바꾸는 것이 의미에 더 맞을 것 같습니다.

2022-11-05 11:43 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
>                          }
p2;
`self?.imageCellView.reloadData()`는 현재 if문의 조건과는 상관없이 무조건 실행되는 부분인 것 같습니다. If 아래로 빼는 것이 더 좋을 것 같습니다.

2022-11-05 11:43 UTC, taek0622 commented on Samsam/ViewController/RoomCategoryViewController.swift
> +        cell.categoryTitle.text = "\(categoryName.categoryName())"
p3;
위와 마찬가지로 해당 부분은 category의 이름을 따오기 위해서 존재하지만, 아래에서 categoryName을 이용하여 이름을 따오고 있고, 위의 변수는 카테고리 자체를 의미하는 듯하여 이곳도 category 등의 이름으로 변경하는 것이 더 좋을 것 같습니다.

2022-11-05 16:02 UTC, JUNY0110 approved these changes
고생하셨습니다~

2022-11-06 02:37 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
>                          }
> p2; `self?.imageCellView.reloadData()`는 현재 if문의 조건과는 상관없이 무조건 실행되는 부분인 것 같습니다. If 아래로 빼는 것이 더 좋을 것 같습니다.

7b51a86 감사합니다!~

2022-11-06 02:40 UTC, CreoHwan commented on Samsam/ViewController/PostingCategoryViewController.swift
> +        cell.categoryTitle.text = "\(categoryName.categoryName())"
> p3; 선언한 변수가 카테고리 이름을 따오기 위해서 선언된 것 맞지만, 아래에서 .categoryName으로 카테고리 이름을 따오고 있고, 해당 변수 자체는 카테고리 자체를 의미하는 것이기 때문에 category 등의 다른 이름으로 바꾸는 것이 의미에 더 맞을 것 같습니다.

a8dbd21 감사합니다!

2022-11-06 02:40 UTC, CreoHwan commented on Samsam/ViewController/RoomCategoryViewController.swift
> +        cell.categoryTitle.text = "\(categoryName.categoryName())"
> p3; 위와 마찬가지로 해당 부분은 category의 이름을 따오기 위해서 존재하지만, 아래에서 categoryName을 이용하여 이름을 따오고 있고, 위의 변수는 카테고리 자체를 의미하는 듯하여 이곳도 category 등의 이름으로 변경하는 것이 더 좋을 것 같습니다.

a8dbd21 감사합니다!

2022-11-06 05:55 UTC, taek0622 commented on Samsam/ViewController/PostingCategoryViewController.swift
> +        cell.categoryTitle.text = "\(categoryName.categoryName())"
> > p3; 선언한 변수가 카테고리 이름을 따오기 위해서 선언된 것 맞지만, 아래에서 .categoryName으로 카테고리 이름을 따오고 있고, 해당 변수 자체는 카테고리 자체를 의미하는 것이기 때문에 category 등의 다른 이름으로 바꾸는 것이 의미에 더 맞을 것 같습니다.
> 
> [a8dbd21](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/a8dbd2118a13351709219342e655581b1b04578d) 감사합니다!

확인했습니다. 리뷰 리졸브합니다.

2022-11-06 05:55 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
>                          }
> > p2; `self?.imageCellView.reloadData()`는 현재 if문의 조건과는 상관없이 무조건 실행되는 부분인 것 같습니다. If 아래로 빼는 것이 더 좋을 것 같습니다.
> 
> [7b51a86](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/7b51a86dafae8effdc43880944ec6abdaa82b980) 감사합니다!~

확인했습니다. 리뷰 리졸브합니다.

2022-11-06 05:56 UTC, taek0622 commented on Samsam/ViewController/RoomCategoryViewController.swift
> +        cell.categoryTitle.text = "\(categoryName.categoryName())"
> > p3; 위와 마찬가지로 해당 부분은 category의 이름을 따오기 위해서 존재하지만, 아래에서 categoryName을 이용하여 이름을 따오고 있고, 위의 변수는 카테고리 자체를 의미하는 듯하여 이곳도 category 등의 이름으로 변경하는 것이 더 좋을 것 같습니다.
> 
> [a8dbd21](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/a8dbd2118a13351709219342e655581b1b04578d) 감사합니다!

확인했습니다. 리뷰 리졸브합니다.

2022-11-06 12:14 UTC, closed without merging