[Feature] 칩뷰 디자인 및 기능 만들기
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #107
Opened 2022-11-08 02:08 UTC by CreoHwan

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 칩뷰 디자인 레이아웃 만들기
- 칩뷰 기능 만들기

## Key Changes 🔥 (주요 구현/변경 사항)
- 칩뷰 디자인 레이아웃 만들었습니다. scrollview에 stackview를 넣고, 카테고리 개수만큼 stackview에 버튼을 생성해서 넣었습니다.
- 칩뷰 밑에는 기존의 cell을 이용했습니다.
- 클릭된 칩은 selectedID에 저장됩니다.
- 칩이 클릭되면, 해당되는 카테고리의 posting을 selectedCategoryItem 배열에 담아서, cell을 reload하는 방식으로 구현했습니다.

## ToDo 📆 (남은 작업)
- [ ] todo

## ScreenShot 📷 (참고 사진)
https://user-images.githubusercontent.com/92836045/200457417-15c7deb0-03ac-4060-b6ca-5b08ef9165f5.mov

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 감사합니다!

## Reference 🔗

## Close Issues 🔒 (닫을 Issue)
Close #101

2022-11-08 07:53 UTC, taek0622 requested changes
고생하셨습니다.
칩을 컬렉션뷰가 아닌 방법으로 구현하신 것 매우 인상 깊었습니다.
상당히 공수가 컸을 것이라고 생각되는데, 이걸 하시네요 ㅎㅎ
현재로선 크게 문제가 될 만한 부분은 보이지 않고, 서버 연동시 변경될 부분은 많은 것 같아서 걱정이긴 하네요..
수정이 필요한 부분 하나와 질문 하나 남겼습니다. 확인 부탁드려요~

2022-11-08 07:53 UTC, ikanic commented on Samsam/ViewController/ChipViewController.swift
> +        $0.backgroundColor = .white
p2;
이미 칩뷰를 불러오는 뷰에서 배경색이 지정되어있기 때문에 별도로 배경색을 지정할 필요는 없을 것 같습니다.

2022-11-08 07:53 UTC, taek0622 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +    }
질문;
roomCategoryID가 현재 뷰가 아닌 PostingView에서 사용되고 있는데, PostingView가 아닌 현재 뷰에서 RoomCategoryID를 불러와야하는 이유가 있을까요?

2022-11-08 14:44 UTC, CreoHwan commented on Samsam/ViewController/ChipViewController.swift
> +        $0.backgroundColor = .white
> p2; 이미 칩뷰를 불러오는 뷰에서 배경색이 지정되어있기 때문에 별도로 배경색을 지정할 필요는 없을 것 같습니다.

1d83478 넵 감사합니다~

2022-11-08 14:46 UTC, CreoHwan commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +    }
> 질문; roomCategoryID가 현재 뷰가 아닌 PostingView에서 사용되고 있는데, PostingView가 아닌 현재 뷰에서 RoomCategoryID를 불러와야하는 이유가 있을까요?

그러게요! 사실 카테고리가 사용되는 부분은 Posting 모달이 사용되는 부분이긴 합니다! 단순하게 방에 처음 들어왔을 때, 그래도 방의 정보를 알고 있어야 하겠게니~ 라는 생각으로 만들었던 것 같습니다!

2022-11-08 14:48 UTC, taek0622 commented on Samsam/ViewController/ChipViewController.swift
> +        $0.backgroundColor = .white
> > p2; 이미 칩뷰를 불러오는 뷰에서 배경색이 지정되어있기 때문에 별도로 배경색을 지정할 필요는 없을 것 같습니다.
> 
> [1d83478](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/1d834789db93bda673f91d2f855ff416074d1051) 넵 감사합니다~

확인했습니다. 리뷰 리졸브합니다.

2022-11-08 14:56 UTC, taek0622 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +    }
> > 질문; roomCategoryID가 현재 뷰가 아닌 PostingView에서 사용되고 있는데, PostingView가 아닌 현재 뷰에서 RoomCategoryID를 불러와야하는 이유가 있을까요?
> 
> 그러게요! 사실 카테고리가 사용되는 부분은 Posting 모달이 사용되는 부분이긴 합니다! 단순하게 방에 처음 들어왔을 때, 그래도 방의 정보를 알고 있어야 하겠게니~ 라는 생각으로 만들었던 것 같습니다!

음.. 이 부분은 사실 PostingView에서 불러오는 게 더 적절할 것 같습니다.
다만, 현재 코어데이터를 만질 이유가 딱히 없기도 하고 서버로 변경되었을 때 전부 수정될걸 생각하면 이부분은 우선 그냥 이 상태로 머지하고 후에 로직을 바꾸는 쪽으로 하면 어떨까 싶습니다.

2022-11-08 14:57 UTC, taek0622 approved these changes
고생하셨습니다.
칩뷰 때문에 상당히 오래 생각하신걸로 아는데 진짜 고생하셨어요.
질문에 대해서는 답변 남겼지만 후에 서버가 연동되었을 때 수정되거나 하는 쪽으로 하면 좋을 것 같습니다~

2022-11-08 19:05 UTC, JUNY0110 reviewed
고생하셨습니다~

2022-11-08 19:05 UTC, JUNY0110 commented on Samsam/ViewController/ChipViewController.swift
> +        )
p3.
`chipScrollView`에 좌우 패딩을 주는 것보다, `chipContentView`에 좌우 패딩 16을 주는 게 더 자연스러울 것 같습니다.
이유는, `chipScrollView`에 좌우 패딩을 주면 좌우 공백이 생겨 scroll시 허공에서 칩이 나오는 것처럼 보이나, `chipContentView`에 패딩을주게 되면 그 부분이 해소되기 때문입니다.

2022-11-08 19:05 UTC, JUNY0110 commented on Samsam/ViewController/ChipViewController.swift
> +}
p3.
func이름이 너무 유사해 착각을 일으키지 않을까 우려됩니다.
tapSelectedButton: 버튼 탭했을 때에 대한 기능
selectedButton: 선택한 버튼에 대한 기능
unselectedButton: 선택되지 않은 버튼에 대한 기능 ( tapSelectedButton 사용 시 didSelectedButton과 혼동 우려 )
처럼 구분하는건 어떨까 싶습니다.

unselectedButton은 변수명같아 많이 애매하지만, selected와 select가 구분만 되도 좋을 것 같습니다.

2022-11-08 19:05 UTC, JUNY0110 commented on Samsam/ViewController/ChipViewController.swift
> +        }
신선한 코드네요..
`"   \(Category(rawValue: Int(coreDataManager.workingStatuses[i-1].categoryID))!.categoryName())   "` 이렇게 하는 방법도 있기도 하고, 아니면 다른 코드에서도 사용을 편하게 하기 위해 categoryName에서 전부 좌우 여백을 추가하는 방법도 있을 것 같습니다.
또한 산술연산자(+)의 경우 좌우 여백을 주는 것이 가독성을 높이는 데 유리할 것 같습니다 ^^

2022-11-09 04:25 UTC, CreoHwan commented on Samsam/ViewController/ChipViewController.swift
> +        )
> p3. `chipScrollView`에 좌우 패딩을 주는 것보다, `chipContentView`에 좌우 패딩 16을 주는 게 더 자연스러울 것 같습니다. 이유는, `chipScrollView`에 좌우 패딩을 주면 좌우 공백이 생겨 scroll시 허공에서 칩이 나오는 것처럼 보이나, `chipContentView`에 패딩을주게 되면 그 부분이 해소되기 때문입니다.

bdfa23f 좋은 의견 감사합니다~

2022-11-09 04:30 UTC, CreoHwan commented on Samsam/ViewController/ChipViewController.swift
> +}
> p3. func이름이 너무 유사해 착각을 일으키지 않을까 우려됩니다. tapSelectedButton: 버튼 탭했을 때에 대한 기능 selectedButton: 선택한 버튼에 대한 기능 unselectedButton: 선택되지 않은 버튼에 대한 기능 ( tapSelectedButton 사용 시 didSelectedButton과 혼동 우려 ) 처럼 구분하는건 어떨까 싶습니다.
> 
> unselectedButton은 변수명같아 많이 애매하지만, selected와 select가 구분만 되도 좋을 것 같습니다.

c13eeb6 감사합니다!

2022-11-09 04:31 UTC, CreoHwan commented on Samsam/ViewController/ChipViewController.swift
> +        }
> 

감사합니다! 다음에 의견 반영하여 코딩하도록 하겠습니다~!

2022-11-09 04:32 UTC, merged