[Feature] 애플 아이디 로그인 기능 / API POST 기능
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #110
Opened 2022-11-09 04:44 UTC by CreoHwan

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 애플 아이디 로그인 기능
- API 로그인 연동 POST 기능 

## Key Changes 🔥 (주요 구현/변경 사항)
- 애플 아이디 로그인 기능
- API 로그인 연동 POST 기능 

## ToDo 📆 (남은 작업)
- [ ] API 연동 준비
- [ ] LoginViewController 리팩토링
- [ ] 토큰 처리

## ScreenShot 📷 (참고 사진)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 일단 LoginViewController 뷰 안에서 API POST 기능을 만들었습니다. 
- 추후 API 서버 통신을 위한 세팅이 필요할 것 같습니다.

## Reference 🔗
- URL Session 관련 refterence
https://gyuios.tistory.com/108

## Close Issues 🔒 (닫을 Issue)
Close #108

2022-11-10 17:30 UTC, JUNY0110 requested changes
고생하셨습니다~ 코드를 이해하기 위해 URLSession에 대해 많은 공부를 하게 되네요. 많이 배워갑니다!

2022-11-10 17:30 UTC, JUNY0110 commented on Samsam/ViewController/LoginViewController.swift
> +    }
p4.
무엇에대한 실행인지를 확인하기 위해 다시 코드를 돌아봐야하는 불편함이 있는 것 같습니다. defaultSession.dateTask를 별도 변수를 지정하여 변수.resume()로 하는게 가독성측면에서 유리할 것 같습니다.
또한 URLSession의 LiftCycle(통신단계)을 명확히 하기에도 좋다고 생각합니다.

[URLSession을 사용한 서버통신 - 후르스콜링개발](https://roniruny.tistory.com/163#%E-%--%--%--%EC%--%-C%EB%--%--%ED%--%--%EB%A-%B-%--UI%--%EC%--%--%EB%-D%B-%EC%-D%B-%ED%-A%B-%--%EB%B-%--%EB%B-%--%EC%-D%--%--%ED%--%AD%EC%--%--%C-%A-main%--thread%EC%--%--%EC%--%-C%--%EC%B-%--%EB%A-%AC%EA%B-%--%--%EC%-D%B-%EB%A-%--%EC%A-%B-%EC%--%BC%--%ED%--%--%EA%B-%B-%--%EB%--%-C%EB%AC%B-%EC%-D%B-%EB%-B%A--)
해당 참고자료에서도 이와같이 사용 중입니다.

Q. 
이 코드에서 Decodable이 아닌 jsonSerialization을 사용한 이유는 무엇일까요? jsonSerializaion을 통해 객체단위 Codable이 가능하다라는 것은 알겠는데, 이해를 위해 [예제코드](https://gist.github.com/hcn1519/0d685b1f0aba74ed9577e9cab1b02b6f)를 봤지만 어떤 차이가 있는지 잘 이해가 되지 않습니다.
```Swift
            if let json = try? JSONSerialization.jsonObject(with: data, options: []) as? [String : Any] {
                 print("json")
                 print(json)
             }
```

2022-11-10 17:30 UTC, JUNY0110 commented on Samsam/ViewController/LoginViewController.swift
> +            appleIDProvider.getCredentialState(forUserID: userIdentifier) { (credentialState, error) in
Q.
AppleID에 등록된 유저인지 확인하기 위한 용도일까요?

2022-11-10 17:30 UTC, JUNY0110 commented on Samsam/ViewController/LoginViewController.swift
> +
p2.
코드가 너무 길어 가독성을 해칩니다. 컨벤션에도 너무 긴 한 줄 코드를 지양토록 되어있으니 이처럼 구분하면 좋을 것 같습니다.
```Swift
self.requestPOSTWithURL(url: "http://3.39.76.231:3000/giwazip/workers",
                        parameters: self.setLoginParameters(userIdentifier: userIdentifier,
                                                            name: userLastName!+userFirstName!,
                                                            email: userEmail!))
```

2022-11-11 01:49 UTC, CreoHwan commented on Samsam/ViewController/LoginViewController.swift
> +    }
> p4. 무엇에대한 실행인지를 확인하기 위해 다시 코드를 돌아봐야하는 불편함이 있는 것 같습니다. defaultSession.dateTask를 별도 변수를 지정하여 변수.resume()로 하는게 가독성측면에서 유리할 것 같습니다. 또한 URLSession의 LiftCycle(통신단계)을 명확히 하기에도 좋다고 생각합니다.
> 
> [URLSession을 사용한 서버통신 - 후르스콜링개발](https://roniruny.tistory.com/163#%E-%--%--%--%EC%--%-C%EB%--%--%ED%--%--%EB%A-%B-%--UI%--%EC%--%--%EB%-D%B-%EC%-D%B-%ED%-A%B-%--%EB%B-%--%EB%B-%--%EC%-D%--%--%ED%--%AD%EC%--%--%C-%A-main%--thread%EC%--%--%EC%--%-C%--%EC%B-%--%EB%A-%AC%EA%B-%--%--%EC%-D%B-%EB%A-%--%EC%A-%B-%EC%--%BC%--%ED%--%--%EA%B-%B-%--%EB%--%-C%EB%AC%B-%EC%-D%B-%EB%-B%A--) 해당 참고자료에서도 이와같이 사용 중입니다.
> 
> Q. 이 코드에서 Decodable이 아닌 jsonSerialization을 사용한 이유는 무엇일까요? jsonSerializaion을 통해 객체단위 Codable이 가능하다라는 것은 알겠는데, 큰 차이가 느껴지지 않습니다. 이해를 위해 [예제코드](https://gist.github.com/hcn1519/0d685b1f0aba74ed9577e9cab1b02b6f)를 찾아봤지만 어떤 차이가 있는지 잘 이해가 되지 않습니다. [예제코드 이전 참고자료](https://hcn1519.github.io/articles/2017-07/iOS_URLSession#urlsession%EC%9D%98-request%EC%99%80-response)
> 
> ```swift
>             if let json = try? JSONSerialization.jsonObject(with: data, options: []) as? [String : Any] {
>                  print("json")
>                  print(json)
>              }
> ```

https://learn-hyeoni.tistory.com/45
저는 이 부분에서는 전체 response를 출력하고 싶어서 사용했습니다! 요새는 response를 적절히 확용하기 위해서 codabel로 많이 사용하는 것 같습니다! 추후 PR에서는 codabel 사용해서 올릴 예정입니다!

2022-11-11 01:50 UTC, CreoHwan commented on Samsam/ViewController/LoginViewController.swift
> +            appleIDProvider.getCredentialState(forUserID: userIdentifier) { (credentialState, error) in
> Q. AppleID에 등록된 유저인지 확인하기 위한 용도일까요?

등록된 유저인지는 서버에서 처리할 예정입니다! 이 부분은 유저의 정보를 받아서 서버로 보내는 부분입니다!

2022-11-11 01:51 UTC, CreoHwan commented on Samsam/ViewController/LoginViewController.swift
> +    }
> > p4. 무엇에대한 실행인지를 확인하기 위해 다시 코드를 돌아봐야하는 불편함이 있는 것 같습니다. defaultSession.dateTask를 별도 변수를 지정하여 변수.resume()로 하는게 가독성측면에서 유리할 것 같습니다. 또한 URLSession의 LiftCycle(통신단계)을 명확히 하기에도 좋다고 생각합니다.
> > [URLSession을 사용한 서버통신 - 후르스콜링개발](https://roniruny.tistory.com/163#%E-%--%--%--%EC%--%-C%EB%--%--%ED%--%--%EB%A-%B-%--UI%--%EC%--%--%EB%-D%B-%EC%-D%B-%ED%-A%B-%--%EB%B-%--%EB%B-%--%EC%-D%--%--%ED%--%AD%EC%--%--%C-%A-main%--thread%EC%--%--%EC%--%-C%--%EC%B-%--%EB%A-%AC%EA%B-%--%--%EC%-D%B-%EB%A-%--%EC%A-%B-%EC%--%BC%--%ED%--%--%EA%B-%B-%--%EB%--%-C%EB%AC%B-%EC%-D%B-%EB%-B%A--) 해당 참고자료에서도 이와같이 사용 중입니다.
> > Q. 이 코드에서 Decodable이 아닌 jsonSerialization을 사용한 이유는 무엇일까요? jsonSerializaion을 통해 객체단위 Codable이 가능하다라는 것은 알겠는데, 큰 차이가 느껴지지 않습니다. 이해를 위해 [예제코드](https://gist.github.com/hcn1519/0d685b1f0aba74ed9577e9cab1b02b6f)를 찾아봤지만 어떤 차이가 있는지 잘 이해가 되지 않습니다. [예제코드 이전 참고자료](https://hcn1519.github.io/articles/2017-07/iOS_URLSession#urlsession%EC%9D%98-request%EC%99%80-response)
> > ```swift
> >             if let json = try? JSONSerialization.jsonObject(with: data, options: []) as? [String : Any] {
> >                  print("json")
> >                  print(json)
> >              }
> > ```
> 
> https://learn-hyeoni.tistory.com/45 저는 이 부분에서는 전체 response를 출력하고 싶어서 사용했습니다! 요새는 response를 적절히 확용하기 위해서 codable로 많이 사용하는 것 같습니다! 추후 PR에서는 codable 사용해서 올릴 예정입니다!

2022-11-11 01:52 UTC, CreoHwan commented on Samsam/ViewController/LoginViewController.swift
> +
> p2. 코드가 너무 길어 가독성을 해칩니다. 컨벤션에도 너무 긴 한 줄 코드를 지양토록 되어있으니 이처럼 구분하면 좋을 것 같습니다.
> 
> ```swift
> self.requestPOSTWithURL(url: "http://3.39.76.231:3000/giwazip/workers",
>                         parameters: self.setLoginParameters(userIdentifier: userIdentifier,
>                                                             name: userLastName!+userFirstName!,
>                                                             email: userEmail!))
> ```

감사합니다! 추후 PR에 고려하여 올리도록 하겠습니다!

2022-11-11 01:53 UTC, closed without merging