[Feature] 방생성뷰(RoomCreationView) 달력 아코디언 및 셀 커스텀
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #111
Opened 2022-11-09 16:59 UTC by JUNY0110

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 달력을 펼치고 닫는 동작을 구현하기 위함
- Cell단위 동작을 구현하기 위함
- 고객명/주소 입력 시 버튼 속성 변경하기 위함

## Key Changes 🔥 (주요 구현/변경 사항)
- TableView활용한 Calendar Accordion 스타일 반영
- Delegate Pattern적용
- dateButton를 위한 Color Asset 추가
- 고객명/주소 입력 시 버튼 활성화/비활성화 기능 구현

## ToDo 📆 (남은 작업)
- [ ] 시공일보다 준공일이 먼저가 되거나, 준공일보다 시공일이 더 늦은 날로 표시되지 않도록 조건 부여
- [ ] Cell height
- [ ] Cell을 닫을 때, DatePicker 잔상이 남는 버그 수정

## ScreenShot 📷 (참고 사진)
![Simulator Screen Recording - iPhone 13 Pro - 2022-11-10 at 01 56 43](https://user-images.githubusercontent.com/98405970/200892677-c848264d-0f7b-4834-b595-63db5beb8966.gif)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 생각보다 삽질이 길어졌습니다. 덕분에 코드 줄수도 상당하게 되었네요. ^^7;;
- 코드를 더 효율적으로 짤 수 있는 방법에 대해 같이 얘기해보고 싶네요

## Reference 🔗
- 일단 올려놓고 추가하겠습니다.

## Close Issues 🔒 (닫을 Issue)
Close #No.

2022-11-14 01:55 UTC, CreoHwan requested changes
고생하셨습니다! 델리게이트를 사용하신 게 되게 인상적이었습니다! RoomCreationViewContoller는 추후에 한번 더 보고 리뷰해보도록 하겠습니다~~ =D

2022-11-14 01:55 UTC, CreoHwan commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewWarrantyCell.swift
> +        $0.wraps = true
p2: $0.wraps = true 를 주신 이유가 있으실까요?! 24에서 갑자기 0으로 넘어가면 유저 입장에서는 살짝 어색할 것 같습니다!!

2022-11-14 01:55 UTC, CreoHwan commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewWarrantyCell.swift
> +        warrantyText.text = "\(warrantyCount)개월"
p4: warrantyText.text = "\(Int(warrantyStepper.value))개월" 이런 식으로 이용하면 굳이 warrantyCount를 사용하지 않아도 될 것 같습니다! 

하지만 warrantyCount가 RoomCreationViewContoller에서 roomCategoryViewController로 기간을 넘겨줄 때 사용하는 것을 확인했습니다! ((RoomCreationViewContoller 253번 줄) 

warrantyCount를 선언하지 않으면, warrantyStepper를 private let 이 아닌 그냥 let으로 선언하고, roomCategoryViewController.warrantyTime = Int32(warrantyCell.warrantyStepper.value) 이런 식으로 하는 방법도 있을 것 같습니다!!

2022-11-14 01:55 UTC, CreoHwan commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateCell copy.swift
> +
p2: 파일 이름을 혹시 RoomCreationViewDateSecondCell로 바꿔주실 수 있으실까요~~?! class이름이랑 파일 이름이랑 달라서 살짝 헷갈립니다~~

2022-11-14 01:55 UTC, CreoHwan commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateFirstCell.swift
> +
p4: 따로 함수로 빼지 않고, datePicker 생성시에, $0.addTarget(self, action: #selector(check), for: .valueChanged) 이렇게 추가해도 될 듯 합니다!! =D

2022-11-14 01:55 UTC, CreoHwan commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateCell copy.swift
> +
p4: 따로 함수로 빼지 않고, datePicker 생성시에, $0.addTarget(self, action: #selector(check), for: .valueChanged) 이렇게 추가해도 될 듯 합니다!! =D

2022-11-14 01:55 UTC, CreoHwan commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateCell copy.swift
> +
질문: AnyObject로 선언하신 이유가 궁금합니다!! : )

2022-11-14 06:04 UTC, CreoHwan reviewed
최대한 이해해보려 노력하면서 코드리뷰했습니다! 정말 고뇌하신 게 느껴지네요 ㅋㅋ 잘 봤습니다!!~

시공일, 준공일, AS기간이 너무 붙어 있는 것 같아서 제가 살짝 고민해봤는데, 밑에 사진처럼 이런 방법도 있는 것 같습니다!
<img width="1659" alt="스크린샷 2022-11-14 15 03 56" src="https://user-images.githubusercontent.com/92836045/201587043-c6264d7f-5edb-43d8-bcc8-d4bea5acfcc1.png">

2022-11-14 06:04 UTC, creohwan commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +        customerTextField.addTarget(self, action: #selector(buttonAttributeChanged), for: .editingChanged)
p3: 이 부분은 customerTextField 생성 시, $0.addTarget(self, action: #selector(buttonAttributeChanged), for: .editingChanged) 이렇게도 할 수 있을 것 같습니다! =D

2022-11-14 06:04 UTC, creohwan commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +
p2: 여기 if문에서 nextButton.addTarget(self, action: #selector(tapNextButton), for: .touchUpInside) 이 부분은 nextButton 생성 시 $0.addTarget(self, action: #selector(tapNextButton), for: .touchUpInside) 이런 식으로 바꾸면 좋을 듯 합니다!
왜냐하면 입력이될 때마다, if문이 돌아가는데, 그때마다 addTarget이 되는 것이 불필요하다고 생각이 들어서 입니다~! 
그리고 isEnabled가 활성화/비활성화 역할을 충분히 해주기 때문에 괜찮을 것 같습니다~

아니면 isEnabled를 지우고, if문에는 addTarget, else문에는 removeTarget를 해도 될 것 같습니다~

+ 문득 궁금증이 생겼습니다. 만약 계속 button에 addTarget를 해주면 어떻게하지?
찾아본 결과, 하나만 저장하는 것 같습니다!
(https://stackoverflow.com/questions/24845469/uibutton-addtarget-multiple-times-on-same-target-action-only-calls-once)

2022-11-14 06:04 UTC, creohwan commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateFirstCell.swift
> +    }
질문: 여기서 if let date = date 에서, date는 무조건 들어오는 값인 거 같은데, if let으로 쓰신 이유가 궁금합니다!

2022-11-14 14:01 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateCell copy.swift
> +
> 질문: AnyObject로 선언하신 이유가 궁금합니다!! : )

AnyObject는 모든 클래스타입 인스턴스를 나타낼 수 있습니다. Delegate는 `참조`를 기반으로 진행되기 때문에, 참조에 필요한 class타입으로 선언되어야 합니다. 따라서 AnyObject로 타입을 지정하였습니다. 
해당 내용이 담겨있는 [공식문서](https://developer.apple.com/documentation/swift/anyobject) 내용을 스크린샷으로 첨부하고, 관련 블로그를 [참고자료](https://gyuios.tistory.com/130)로 올립니다.
<img width="896" alt="스크린샷 2022-11-14 오후 11 00 36" src="https://user-images.githubusercontent.com/98405970/201678983-4f98f2b1-0e84-48c8-823c-8196fe9954e5.png">

2022-11-14 14:17 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewWarrantyCell.swift
> +        warrantyText.text = "\(warrantyCount)개월"
> p4: warrantyText.text = "(Int(warrantyStepper.value))개월" 이런 식으로 이용하면 굳이 warrantyCount를 사용하지 않아도 될 것 같습니다!
> 
> 하지만 warrantyCount가 RoomCreationViewContoller에서 roomCategoryViewController로 기간을 넘겨줄 때 사용하는 것을 확인했습니다! ((RoomCreationViewContoller 253번 줄)
> 
> warrantyCount를 선언하지 않으면, warrantyStepper를 private let 이 아닌 그냥 let으로 선언하고, roomCategoryViewController.warrantyTime = Int32(warrantyCell.warrantyStepper.value) 이런 식으로 하는 방법도 있을 것 같습니다!!

좋은 의견 감사합니다!
하지만, WarrantyCount라는 변수명이 자주 여러번 사용되는 점,
 Int32(warrantyCell.warrantyStepper.value)보다 코드 의미 해석이 빠르다는 점에서
 WarrantyCount를 사용하는 게 조금 더 낫다고 생각이 들어 변경하지는 않았습니다. 다음 변수명을 정할 때에는 그 부분을 다시 한 번 상기시킬 수 있을 것 같네요!

2022-11-14 14:19 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewWarrantyCell.swift
> +        $0.wraps = true
> p2: $0.wraps = true 를 주신 이유가 있으실까요?! 24에서 갑자기 0으로 넘어가면 유저 입장에서는 살짝 어색할 것 같습니다!!

저도 이 부분에 대해 많은 고민을 했었고, 내일 같이 얘기를 해보고 싶네요!
저는 시작값이 12로 시작하지만, 사용자가 실수로 0 또는 24를 선택했다가, 다시 24 또는 0 방향의 값으로 돌아가고 싶을 때, Stepper를 여러번 클릭하지 않고 넘길 수 있는게 낫지 않을까? 라는 생각이었습니다.

2022-11-14 14:49 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateFirstCell.swift
> +    }
> 질문: 여기서 if let date = date 에서, date는 무조건 들어오는 값인 거 같은데, if let으로 쓰신 이유가 궁금합니다!

큰 이유는 없었습니다. RoomCreationViewController에서 `currentSelectedFirstDate`를 대입해 configure함수를 사용하는데, `currentSelectedFirstDate`는 현재 선택한 값이기에 초기값을 선언할 필요는 없다고 생각했습니다.
 하지만 `currentSelectedFirstDate`를 초기화하지 않으면 optional value error가 나오기 때문에, if let을 사용했습니다.

하지만 디너의 말처럼 If let을 삭제하고, Date에서 optional을 제거하고, `currentSelectedFirstDate`를 오늘 날짜로 선언하는 것도 하나의 방법인 것 같습니다..! 어떤 게 더 의미적으로 올바른 코드인지는 얘기를 나눠보면 좋을 것 같아요!

2022-11-14 14:51 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateFirstCell.swift
> +
0e7f603 반영했습니다~

2022-11-14 14:51 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateCell copy.swift
> +
> p4: 따로 함수로 빼지 않고, datePicker 생성시에, $0.addTarget(self, action: #selector(check), for: .valueChanged) 이렇게 추가해도 될 듯 합니다!! =D

0e7f603 반영했습니다~

2022-11-14 14:52 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateCell copy.swift
> +
> p2: 파일 이름을 혹시 RoomCreationViewDateSecondCell로 바꿔주실 수 있으실까요~~?! class이름이랑 파일 이름이랑 달라서 살짝 헷갈립니다~~

ff2104a 실수했네요.. 반영했습니다~

2022-11-14 14:53 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +        customerTextField.addTarget(self, action: #selector(buttonAttributeChanged), for: .editingChanged)
> p3: 이 부분은 customerTextField 생성 시, $0.addTarget(self, action: #selector(buttonAttributeChanged), for: .editingChanged) 이렇게도 할 수 있을 것 같습니다! =D

7cbb68d 반영했습니다~

2022-11-14 14:55 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +
> p2: 여기 if문에서 nextButton.addTarget(self, action: #selector(tapNextButton), for: .touchUpInside) 이 부분은 nextButton 생성 시 $0.addTarget(self, action: #selector(tapNextButton), for: .touchUpInside) 이런 식으로 바꾸면 좋을 듯 합니다! 왜냐하면 입력이될 때마다, if문이 돌아가는데, 그때마다 addTarget이 되는 것이 불필요하다고 생각이 들어서 입니다~! 그리고 isEnabled가 활성화/비활성화 역할을 충분히 해주기 때문에 괜찮을 것 같습니다~
> 
> 아니면 isEnabled를 지우고, if문에는 addTarget, else문에는 removeTarget를 해도 될 것 같습니다~
> 
> * 문득 궁금증이 생겼습니다. 만약 계속 button에 addTarget를 해주면 어떻게하지?
>   찾아본 결과, 하나만 저장하는 것 같습니다!
>   (https://stackoverflow.com/questions/24845469/uibutton-addtarget-multiple-times-on-same-target-action-only-calls-once)

c281ad7 꼼꼼한 리뷰 감사합니다! 입력되는 동안 계속 if문이 돌아갈거라는 생각을 못했네요..!

2022-11-15 13:35 UTC, CreoHwan approved these changes
고생하셨습니다 에디!

2022-11-15 19:06 UTC, JUNY0110 commented
코드가 많이 복잡해, 추후 리팩토링 과정을 반드시 거치도록 하겠습니다!

2022-11-15 19:08 UTC, merged