[Feature] API 연동 준비 / 로그인 뷰 POST 만들기
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #113
Opened 2022-11-11 08:26 UTC by CreoHwan

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- API 연동 준비 세팅
- 로그인 뷰 POST 기능 구현

## Key Changes 🔥 (주요 구현/변경 사항)

## ToDo 📆 (남은 작업)
- [ ] 토큰 발행

## ScreenShot 📷 (참고 사진)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)

## Reference 🔗
- URL Session 관련: https://gyuios.tistory.com/108
- Codable vs jsonSerialization: https://learn-hyeoni.tistory.com/45
- 프로토콜 관련: https://zeddios.tistory.com/255

## Close Issues 🔒 (닫을 Issue)
Close #108 #109

2022-11-15 15:54 UTC, JUNY0110 requested changes
고생하셨습니다..! 정말정말 공부해야할 부분들이 많네요.. 많은 고민을 했을 것 같습니다

2022-11-15 15:54 UTC, JUNY0110 commented on Network/EndPoint/LoginEndPoint.swift
> +    }
p2.
setting과 body가 같은 용도로 사용되는데, 다른 변수를 주고 있습니다. 하나로 통일해도 좋을 것 같아요

2022-11-15 15:54 UTC, JUNY0110 commented on Network/Service/NetworkRequest.swift
> +        httpMethod: HTTPMethod
p2.
들여쓰기가 잘못잡혀있는 것 같습니다..!

2022-11-15 15:54 UTC, JUNY0110 commented on Samsam/ViewController/LoginViewController.swift
> +    }
p5.
controller 변수선언부와 request.requestedScopes를 줄구분을 하는 게 더 보기 좋을 것 같아요~

2022-11-15 15:54 UTC, JUNY0110 commented on Samsam/ViewController/LoginViewController.swift
> +}
Q.
코드 전반에 걸쳐 print문이 굉장히 많은데, 추후 수정되거나 삭제되는 것이 맞을까요?

2022-11-15 15:54 UTC, JUNY0110 commented on Network/EndPoint/LoginEndPoint.swift
> +    }
Get을 연산프로퍼티를 활용해 값을 반환하는 것 잘 배웠습니다..!

2022-11-15 16:10 UTC, JUNY0110 requested changes
추가로 확인된 부분이 있어 리뷰 남깁니다~~

2022-11-15 16:10 UTC, JUNY0110 commented on Samsam/ViewController/LoginViewController.swift
> +
p1.
어떤 용도로 사용될 viewWillAppear일까요?

2022-11-15 21:04 UTC, taek0622 requested changes
고생하셨습니다.
수정 필요해보이는 부분에 리뷰 남겼습니다.
확인 부탁드립니다~

2022-11-15 21:04 UTC, ikanic commented on Network/API/LoginAPI.swift
> +            .startAppleLogin(LoginDTO: LoginDTO)
p2;
`LoginAPI`의 `startAppleLogin` func의 형태와 `LoginEndPoint`의 `startAppleLogin`의 이름 및 형태가 너무 똑같아서, 자칫 혼동을 줄 수 있을 것 같습니다.
endPoint에 들어가는 case의 파라미터명을 변경하는 것이 더 좋을 것 같습니다.

2022-11-15 21:04 UTC, ikanic commented on Network/Service/APIService.swift
> +        guard let encodedUrl = request.url.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed),
p1;
코드 전반적으로 url이라는 단어에 대해서 약어 컨벤션이 지켜지고 있지 않는 것 같습니다.
약어 컨벤션을 지켜주세요.

2022-11-15 21:04 UTC, ikanic commented on Network/Service/APIService.swift
> +        print("encodedUrl = \(encodedUrl)")
p1;
코드 전반적으로 불필요한 print문이 많이 사용되고 있습니다.
PR을 올릴때는 전부 삭제 부탁드립니다.

2022-11-15 21:04 UTC, taek0622 commented on Samsam/ViewController/LoginViewController.swift
> +}
p1;
해당 부분 또한 print 전부 삭제 부탁드립니다.
또한, print를 제외한 내부 로직이 없다면 catch문이 필요한 이유가 있을까요?
각 catch문에 올바른 내부 로직이 필요할 것 같습니다.

2022-11-15 21:04 UTC, taek0622 commented on Samsam/ViewController/LoginViewController.swift
> +    }
p1;
에러를 print만 해주고 그 외의 처리를 해주지 않는다면 불필요한 코드가 될 것 같습니다.
내부적으로 에러가 발생했을때 다른 처리를 하는 코드가 필요해보여요.

2022-11-16 01:31 UTC, CreoHwan commented on Network/EndPoint/LoginEndPoint.swift
> +    }
> p2. setting과 body가 같은 용도로 사용되는데, 다른 변수를 주고 있습니다. 하나로 통일해도 좋을 것 같아요

71980dc 감사합니다!

2022-11-16 01:36 UTC, CreoHwan commented on Network/Service/NetworkRequest.swift
> +        httpMethod: HTTPMethod
> p2. 들여쓰기가 잘못잡혀있는 것 같습니다..!

dd05e7b 감사합니다~!

2022-11-16 01:37 UTC, CreoHwan commented on Samsam/ViewController/LoginViewController.swift
> +    }
> p5. controller 변수선언부와 request.requestedScopes를 줄구분을 하는 게 더 보기 좋을 것 같아요~

6808632 감사합니다~~

2022-11-16 01:38 UTC, CreoHwan commented on Network/EndPoint/LoginEndPoint.swift
> +    }
> Get을 연산프로퍼티를 활용해 값을 반환하는 것 잘 배웠습니다..!

감사합니다!! 굿굿 입니다!

2022-11-16 01:41 UTC, CreoHwan commented on Samsam/ViewController/LoginViewController.swift
> +
> p1. 어떤 용도로 사용될 viewWillAppear일까요?

8ef1898 제가 잠시 머리가 이상해진 것 같습니다 하하~

2022-11-16 02:00 UTC, CreoHwan commented on Network/Service/APIService.swift
> +        print("encodedUrl = \(encodedUrl)")
> p1; 코드 전반적으로 불필요한 print문이 많이 사용되고 있습니다. PR을 올릴때는 전부 삭제 부탁드립니다.

da8f3b3 넵!

2022-11-16 02:03 UTC, CreoHwan commented on Network/API/LoginAPI.swift
> +            .startAppleLogin(LoginDTO: LoginDTO)
> p2; `LoginAPI`의 `startAppleLogin` func의 형태와 `LoginEndPoint`의 `startAppleLogin`의 이름 및 형태가 너무 똑같아서, 자칫 혼동을 줄 수 있을 것 같습니다. endPoint에 들어가는 case의 파라미터명을 변경하는 것이 더 좋을 것 같습니다.

이 부분은 일부러 똑같이 만들었습니다! LoginAPI랑 LoginEndpoint가 서로 연관이 있기 때문입니다!

2022-11-16 02:20 UTC, CreoHwan commented on Network/Service/APIService.swift
> +        guard let encodedUrl = request.url.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed),
> p1; 코드 전반적으로 url이라는 단어에 대해서 약어 컨벤션이 지켜지고 있지 않는 것 같습니다. 약어 컨벤션을 지켜주세요.

599e53b 넵 감사합니다~

2022-11-16 02:23 UTC, CreoHwan commented on Samsam/ViewController/LoginViewController.swift
> +}
> p1; 해당 부분 또한 print 전부 삭제 부탁드립니다. 또한, print를 제외한 내부 로직이 없다면 catch문이 필요한 이유가 있을까요? 각 catch문에 올바른 내부 로직이 필요할 것 같습니다.

755f8b0 일단 삭제했습니다! 추후에 논의해보면 좋을 것 같습니다~

2022-11-16 02:23 UTC, CreoHwan commented on Samsam/ViewController/LoginViewController.swift
> +    }
> p1; 에러를 print만 해주고 그 외의 처리를 해주지 않는다면 불필요한 코드가 될 것 같습니다. 내부적으로 에러가 발생했을때 다른 처리를 하는 코드가 필요해보여요.

755f8b0 일단 삭제했습니다! 추후 논의해보면 좋을 것 같습니다~

2022-11-16 02:24 UTC, CreoHwan commented on Samsam/ViewController/LoginViewController.swift
> +}
> Q. 코드 전반에 걸쳐 print문이 굉장히 많은데, 추후 수정되거나 삭제되는 것이 맞을까요?

755f8b0 추후 논의해보면 좋을 것 같습니다~~!

2022-11-16 06:49 UTC, CreoHwan reviewed
[6f97b16] 제가 name이 nil일 때 처리하는 방법을 생각해봤습니다!
First Second가 둘 다 nil일 경우, 하나만 nil일 경우, 둘 다 nil이 아닌 경우가 있어서,
이 모든 상황을 컨트롤 하기에는 지금 구현한 방식이 제일 나을 것 같다는 생각이 들었습니다!
의견 있으면 편하게 말씀해주시면 감사하겠습니다~

2022-11-16 08:20 UTC, JUNY0110 approved these changes
고생하셨습니다~

2022-11-16 12:59 UTC, ikanic commented on Network/API/LoginAPI.swift
> +            .startAppleLogin(LoginDTO: LoginDTO)
> > p2; `LoginAPI`의 `startAppleLogin` func의 형태와 `LoginEndPoint`의 `startAppleLogin`의 이름 및 형태가 너무 똑같아서, 자칫 혼동을 줄 수 있을 것 같습니다. endPoint에 들어가는 case의 파라미터명을 변경하는 것이 더 좋을 것 같습니다.
> 
> 이 부분은 일부러 똑같이 만들었습니다! LoginAPI랑 LoginEndpoint가 서로 연관이 있기 때문입니다!

그 둘이 연관이 있다는 것은 이미 인지하고 있습니다만, 현재와 같은 경우 그냥 보았을때 function을 재귀하고 있다고 생각이 듭니다.
혼자 작성하는 코드일 때에도 지양해야할 부분이라고 생각합니다만, 개인 프로젝트일 때에는 모든 코드를 본인이 짜기 때문에 비교적 코드 파악이 쉽습니다. 하지만 협업의 경우 이렇게 아예 같아보이는 코드를 작성하게 되면 다른 읽는 사람들에게 혼동을 주기 쉽습니다.
그렇기 때문에 최소 case에 들어가는 파라미터라도 변경하는 것이 더 좋을 것 같습니다. 협업은 혼자 읽는 코드가 아니라 함께 읽을 코드를 작성하는 일이니까요.

2022-11-16 13:03 UTC, ikanic commented on Network/Service/APIService.swift
> +        guard let encodedUrl = request.url.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed),
> > p1; 코드 전반적으로 url이라는 단어에 대해서 약어 컨벤션이 지켜지고 있지 않는 것 같습니다. 약어 컨벤션을 지켜주세요.
> 
> [599e53b](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/599e53b801a2ddbde779a405d6eaa76178a8af8a) 넵 감사합니다~

반영확인했습니다만, 모든 약어가 전부 대문자가 되면 안됩니다. 변수 등에 사용된 약어가 변수명의 맨처음에 올때에는 전부 소문자로 사용하는 컨벤션이 있습니다. 재확인 부탁드려요.

2022-11-16 13:05 UTC, taek0622 commented on Network/Service/APIService.swift
> +        print("encodedUrl = \(encodedUrl)")
> > p1; 코드 전반적으로 불필요한 print문이 많이 사용되고 있습니다. PR을 올릴때는 전부 삭제 부탁드립니다.
> 
> [da8f3b3](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/da8f3b379527183919709d4819a17a11b7d0ff3d) 넵!

확인했습니다. 리뷰 리졸브합니다.

2022-11-16 13:05 UTC, ikanic commented on Samsam/ViewController/LoginViewController.swift
> +}
> > p1; 해당 부분 또한 print 전부 삭제 부탁드립니다. 또한, print를 제외한 내부 로직이 없다면 catch문이 필요한 이유가 있을까요? 각 catch문에 올바른 내부 로직이 필요할 것 같습니다.
> 
> [755f8b0](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/755f8b0a878ca6487d833969d393a6b31f8957e9) 일단 삭제했습니다! 추후에 논의해보면 좋을 것 같습니다~

확인했습니다. 리뷰 리졸브합니다.

2022-11-16 13:05 UTC, taek0622 commented on Samsam/ViewController/LoginViewController.swift
> +    }
> > p1; 에러를 print만 해주고 그 외의 처리를 해주지 않는다면 불필요한 코드가 될 것 같습니다. 내부적으로 에러가 발생했을때 다른 처리를 하는 코드가 필요해보여요.
> 
> [755f8b0](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/755f8b0a878ca6487d833969d393a6b31f8957e9) 일단 삭제했습니다! 추후 논의해보면 좋을 것 같습니다~

확인했습니다. 리뷰 리졸브합니다.

2022-11-17 01:32 UTC, CreoHwan commented on Network/Service/APIService.swift
> +        guard let encodedUrl = request.url.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed),
> > > p1; 코드 전반적으로 url이라는 단어에 대해서 약어 컨벤션이 지켜지고 있지 않는 것 같습니다. 약어 컨벤션을 지켜주세요.
> > 
> > 
> > [599e53b](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/599e53b801a2ddbde779a405d6eaa76178a8af8a) 넵 감사합니다~
> 
> 반영확인했습니다만, 모든 약어가 전부 대문자가 되면 안됩니다. 변수 등에 사용된 약어가 변수명의 맨처음에 올때에는 전부 소문자로 사용하는 컨벤션이 있습니다. 재확인 부탁드려요.

다 변경한 것 같습니다~!

2022-11-17 02:10 UTC, CreoHwan commented on Network/API/LoginAPI.swift
> +            .startAppleLogin(LoginDTO: LoginDTO)
> > > p2; `LoginAPI`의 `startAppleLogin` func의 형태와 `LoginEndPoint`의 `startAppleLogin`의 이름 및 형태가 너무 똑같아서, 자칫 혼동을 줄 수 있을 것 같습니다. endPoint에 들어가는 case의 파라미터명을 변경하는 것이 더 좋을 것 같습니다.
> > 
> > 
> > 이 부분은 일부러 똑같이 만들었습니다! LoginAPI랑 LoginEndpoint가 서로 연관이 있기 때문입니다!
> 
> 그 둘이 연관이 있다는 것은 이미 인지하고 있습니다만, 현재와 같은 경우 그냥 보았을때 function을 재귀하고 있다고 생각이 듭니다. 혼자 작성하는 코드일 때에도 지양해야할 부분이라고 생각합니다만, 개인 프로젝트일 때에는 모든 코드를 본인이 짜기 때문에 비교적 코드 파악이 쉽습니다. 하지만 협업의 경우 이렇게 아예 같아보이는 코드를 작성하게 되면 다른 읽는 사람들에게 혼동을 주기 쉽습니다. 그렇기 때문에 최소 case에 들어가는 파라미터라도 변경하는 것이 더 좋을 것 같습니다. 협업은 혼자 읽는 코드가 아니라 함께 읽을 코드를 작성하는 일이니까요.

a7932ce 확인했습니다! 감사합니다~

2022-11-17 02:16 UTC, taek0622 commented on Network/API/LoginAPI.swift
> +            .startAppleLogin(LoginDTO: LoginDTO)
> LoginEndPoint

확인했습니다. 리뷰 리졸브합니다.

2022-11-17 02:18 UTC, taek0622 commented on Network/Service/APIService.swift
> +        guard let encodedUrl = request.url.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed),
> > > > p1; 코드 전반적으로 url이라는 단어에 대해서 약어 컨벤션이 지켜지고 있지 않는 것 같습니다. 약어 컨벤션을 지켜주세요.
> > > 
> > > 
> > > [599e53b](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/599e53b801a2ddbde779a405d6eaa76178a8af8a) 넵 감사합니다~
> > 
> > 
> > 반영확인했습니다만, 모든 약어가 전부 대문자가 되면 안됩니다. 변수 등에 사용된 약어가 변수명의 맨처음에 올때에는 전부 소문자로 사용하는 컨벤션이 있습니다. 재확인 부탁드려요.
> 
> 다 변경한 것 같습니다~!

확인했습니다. 리뷰 리졸브합니다.

2022-11-17 02:18 UTC, taek0622 approved these changes
고생하셨습니다~

2022-11-17 02:19 UTC, merged