[Design] 문의내역 뷰 만들기
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #117
Opened 2022-11-15 14:28 UTC by CreoHwan

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 문의내역 뷰 만들기

## Key Changes 🔥 (주요 구현/변경 사항)
- HistoryView - InquiryHistoryView 폴더에서 3개의 파일을 만들었습니다.
- InquiryCell 은 문의내역 content 셀입니다.
- AsHeaderCell 은 As 남은 기간 header입니다.
- InquiryHistoryViewController 은 구현한 뷰 입니다.

## ToDo 📆 (남은 작업)
- [ ] API 연동 작업이 필요합니다.

## ScreenShot 📷 (참고 사진)
![Simulator Screen Recording - iPhone 14 - 2022-11-15 at 23 26 53](https://user-images.githubusercontent.com/92836045/201944184-f451ea5f-7a5f-4506-ac9c-613e1a68d6b2.gif)

## To Reviewers 🙏 (리뷰어에게 전달
<img width="848" alt="스크린샷 2022-11-15 23 26 13" src="https://user-images.githubusercontent.com/92836045/201943932-5c3e05fc-e0ed-44d1-8c34-c65a2c2ebecd.png">
하고 싶은 말)

- 현재는 header1, header2 로 선언했습니다. 1은 메트로이고, 2는 AS 남은 기간입니다. 추후 API 연동 작업에서 수정하면 될 것 같습니다. 감사합니다.

## Reference 🔗

## Close Issues 🔒 (닫을 Issue)
Close #115

2022-11-15 15:44 UTC, JUNY0110 approved these changes
고생하셨습니다~

2022-11-15 20:42 UTC, taek0622 requested changes
고생하셨습니다.
수정이 필요해 보이는 부분 리뷰 남겼습니다. 확인부탁드려요~

2022-11-15 20:42 UTC, taek0622 commented on Samsam/ViewController/HistoryView/InquiryHistoryView/AsHeaderCell.swift
> +
p2;
약어는 모두 소문자, 혹은 모두 대문자가 되어야 합니다.
지금과 같은 경우 대문자로 시작하기 때문에 ASHeaderCell이 되어야 할 것 같습니다.

2022-11-15 20:42 UTC, taek0622 commented on Samsam/ViewController/HistoryView/InquiryHistoryView/AsHeaderCell.swift
> +            height: 25
p2;
해당 부분의 width와 height은 직접 지정하지 않는 것이 좋을 것 같습니다.

2022-11-15 20:42 UTC, taek0622 commented on Samsam/ViewController/HistoryView/InquiryHistoryView/AsHeaderCell.swift
> +        remainingText.centerY(inView: remainingView)
p1;
remainingDay와 remainigText의 위치 관계를 확실히 해야할 것 같습니다.
현재 상태에서는 간헐적으로 remaingDay와 remaingText의 위치가 뒤바뀌는 현상이 발생합니다.

2022-11-15 20:42 UTC, taek0622 commented on Samsam/ViewController/HistoryView/InquiryHistoryView/InquiryCell.swift
> +
p1;
해당 셀은 새로 만들기 보단 기존 시공상황의 셀을 그대로 사용하는 것이 더 좋을 것 같습니다.

2022-11-15 20:42 UTC, taek0622 commented on Samsam/ViewController/HistoryView/InquiryHistoryView/InquiryHistoryViewController.swift
> +    private let inquiryHistoryView: UICollectionView = {
p3;
`InquiryHistoryView` 또한 결국 시공내역과 뷰 자체는 차이가 없는 것 같습니다.
해당 뷰도 어떻게하면 재사용할 수 있을지 고민해보면 좋을 것 같네요.

2022-11-16 12:52 UTC, CreoHwan commented on Samsam/ViewController/HistoryView/InquiryHistoryView/AsHeaderCell.swift
> +
> p2; 약어는 모두 소문자, 혹은 모두 대문자가 되어야 합니다. 지금과 같은 경우 대문자로 시작하기 때문에 ASHeaderCell이 되어야 할 것 같습니다.

66b6680 감사합니다~

2022-11-16 12:53 UTC, CreoHwan commented on Samsam/ViewController/HistoryView/InquiryHistoryView/InquiryCell.swift
> +
> p1; 해당 셀은 새로 만들기 보단 기존 시공상황의 셀을 그대로 사용하는 것이 더 좋을 것 같습니다.

기존 셀에서는 철거, 화장실 등의 UILabel이 있어서, 따로 생성했습니다!

2022-11-16 12:55 UTC, taek0622 commented on Samsam/ViewController/HistoryView/InquiryHistoryView/AsHeaderCell.swift
> +
> > p2; 약어는 모두 소문자, 혹은 모두 대문자가 되어야 합니다. 지금과 같은 경우 대문자로 시작하기 때문에 ASHeaderCell이 되어야 할 것 같습니다.
> 
> [66b6680](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/66b668094258149f0854ede8d69e1ae2aae1d879) 감사합니다~

확인했습니다. 리뷰 리뷰 리졸브합니다.

2022-11-16 15:43 UTC, taek0622 requested changes
리뷰 필요한 곳이 보여 추가 리뷰 남깁니다.

2022-11-16 15:43 UTC, taek0622 commented on Samsam/ViewController/HistoryView/InquiryHistoryView/InquiryHistoryViewController.swift
> +    }()
p4;
해당 부분은 현재와 같이도 작성할 수 있지만, 다른 뷰 컴포넌트들과의 통일성을 위해
```swift
private let inquiryHistoryView: UICollectionView = {
    let flowLayout = UICollectionViewFlowLayout()
    flowLayout.sectionInset = UIEdgeInsets(top: 10, left: 0, bottom: 0, right: 0)
    $0.collectionViewLayout = flowLayout
    return $0
}(UICollectionView(frame: .zero, collectionViewLayout: UICollectionViewLayout()))
```
와 같이 작성할 수도 있을 것 같습니다.

2022-12-08 00:27 UTC, closed without merging