Design: 방 목록 뷰 레이아웃 그리기
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #12
Opened 2022-10-18 07:09 UTC by taek0622

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 방 목록의 레이아웃 그리기

## Key Changes 🔥 (주요 구현/변경 사항)
- RoomListViewController layout 추가
- RoomListView의 CollectionView에서 사용될 RoomListCell 추가

## ToDo 📆 (남은 작업)
- [ ] RoomListView 기능 작업
- [ ] 2차 스프린트에 추가될 레이아웃 작업

## ScreenShot 📷 (참고 사진)
<img src="https://user-images.githubusercontent.com/81027256/196360397-aafbe7e5-60a7-4d95-a15e-458e31adc0a9.gif" width=300>

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 간단한 레이아웃 작업이 너무 오래 걸렸네요. 꼼꼼한 리뷰 부탁드립니다.

## Reference 🔗
- 없음

## Close Issues 🔒 (닫을 Issue)
Close #7

2022-10-18 13:28 UTC, JUNY0110 requested changes
p2.
고생하셨습니다. 코드에 일부 궁금한 점을 질문으로 남겼으니 답변바랍니다~

2022-10-18 13:28 UTC, JUNY0110 commented on Samsam/ViewController/RoomListCell.swift
> +        $0.alignment = .bottom
Q.
alignment Bottom이 있는 것과 없는 것의 차이가 있을까요?
구현상에는 차이가 없어보입니다.

2022-10-18 13:28 UTC, JUNY0110 commented on Samsam/ViewController/RoomListCell.swift
> +    private let detailContentStack: UIStackView = {
p4.
변수명이 좋은 변수명인지 잘 모르겠습니다. 세부사항(detail)이 맞을까요?
dateTitleStack / dateStack같은 변수명이 시공일자, 준공예정 / 2022.10.17에서는 더 낫지 않을까 싶습니다.

2022-10-18 13:28 UTC, JUNY0110 commented on Samsam/ViewController/RoomListCell.swift
> +        roomStack.addArrangedSubview(rightSpacer)
Q.
cellStack은 다음 스프린트에 있을 초대코드공유하기 때문에 만들어져있는 아이가 맞을까요?

2022-10-18 13:28 UTC, JUNY0110 commented on Samsam/ViewController/RoomListViewController.swift
> +            paddingRight: 16,
p2.
좌우 패딩으로 잡으실거라면, 왜 safeAreaLayoutGuide를 주셨을까요? safeArea가 작동하지 않는 것 같습니다.

2022-10-18 13:28 UTC, JUNY0110 commented on Samsam/ViewController/RoomListViewController.swift
> +            bottom: view.safeAreaLayoutGuide.bottomAnchor,
p1.
CollectionView의 하단은 safeArea를 주지 않는 것이 더 자연스러울 것 같습니다. 스크롤을 내릴 때 등에서 부자연스러운 느낌을 줍니다.
![simulator_screenshot_867D341D-A532-4C6B-B2F9-CB0101816F62](https://user-images.githubusercontent.com/98405970/196442293-b9b63780-f6e3-4bdf-8721-611f4c5064ea.png)

2022-10-18 13:28 UTC, JUNY0110 commented on Samsam/ViewController/RoomListViewController.swift
> +        navigationController?.setNavigationBarHidden(false, animated: false)
p2.
setnavigationbarhidden의 항목이 둘 다 false인데 적은 이유가 있을까요?
디폴트값이 false라면 불필요한 코드가 될 것 같습니다.

2022-10-18 13:31 UTC, taek0622 commented on Samsam/ViewController/RoomListCell.swift
> +        $0.alignment = .bottom
> Q. alignment Bottom이 있는 것과 없는 것의 차이가 있을까요? 구현상에는 차이가 없어보입니다.

마지막 행인 `$0.alignment = .bottom`은 불필요한 코드가 맞습니다.
코드를 수정하다가 남은 잔재인 것 같네요. 해당 코드는 0925690 에서 삭제되었습니다. 감사합니다.

2022-10-18 13:33 UTC, ikanic commented on Samsam/ViewController/RoomListCell.swift
> +        roomStack.addArrangedSubview(rightSpacer)
> Q. cellStack은 다음 스프린트에 있을 초대코드공유하기 때문에 만들어져있는 아이가 맞을까요?

네, cellStack 다음 스프린트의 초대코드 공유하기 버튼을 추가하기 위해 만들어져 있는 스택입니다.

2022-10-18 13:36 UTC, taek0622 commented on Samsam/ViewController/RoomListViewController.swift
> +            paddingRight: 16,
> p2. 좌우 패딩으로 잡으실거라면, 왜 safeAreaLayoutGuide를 주셨을까요? safeArea가 작동하지 않는 것 같습니다.

safeAreaLayoutGuide는 정상 작동하고 있습니다. 해당 부분은 세로모드에서는 작동하지 않는 것처럼 보일 수 있습니다만, 가로모드에서는 확연하게 차이가 나는 것을 볼 수 있습니다.

저희 앱이 가로모드를 상정하지 않고 만들어지고 있습니다만, 그럼에도 불구하고 safeAreaLayoutGuide는 지켜주는 것이 맞다고 생각하여 safeAreaLayoutGuide와 패딩을 모두 넣어주었습니다.

2022-10-18 13:41 UTC, ikanic commented on Samsam/ViewController/RoomListViewController.swift
> +            bottom: view.safeAreaLayoutGuide.bottomAnchor,
> p1. CollectionView의 하단은 safeArea를 주지 않는 것이 더 자연스러울 것 같습니다. 스크롤을 내릴 때 등에서 부자연스러운 느낌을 줍니다. ![simulator_screenshot_867D341D-A532-4C6B-B2F9-CB0101816F62](https://user-images.githubusercontent.com/98405970/196442293-b9b63780-f6e3-4bdf-8721-611f4c5064ea.png)

해당 부분에 대해서 동감하여 81248bf 로 수정 반영했습니다.
다만, 해당 부분에 대해서는 다시 한 번 이야기 해보고 싶네요.

2022-10-18 13:47 UTC, taek0622 commented on Samsam/ViewController/RoomListViewController.swift
> +        navigationController?.setNavigationBarHidden(false, animated: false)
> p2. setnavigationbarhidden의 항목이 둘 다 false인데 적은 이유가 있을까요? 디폴트값이 false라면 불필요한 코드가 될 것 같습니다.

해당 부분은 8bf20f9 에서 뷰간 이동할 때 내비게이션이 더 자연스럽게 보일 수 있도록 animated 속성이 true로 변경되었습니다.

2022-10-18 14:36 UTC, taek0622 commented on Samsam/ViewController/RoomListCell.swift
> +    private let detailContentStack: UIStackView = {
> p4. 변수명이 좋은 변수명인지 잘 모르겠습니다. 세부사항(detail)이 맞을까요? dateTitleStack / dateStack같은 변수명이 시공일자, 준공예정 / 2022.10.17에서는 더 낫지 않을까 싶습니다.

안그래도 변수명에 대해 논의가 필요하다고 생각했는데, 좋은 변수명 추천 감사합니다.
해당 변경은 31d21c1 에서 반영되었습니다.

2022-10-18 14:37 UTC, taek0622 commented
@JUNY0110 리뷰해주신 부분 모두 수정 및 반영하였습니다. 다시 한 번 검토 부탁드립니다. 감사합니다.

2022-10-19 01:48 UTC, JUNY0110 approved these changes
고생하셨습니다

2022-10-19 01:48 UTC, merged