[Feataure] 전화번호 입력 뷰 데이터 통신 / 전화번호 입력 에러 수정
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #124
Opened 2022-11-18 11:56 UTC by CreoHwan

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 전화번호를 DB에 저장하기 위함

## Key Changes 🔥 (주요 구현/변경 사항)
- Message Struct를 만들었습니다. API 명세서에서 PUT 통신 성공시 message를 반환해주는데, 그것을 받기 위함입니다. 
- 전화번호 입력할 떄 오류가 있어 해결했습니다.

## ToDo 📆 (남은 작업)
- [ ] todo

## ScreenShot 📷 (참고 사진)
- 통신 관련하여서는 올리지 않겠습니다!
- 전화번호 입력 에러 수정
https://user-images.githubusercontent.com/92836045/202699782-dee1b5e5-b139-4ed4-943b-d48aa4d861f0.mp4

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 기존의 API Setting을 이용하여 구현해봤습니다. 제가 작업한 것을 보시면... 조금은 감이 잡히실 것 같습니다!!

## Reference 🔗

## Close Issues 🔒 (닫을 Issue)
Close #120

2022-11-21 17:06 UTC, taek0622 reviewed
고생하셨습니다.
수정되면 좋을 것 같은 부분에 리뷰 남겼습니다.
확인 부탁드려요~

2022-11-21 17:06 UTC, ikanic commented on Samsam/ViewController/PhoneNumViewController.swift
> +        if phoneNum.count >= maxLength {
p3;
아래에서는 자릿수를 8이라는 숫자로 직접 지정했는데 이곳에서는 maxLength를 사용하고 있네요. 굳이 다르게 할 이유가 없을 것 같아서 여기도 그냥 8로 지정하는 것이 좋을 것 같습니다.
또한, 메서드 순서가 가독성에 좋지 못합니다.
현재 메서드가 아래의 메서드에서 사용되고 있는 상황이라 메서드 순서가 반대가 되면 더 좋을 것 같습니다.

2022-11-21 17:11 UTC, JUNY0110 requested changes
고생하셨습니다~

2022-11-21 17:11 UTC, JUNY0110 commented on Samsam/ViewController/PhoneNumViewController.swift
> +        if phoneNum.count >= maxLength {
p2. 
```swift
    @objc private func buttonAttributeChanged() {
         phoneNum = (numberInput.text?.replacingOccurrences(of: " - ", with: ""))!
         if phoneNum.count >= 8 {
             submitButton.backgroundColor = .blue
             submitButton.isEnabled = true
             checkText(textField: numberInput, phoneNum: phoneNum, maxLength: 8)
         } else {
             submitButton.backgroundColor = .gray
             submitButton.isEnabled = false
         }
     }
```
이미 해당부분에서 같은 조건을 주고 있어 전화번호 글자수를 기준으로 조건을 주는 것은 불필요한 코드같습니다.

2022-11-22 00:57 UTC, CreoHwan commented on Samsam/ViewController/PhoneNumViewController.swift
> +        if phoneNum.count >= maxLength {
> p3; 아래에서는 자릿수를 8이라는 숫자로 직접 지정했는데 이곳에서는 maxLength를 사용하고 있네요. 굳이 다르게 할 이유가 없을 것 같아서 여기도 그냥 8로 지정하는 것이 좋을 것 같습니다. 또한, 메서드 순서가 가독성에 좋지 못합니다. 현재 메서드가 아래의 메서드에서 사용되고 있는 상황이라 메서드 순서가 반대가 되면 더 좋을 것 같습니다.

554d2eb 넵 감사합니다!

2022-11-22 00:57 UTC, creohwan commented on Samsam/ViewController/PhoneNumViewController.swift
> +        if phoneNum.count >= maxLength {
> p2.
> 
> ```swift
>     @objc private func buttonAttributeChanged() {
>          phoneNum = (numberInput.text?.replacingOccurrences(of: " - ", with: ""))!
>          if phoneNum.count >= 8 {
>              submitButton.backgroundColor = .blue
>              submitButton.isEnabled = true
>              checkText(textField: numberInput, phoneNum: phoneNum, maxLength: 8)
>          } else {
>              submitButton.backgroundColor = .gray
>              submitButton.isEnabled = false
>          }
>      }
> ```
> 
> 이미 해당부분에서 같은 조건을 주고 있어 전화번호 글자수를 기준으로 조건을 주는 것은 불필요한 코드같습니다.

넵! 감사합니다! 554d2eb

2022-11-22 15:15 UTC, JUNY0110 approved these changes
고생하셨습니다!

2022-11-23 00:20 UTC, taek0622 commented on Samsam/ViewController/PhoneNumViewController.swift
> +        if phoneNum.count >= maxLength {
> > p3; 아래에서는 자릿수를 8이라는 숫자로 직접 지정했는데 이곳에서는 maxLength를 사용하고 있네요. 굳이 다르게 할 이유가 없을 것 같아서 여기도 그냥 8로 지정하는 것이 좋을 것 같습니다. 또한, 메서드 순서가 가독성에 좋지 못합니다. 현재 메서드가 아래의 메서드에서 사용되고 있는 상황이라 메서드 순서가 반대가 되면 더 좋을 것 같습니다.
> 
> [554d2eb](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/554d2ebf465048adfc979eeca1b34a0b20db3c97) 넵 감사합니다!

확인했습니다. 리뷰 리졸브합니다.

2022-11-23 00:20 UTC, taek0622 approved these changes
고생하셨습니다.

2022-11-23 00:33 UTC, merged