[Feature] 시공상황뷰(WorkingHistoryView) URLSession Get 작업
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #130
Opened 2022-11-22 15:07 UTC by JUNY0110

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 시공상황뷰에 URLSession URL GET을 하기 위함.

## Key Changes 🔥 (주요 구현/변경 사항)
- **Room 데이터 바인딩 경로:** RoomListView -> SegmentControllView -> WorkingHistoryView
- **Post, Photo 데이터 바인딩 경로:** SegmentControllView -> WorkingHistoryView
- SegmentControllView에서 Post, Photo데이터를 호출하는 함수(loadPostByRoom, loadPhotoByRoom) 사용해 서버데이터 호출
- responseData를 최신순으로 받기 위해 post.reverse() / url.reverse()처리하였습니다.
- ```swift
    var posts = [Post]() {
        didSet {
            posts.forEach {
                loadPhotoByRoom(postID: $0.postID)
            }
            posts = posts.reversed()    // This Here!!
        }
    }
    var photos = [Photo]() {
        didSet {
            if photos.count == posts.count {
                for i in 0..<posts.count {
                    url.append(URL(string: photos[i].photoPath)!)
                }
                workingHistoryView.url = url.reversed()   // This Here!!
            }
        }
    }
    var url: [URL] = []
```
- request Data가 response할 때, 요청 순서대로 받아지지 않는 문제가 발생 -> WorkingHistoryView를 불러올 때마다 Photo 순서가 바뀝니다. -> Post는 제대로 오지만, Photo만 달라지기 때문에 Post와 Photo가 매칭되지 않는 문제가 있습니다.
- Photo 순서가 틀어지는 문제는 클라이언트에서, Photo와 Post가 매칭되지 않는 문제는 서버에서 해결할 필요가 있을 것 같습니다.

## ToDo 📆 (남은 작업)
- [ ] 날짜별 섹션 구분
- [ ] PhotoData response 시, 매번 다른 순서로 response되는 문제
- [ ] Metro에 진행률 표시
- [ ] 시공상황작성 버튼 클릭 시 선택된 카테고리만 나타나도록 수정

## ScreenShot 📷 (참고 사진)
![Simulator Screen Recording - iPhone 13 Pro - 2022-11-23 at 00 05 13](https://user-images.githubusercontent.com/98405970/203348503-98d5725e-cc26-43e4-8964-c80064e1b092.gif)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- Coredata와 관련해 주석처리한 부분이 많습니다. 다만, 다음 작업에서 빠뜨리지 않고 작업하기 위해 일부러 남겨둔 주석이니 게의치 않으셔도 됩니다.

## Close Issues 🔒 (닫을 Issue)
Close #No.

2022-11-22 16:08 UTC, taek0622 requested changes
고생하셨습니다.
URLSession 부분이 유독 복잡하고, 또 사진을 불러오는 부분에서 어려운 부분이 있던 것 같은데 정말 고생하셨어요.
수정이 필요할 것 같은 부분 리뷰 남겼습니다. 확인 부탁드려요~

2022-11-22 16:08 UTC, ikanic commented on Network/API/RoomAPI.swift
> +    func loadPhotobyroom(postID: Int) async throws -> [Photo]? {
p2;
`loadPhotobyroom`에 카멜케이스가 잘 적용되고 있지 않은 것 같습니다.

2022-11-22 16:08 UTC, ikanic commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +    var url: [URL] = []
p5;
property observer를 사용하는 property들은 너무 모여있으면 가독성이 좋지 못한 것 같습니다.
반드시 반영되어야할 것은 아니지만, property observer가 사용된 property 다음은 한 줄 띄워주시면 어떨까요?

2022-11-22 16:08 UTC, ikanic commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +    private func loadPhotoByRoom(postID: Int) {
p5;
가독성을 위해 띄어주시면 더 좋을 것 같습니다.

2022-11-22 16:08 UTC, ikanic commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +                workingHistoryView.post = posts
p2;
모든 게시물 정보가 시공상황은 아닙니다.
게시물 정보에는 문의 내역이 포함되어 있기 때문에 문의 내역을 필터링해서 workingHistoryView로 넘겨줄 필요가 있을 것 같습니다.

2022-11-22 16:08 UTC, ikanic commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +                workingHistoryView.photos = photos
p2;
마찬가지로 모든 사진 정보가 시공상황은 아닙니다.
문의 내역 사진 또한 포함되어 있기 때문에 문의 내역을 필터링해서 workingHistoryView로 넘겨줄 필요가 있을 것 같습니다.

2022-11-22 16:08 UTC, ikanic commented on Samsam/ViewController/HistoryView/WorkingHistoryView/WorkingHistoryViewController.swift
> +        didSet {
p2;
WorkingHistoryView에서는 실제로 photo가 사용되고 있지 않은 것 같습니다.
url이 그 부분을 대체하고 있는 것 같은데, 해당 부분을 photo로 전부 바꾸는 게 어떨까 싶습니다.

2022-11-22 16:08 UTC, ikanic commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +            }
p2;
사진이 현재 잘 정렬되고 있지 않은 것 같은데, 이 부분에서 수정해서 보내주면 좋을 것 같습니다.

2022-11-23 14:36 UTC, JUNY0110 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +            }
> p2;
> 사진이 현재 잘 정렬되고 있지 않은 것 같은데, 이 부분에서 수정해서 보내주면 좋을 것 같습니다.

66987d5
이미지 정렬했습니다~

2022-11-23 14:37 UTC, taek0622 commented
코드가 모두 엎어진 상황이라 기존 리뷰가 의미 없다고 판단, 기존 리뷰들을 모두 리졸브합니다.

2022-11-23 14:48 UTC, taek0622 requested changes
고생하셨습니다.
정말 오랜 시간 고민하셨고, 또 도중에 서버와도 논의해서 서버에서 받아오는 데이터 구조도 바뀌어서 api에서 데이터를 가져오는 코드도 완전 엎고 다시 작성하셨는데, 정말 너무너무 고생하셨어요.
일부 수정이 필요해 보이는 부분이 있어서 해당 부분 리뷰 남겼습니다. 확인 부탁드려요~

2022-11-23 14:48 UTC, taek0622 commented on Network/API/RoomAPI.swift
> +    func loadContentByRoom(roomID: Int) async throws -> [Post]? {
p5;
해당 방의 게시물 및 사진을 모두 가져오는 것이라 Content라는 이름도 좋지만, 결국 반환되는 값이 [Post] 배열이니 loadPostByRoom은 어떨까요?

2022-11-23 14:48 UTC, taek0622 commented on Network/EndPoint/RoomEndPoint.swift
> +    case loadContentsRoom(roomID: Int)
p5;
위와 마찬가지로 해당 이름을 사용하고 있는 곳은 위의 이름이 바뀐다면 함께 바뀌면 좋을 것 같습니다.
하지만, 바뀌지 않는다면 그대로 두어도 되겠네요.

2022-11-23 14:48 UTC, taek0622 commented on Network/EndPoint/RoomEndPoint.swift
> +            return "\(APIEnvironment.contentsURL)/\(roomID)"
p2;
APIEnvironment에 contentsURL이라는 새로운 것을 만든 것 같습니다만 해당 url은 한번밖에 사용되지 않습니다.
그래서 contentsURL을 새로 만들기보다는 기존에 있는 postURL을 가져다가 적당히 사용하는 것이 더 좋을 것 같습니다.

2022-11-23 14:48 UTC, taek0622 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +    var postIDArray: [Int] = []
p1;
해당 프로퍼티는 사용되지 않고 있습니다. 삭제 부탁드립니다.

2022-11-23 16:01 UTC, JUNY0110 commented on Network/EndPoint/RoomEndPoint.swift
> +            return "\(APIEnvironment.contentsURL)/\(roomID)"
6898325 수정했습니다~

2022-11-23 16:02 UTC, JUNY0110 commented on Network/EndPoint/RoomEndPoint.swift
> +    case loadContentsRoom(roomID: Int)
> p5;
> 위와 마찬가지로 해당 이름을 사용하고 있는 곳은 위의 이름이 바뀐다면 함께 바뀌면 좋을 것 같습니다.
> 하지만, 바뀌지 않는다면 그대로 두어도 되겠네요.

abf288e 수정했습니다~

2022-11-23 16:02 UTC, JUNY0110 commented on Network/API/RoomAPI.swift
> +    func loadContentByRoom(roomID: Int) async throws -> [Post]? {
> p5;
> 해당 방의 게시물 및 사진을 모두 가져오는 것이라 Content라는 이름도 좋지만, 결국 반환되는 값이 [Post] 배열이니 loadPostByRoom은 어떨까요?

abf288e 수정했습니다~

2022-11-23 16:02 UTC, JUNY0110 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +    var postIDArray: [Int] = []
> p1;
> 해당 프로퍼티는 사용되지 않고 있습니다. 삭제 부탁드립니다.

d4df3ef 수정했습니다~

2022-11-23 16:04 UTC, taek0622 commented on Network/EndPoint/RoomEndPoint.swift
> +    case loadContentsRoom(roomID: Int)
> > p5;
> > 위와 마찬가지로 해당 이름을 사용하고 있는 곳은 위의 이름이 바뀐다면 함께 바뀌면 좋을 것 같습니다.
> > 하지만, 바뀌지 않는다면 그대로 두어도 되겠네요.
> 
> [abf288e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/abf288eeaba832ee7aff00f7dc59a26859192d64) 수정했습니다~

확인했습니다. 리뷰 리졸브합니다~

2022-11-23 16:05 UTC, taek0622 commented on Network/EndPoint/RoomEndPoint.swift
> +            return "\(APIEnvironment.contentsURL)/\(roomID)"
> [6898325](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/68983258185d66959a3a924edc5b964a844a21a6) 수정했습니다~

확인했습니다. 리뷰 리졸브합니다~

2022-11-23 16:06 UTC, taek0622 commented on Network/API/RoomAPI.swift
> +    func loadContentByRoom(roomID: Int) async throws -> [Post]? {
> > p5;
> > 해당 방의 게시물 및 사진을 모두 가져오는 것이라 Content라는 이름도 좋지만, 결국 반환되는 값이 [Post] 배열이니 loadPostByRoom은 어떨까요?
> 
> [abf288e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/abf288eeaba832ee7aff00f7dc59a26859192d64) 수정했습니다~

확인했습니다. 리뷰 리졸브합니다~

2022-11-23 16:07 UTC, taek0622 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +    var postIDArray: [Int] = []
> > p1;
> > 해당 프로퍼티는 사용되지 않고 있습니다. 삭제 부탁드립니다.
> 
> [d4df3ef](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/d4df3ef5003c7a156fc2ed71349f70ade36c1f06) 수정했습니다~

확인했습니다. 리뷰 리졸브합니다~

2022-11-23 16:09 UTC, ikanic approved these changes
고생하셨습니다.
정말 많은 코드가 갈아 엎어졌는데, 진짜 너무너무 고생 많으셨어요.
아직 남은 테스크가 좀 되는 걸로 알고 있는데, 앞으로도 잘 부탁드립니다 에디~

2022-11-24 01:32 UTC, merged