[Feature] 설정 뷰 만들기 / 방 정보 수정 기능 구현
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #139
Opened 2022-11-29 05:59 UTC by CreoHwan

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 설정 뷰 만들기
- 방 정보 수정 기능 구현

## Key Changes 🔥 (주요 구현/변경 사항)

## ToDo 📆 (남은 작업)
- [ ] 이름, 전화번호 수정 기능 추후 구현해야 함

## ScreenShot 📷 (참고 사진)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)

## Reference 🔗
- UITabelView 관련: (오른쪽 글씨 쓸 때 참조한 링크)
https://velog.io/@jangdev/UITableView

## Close Issues 🔒 (닫을 Issue)
Close #128

2022-11-30 01:07 UTC, JUNY0110 requested changes
고생하셨습니다~

2022-11-30 01:07 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/RoomCategoryViewController.swift
> +    var warrantyTime: Int?
Q.
warrantyTime을 12에서 옵셔널로 준 이유가 있을까요?

2022-11-30 01:07 UTC, JUNY0110 commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +
p3. 아직 연결이 되어있지 않아 확인이 어렵습니다..!

2022-11-30 01:07 UTC, JUNY0110 commented on Samsam/ViewController/SettingView/SettingRoomViewController.swift
> +        let cell = UITableViewCell(style: .value1, reuseIdentifier: .none)
TableView에 이런 기능이 있는 줄은 몰랐네요..!👍

2022-11-30 01:07 UTC, JUNY0110 commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +
추후 '전화번호'는 최초 가입 시 입력했던 전화번호가 입력되면 좋을 것 같습니다~

2022-11-30 01:07 UTC, JUNY0110 commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +        case [2,2]:
p3.
options를 별도 사용할 것이 아니라면, 삭제하는 게 더 깔끔할 것 같아요~

2022-11-30 01:07 UTC, JUNY0110 commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +
p2. 
header가 헤더 갯수 외에는 사용되지 않고 있는 것 같습니다.
`data.count`로 변경하면 header를 선언하지 않아도 될 것 같아요

2022-11-30 01:07 UTC, JUNY0110 commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +}
p3.
completion이 nil이라면 삭제해도 될 것 같습니다.
completion은 navigation 또는 modal 종료 후 실행할 것이 있을 때 사용하는 비동기함수인데 따로 사용할 게 없는 것 같아서요..!
[김종권 - 화면전환(present, navigation, segue)](https://ios-development.tistory.com/19)
[애플 공식문서](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621380-present)
<img width="811" alt="스크린샷 2022-11-30 오전 10 04 51" src="https://user-images.githubusercontent.com/98405970/204682344-427984d1-9cef-4a91-91bc-aeef371b74d6.png">

2022-11-30 01:13 UTC, CreoHwan commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +
> 추후 '전화번호'는 최초 가입 시 입력했던 전화번호가 입력되면 좋을 것 같습니다~

업자는 전화번호를 입력하지 않긴 합니다! 그래서 따로 연락이 필요한 경우를 위해 적어뒀습니다!

2022-11-30 01:13 UTC, CreoHwan commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +
> 추후 '전화번호'는 최초 가입 시 입력했던 전화번호가 입력되면 좋을 것 같습니다~

좋은 생각 같습니다!

2022-11-30 01:15 UTC, CreoHwan commented on Samsam/ViewController/RoomCreationView/RoomCategoryViewController.swift
> +    var warrantyTime: Int?
> Q. warrantyTime을 12에서 옵셔널로 준 이유가 있을까요?

RoomCreationViewController에서 바인딩으로 넘어올 것이라, RoomCategoryViewContorller에서 값을 설정하고 싶지 않아서, 옵셔널로 선언했습니다!

2022-11-30 01:18 UTC, CreoHwan commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +        case [2,2]:
> p3. options를 별도 사용할 것이 아니라면, 삭제하는 게 더 깔끔할 것 같아요~

9781445 감사합니다!

2022-11-30 01:22 UTC, CreoHwan commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +
> p2. header가 헤더 갯수 외에는 사용되지 않고 있는 것 같습니다. `data.count`로 변경하면 header를 선언하지 않아도 될 것 같아요

1af895c 감사합니다~

2022-11-30 01:26 UTC, CreoHwan commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +}
> p3. completion이 nil이라면 삭제해도 될 것 같습니다. completion은 navigation 또는 modal 종료 후 실행할 것이 있을 때 사용하는 비동기함수인데 따로 사용할 게 없는 것 같아서요..! [김종권 - 화면전환(present, navigation, segue)](https://ios-development.tistory.com/19) [애플 공식문서](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621380-present) <img alt="스크린샷 2022-11-30 오전 10 04 51" width="811" src="https://user-images.githubusercontent.com/98405970/204682344-427984d1-9cef-4a91-91bc-aeef371b74d6.png">

336a6be 감사합니다!

2022-11-30 01:39 UTC, taek0622 requested changes
고생하셨습니다.
정말 많은 작업량이네요.
수정이 필요한 부분 리뷰 남겼습니다.
추가로, 현재 코드에서 어디에 있는지 찾을 수가 없어서 남기지 못한 리뷰가 있는데, 달력에서 날짜를 선택했을때, 날짜 표기하는 쪽에 형식이 기존 형식과 다른 것 같습니다. `22.11.30` 형식이 현재 `2022-11-30`으로 보이고 있는 것 같아요. 해당 부분도 수정 부탁드립니다.

2022-11-30 01:39 UTC, ikanic commented on Network/API/RoomAPI.swift
> +    }
p3;
이 부분에서 Message를 응답받을 필요가 있을까요?
Message가 별도로 사용될 일은 없을 것 같아서 Message를 반환받을 필요가 없을 것 같습니다.
해당 동작이 정상적으로 끝났다, 끝나지 않았다를 판단하기 위함이라면 응답으로 statusCode가 200대일 때, true를 반환하는 등으로 하는 것이 더 좋을 것 같습니다.

2022-11-30 01:39 UTC, ikanic commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +    private let header = ["","","",""]
p1;
이렇게 다른 내용이 없는 배열로 사용할 것이라면 이 부분이 왜 필요한 것일까요?

2022-11-30 01:39 UTC, ikanic commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +        return header.count
p1;
이 부분만을 위해 header가 존재하는 것이라면, header를 만들어서 header.count를 하는 것보다는 data.count를 하는 것이 더 좋을 것 같습니다.

2022-11-30 01:39 UTC, ikanic commented on Network/API/RoomAPI.swift
> +    func loadRoomByRoomID(roomID: Int) async throws -> Room? {
p2;
특정 방 정보는 원래 roomID로 불러오므로 loadRoomByRoomID보다는 loadRoom이 되는 것이 더 좋을 것 같습니다.

2022-11-30 01:39 UTC, taek0622 commented on Samsam/ViewController/SettingView/SettingRoomViewController.swift
> +    private var invitecode: String?
p1;
invitecode의 네이밍 컨벤션이 지켜지고 있지 않은 것 같습니다.
inviteCode로 변경 부탁드립니다.

2022-11-30 01:39 UTC, taek0622 commented on Samsam/ViewController/SettingView/SettingRoomViewController.swift
> +    private let data = [["초대 코드 공유"],["방 정보 수정"]]
p1;
여기서 이중 배열이 되어야 하는 이유가 있을까요?
불필요한 이중 배열 같습니다.

2022-11-30 01:39 UTC, taek0622 commented on Samsam/ViewController/SettingView/SettingRoomViewController.swift
> +        invitecode = "asdf"
p1;
현재 아무 정보도 받아오지 못했을 때의 inviteCode 초기 값은 `------` 입니다.
해당 정보가 정상적으로 불러와지지 못했다고 명확하게 알기 위해 설정한 것이므로, 이에 맞게 변경이 필요할 것 같습니다.

2022-11-30 01:39 UTC, taek0622 commented on Samsam/ViewController/SettingView/SettingRoomViewController.swift
> +        let activityViewController = UIActivityViewController(activityItems: shareItems, applicationActivities: nil)
p1;
UIActivity의 activityItems에 넘겨주는 값이 단 하나라면 shareItems가 배열이 될 이유가 없을 것 같습니다.

2022-11-30 01:39 UTC, taek0622 commented on Samsam/ViewController/SettingView/SettingRoomViewController.swift
> +        return header.count
p1;
해당 부분을 위해 header가 필요한 것이라면 상당히 비효율적으로 보입니다.
header를 지우고 header.count 대신에 data.count로 변경이 필요할 것 같습니다.

2022-11-30 01:39 UTC, taek0622 commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +            composeVC.setToRecipients([Email])
p1;
Email을 한개만 받고 있는데, 배열이어야 할 이유가 있을까요?

2022-11-30 01:39 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +            if roomCreation == true {
p1;
roomCreation이 boolean 타입이므로 `roomCreation == true`가 아닌 `roomCreation`만으로도 참 거짓을 판별할 수 있습니다.

2022-11-30 01:39 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +        }
p3;
현재 글자 수가 10자 이상이 되면 뒤의 글자가 자동으로 잘려서 10자로 유지되는 것으로 알고 있습니다.
그렇다면 아래의 10/10은 불필요한 코드가 되지 않을까요?

2022-11-30 01:39 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +        updateRoomImformation(RoomDTO: roomDTO)
p2;
오타가 있는 것 같습니다.
updateRoomI`m`formation으로 되어있는데, I`n`formation이 되어야할 것 같습니다.

2022-11-30 01:58 UTC, JUNY0110 requested changes
삼항연산으로 수정할 수 있는 부분이 부분부분 보이는 것 같습니다..! if else보다 상항연산을 사용해보는 게 어떨까요?

2022-11-30 01:58 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +        }
p2.
```swift
if roomCreation! {
            (customerTextField.text!.count >= 1) ? (nextButton.backgroundColor = .blue) : (nextButton.backgroundColor = .gray)
            nextButton.isEnabled.toggle()
```
이렇게 바꾸면 더 간결한 코드가 작성될 것 같습니다!
아래 else문도 동일합니다.

2022-11-30 01:58 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }
p2.
삼항연산으로 수정해보는게 어떨까요?
`count <= 10 ? cutomerTextLimit.text = "\(count)/\(10)" : "\(10)/\(10)"`

2022-11-30 02:13 UTC, CreoHwan commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +
> p3. 아직 연결이 되어있지 않아 확인이 어렵습니다..!

73b24a6 연결했습니다! 감사합니다!

2022-11-30 02:14 UTC, CreoHwan commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +    private let header = ["","","",""]
> p1; 이렇게 다른 내용이 없는 배열로 사용할 것이라면 이 부분이 왜 필요한 것일까요?

1af895c  감사합니다!

2022-11-30 02:16 UTC, CreoHwan commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +        return header.count
> p1; 이 부분만을 위해 header가 존재하는 것이라면, header를 만들어서 header.count를 하는 것보다는 data.count를 하는 것이 더 좋을 것 같습니다.

1af895c 99a3673 감사합니다~

2022-11-30 02:20 UTC, CreoHwan commented on Network/API/RoomAPI.swift
> +    func loadRoomByRoomID(roomID: Int) async throws -> Room? {
> p2; 특정 방 정보는 원래 roomID로 불러오므로 loadRoomByRoomID보다는 loadRoom이 되는 것이 더 좋을 것 같습니다.

62b1731 넵 감사합니다~

2022-11-30 02:27 UTC, CreoHwan commented on Samsam/ViewController/SettingView/SettingRoomViewController.swift
> +    private var invitecode: String?
> p1; invitecode의 네이밍 컨벤션이 지켜지고 있지 않은 것 같습니다. inviteCode로 변경 부탁드립니다.

11e4971 감사합니다! 불필요하게 선언되어 있는 거 같아서 삭제하고 조치했습니다!

2022-11-30 02:27 UTC, creohwan commented on Samsam/ViewController/SettingView/SettingRoomViewController.swift
> +    private let data = [["초대 코드 공유"],["방 정보 수정"]]
> p1; 여기서 이중 배열이 되어야 하는 이유가 있을까요? 불필요한 이중 배열 같습니다.

1af895c 99a3673 감사합니다~

2022-11-30 02:27 UTC, CreoHwan commented on Samsam/ViewController/SettingView/SettingRoomViewController.swift
> +        invitecode = "asdf"
> p1; 현재 아무 정보도 받아오지 못했을 때의 inviteCode 초기 값은 `------` 입니다. 해당 정보가 정상적으로 불러와지지 못했다고 명확하게 알기 위해 설정한 것이므로, 이에 맞게 변경이 필요할 것 같습니다.

11e4971 감사합니다!

2022-11-30 02:28 UTC, CreoHwan commented on Samsam/ViewController/SettingView/SettingRoomViewController.swift
> +        let activityViewController = UIActivityViewController(activityItems: shareItems, applicationActivities: nil)
> p1; UIActivity의 activityItems에 넘겨주는 값이 단 하나라면 shareItems가 배열이 될 이유가 없을 것 같습니다.

현재는 초대코드 1줄만 보내고 있긴합니다! 추후 어떤 형식으로 초대공유 메시지를 보내야할 지 잘 몰라서 일단 이렇게 뒀습니다!

2022-11-30 02:29 UTC, CreoHwan commented on Samsam/ViewController/SettingView/SettingRoomViewController.swift
> +        return header.count
> p1; 해당 부분을 위해 header가 필요한 것이라면 상당히 비효율적으로 보입니다. header를 지우고 header.count 대신에 data.count로 변경이 필요할 것 같습니다.

1af895c 99a3673 감사합니다~

2022-11-30 02:38 UTC, CreoHwan commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +        }
> p3; 현재 글자 수가 10자 이상이 되면 뒤의 글자가 자동으로 잘려서 10자로 유지되는 것으로 알고 있습니다. 그렇다면 아래의 10/10은 불필요한 코드가 되지 않을까요?

3c02bf3 감사합니다~

2022-11-30 02:40 UTC, CreoHwan commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +            if roomCreation == true {
> p1; roomCreation이 boolean 타입이므로 `roomCreation == true`가 아닌 `roomCreation`만으로도 참 거짓을 판별할 수 있습니다.

7c1222d 감사합니다!

2022-11-30 02:42 UTC, CreoHwan commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +        updateRoomImformation(RoomDTO: roomDTO)
> p2; 오타가 있는 것 같습니다. updateRoomI`m`formation으로 되어있는데, I`n`formation이 되어야할 것 같습니다.

441e3f5 으악!

2022-11-30 02:43 UTC, CreoHwan commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +            composeVC.setToRecipients([Email])
> p1; Email을 한개만 받고 있는데, 배열이어야 할 이유가 있을까요?

공식문서 자체에서 파라미터를 [String]으로 받고 있습니다!
https://developer.apple.com/documentation/messageui/mfmailcomposeviewcontroller/1616872-settorecipients

2022-11-30 06:26 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCategoryViewController.swift
> +    var warrantyTime: Int?
> > Q. warrantyTime을 12에서 옵셔널로 준 이유가 있을까요?
> 
> RoomCreationViewController에서 바인딩으로 넘어올 것이라, RoomCategoryViewContorller에서 값을 설정하고 싶지 않아서, 옵셔널로 선언했습니다!

옵셔널 설정시 nil 값의 가능성이 있다고 판단되어 12로 남겨두었던 건데, 옵셔널에 대한 처리가 완벽하게 이루어지고 있는 것이 맞을까요?

2022-11-30 06:27 UTC, taek0622 commented on Network/API/RoomAPI.swift
> +    }
해당 부분 직접 이야기 나누고 우선 Message를 남기는 것으로 결정했습니다. 리뷰 리졸브합니다.

2022-11-30 06:28 UTC, taek0622 commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +    private let header = ["","","",""]
> > p1; 이렇게 다른 내용이 없는 배열로 사용할 것이라면 이 부분이 왜 필요한 것일까요?
> 
> [1af895c](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/1af895c5e807cf9053eb36b70035505d47103957) [99a3673](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/99a36737a2f686bc2194678b671b6f19e6debcb8) 감사합니다~

확인했습니다. 리뷰 리졸브합니다.

2022-11-30 06:29 UTC, taek0622 commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +        return header.count
> > p1; 이 부분만을 위해 header가 존재하는 것이라면, header를 만들어서 header.count를 하는 것보다는 data.count를 하는 것이 더 좋을 것 같습니다.
> 
> [1af895c](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/1af895c5e807cf9053eb36b70035505d47103957) [99a3673](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/99a36737a2f686bc2194678b671b6f19e6debcb8) 감사합니다~

확인했습니다. 리뷰 리졸브합니다.

2022-11-30 06:29 UTC, taek0622 commented on Network/API/RoomAPI.swift
> +    func loadRoomByRoomID(roomID: Int) async throws -> Room? {
> > p2; 특정 방 정보는 원래 roomID로 불러오므로 loadRoomByRoomID보다는 loadRoom이 되는 것이 더 좋을 것 같습니다.
> 
> [62b1731](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/62b1731d9eb969a66b09785285a27a2186335ff6) 넵 감사합니다~

확인했습니다. 리뷰 리졸브합니다.

2022-11-30 06:30 UTC, taek0622 commented on Samsam/ViewController/SettingView/SettingRoomViewController.swift
> +    private var invitecode: String?
> > p1; invitecode의 네이밍 컨벤션이 지켜지고 있지 않은 것 같습니다. inviteCode로 변경 부탁드립니다.
> 
> [11e4971](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/11e4971a7f1b3693d773d10f250447f7453106f1) 감사합니다! 불필요하게 선언되어 있는 거 같아서 삭제하고 조치했습니다!

확인했습니다. 리뷰 리졸브합니다.

2022-11-30 06:30 UTC, taek0622 commented on Samsam/ViewController/SettingView/SettingRoomViewController.swift
> +    private let data = [["초대 코드 공유"],["방 정보 수정"]]
> > p1; 여기서 이중 배열이 되어야 하는 이유가 있을까요? 불필요한 이중 배열 같습니다.
> 
> [1af895c](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/1af895c5e807cf9053eb36b70035505d47103957) [99a3673](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/99a36737a2f686bc2194678b671b6f19e6debcb8) 감사합니다~

확인했습니다. 리뷰 리졸브합니다.

2022-11-30 06:31 UTC, taek0622 commented on Samsam/ViewController/SettingView/SettingRoomViewController.swift
> +        invitecode = "asdf"
> > p1; 현재 아무 정보도 받아오지 못했을 때의 inviteCode 초기 값은 `------` 입니다. 해당 정보가 정상적으로 불러와지지 못했다고 명확하게 알기 위해 설정한 것이므로, 이에 맞게 변경이 필요할 것 같습니다.
> 
> [11e4971](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/11e4971a7f1b3693d773d10f250447f7453106f1) 감사합니다!

확인했습니다. 리뷰 리졸브합니다.

2022-11-30 06:31 UTC, taek0622 commented on Samsam/ViewController/SettingView/SettingRoomViewController.swift
> +        return header.count
> > p1; 해당 부분을 위해 header가 필요한 것이라면 상당히 비효율적으로 보입니다. header를 지우고 header.count 대신에 data.count로 변경이 필요할 것 같습니다.
> 
> [1af895c](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/1af895c5e807cf9053eb36b70035505d47103957) [99a3673](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/99a36737a2f686bc2194678b671b6f19e6debcb8) 감사합니다~

확인했습니다. 리뷰 리졸브합니다.

2022-11-30 06:32 UTC, taek0622 commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +            composeVC.setToRecipients([Email])
> https://developer.apple.com/documentation/messageui/mfmailcomposeviewcontroller/1616872-settorecipients

확인했습니다. 해당 부분은 몰랐네요. 리뷰 리졸브합니다.

2022-11-30 06:33 UTC, JUNY0110 commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +
> > p2. header가 헤더 갯수 외에는 사용되지 않고 있는 것 같습니다. `data.count`로 변경하면 header를 선언하지 않아도 될 것 같아요
> 
> [1af895c](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/1af895c5e807cf9053eb36b70035505d47103957) [99a3673](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/99a36737a2f686bc2194678b671b6f19e6debcb8) 감사합니다~

수정 확인했습니다~

2022-11-30 06:33 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +            if roomCreation == true {
> > p1; roomCreation이 boolean 타입이므로 `roomCreation == true`가 아닌 `roomCreation`만으로도 참 거짓을 판별할 수 있습니다.
> 
> [7c1222d](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/7c1222df724825284bfcce7f33ff63ef9013cf7b) 감사합니다!

확인했습니다. 리뷰 리졸브합니다.

2022-11-30 06:33 UTC, JUNY0110 commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +        case [2,2]:
> > p3. options를 별도 사용할 것이 아니라면, 삭제하는 게 더 깔끔할 것 같아요~
> 
> [9781445](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/9781445a831e741555432a030b5d671da2298422) 감사합니다!

수정 확인했습니다~

2022-11-30 06:33 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +        }
> > p3; 현재 글자 수가 10자 이상이 되면 뒤의 글자가 자동으로 잘려서 10자로 유지되는 것으로 알고 있습니다. 그렇다면 아래의 10/10은 불필요한 코드가 되지 않을까요?
> 
> [3c02bf3](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/3c02bf372147dbf438e460cfc6f45bb3f809de1c) 감사합니다~ 깔끔하게 수정했습니다!

확인했습니다. 정말 깔~끔하네요. 리뷰 리졸브합니다.

2022-11-30 06:34 UTC, JUNY0110 commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +}
> [336a6be](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/336a6be4e88b3332578df0f8271958d2fef1dc9d) 감사합니다!

수정 확인했습니다~

2022-11-30 06:34 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +        updateRoomImformation(RoomDTO: roomDTO)
> > p2; 오타가 있는 것 같습니다. updateRoomI`m`formation으로 되어있는데, I`n`formation이 되어야할 것 같습니다.
> 
> [441e3f5](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/441e3f5adcc324a58f4b63cac32a76a6208504b1) 으악!

와우~ 확인했습니다. 리뷰 리졸브합니다.

2022-11-30 06:37 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +        }
> p2.
> 
> ```swift
> if roomCreation! {
>             (customerTextField.text!.count >= 1) ? (nextButton.backgroundColor = .blue) : (nextButton.backgroundColor = .gray)
>             nextButton.isEnabled.toggle()
> ```
> 
> 이렇게 바꾸면 더 간결한 코드가 작성될 것 같습니다! 아래 else문도 동일합니다.

해당 부분은 아래와 같이 더 깔끔하게 수정 가능합니다.
```swift
if roomCreation! {
    nextButton.backgroundColor = (customerTextField.text!.count >= 1) ? .blue : .gray
    nextButton.isEnabled.toggle()
}
```

2022-11-30 06:44 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }
수정확인했습니다~

2022-12-01 01:14 UTC, CreoHwan commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +        }
e7ca90d 좋은 의견 감사합니다!

2022-12-01 02:30 UTC, creohwan commented on Samsam/ViewController/RoomCreationView/RoomCategoryViewController.swift
> +    var warrantyTime: Int?
> > > Q. warrantyTime을 12에서 옵셔널로 준 이유가 있을까요?
> > 
> > 
> > RoomCreationViewController에서 바인딩으로 넘어올 것이라, RoomCategoryViewContorller에서 값을 설정하고 싶지 않아서, 옵셔널로 선언했습니다!
> 
> 옵셔널 설정시 nil 값의 가능성이 있다고 판단되어 12로 남겨두었던 건데, 옵셔널에 대한 처리가 완벽하게 이루어지고 있는 것이 맞을까요?

5e6b437 아까 모여서 이야기한 이후 반영했습니다! 감사합니다!

2022-12-01 02:43 UTC, CreoHwan commented
3db04aa 날짜 형식까지 바꾸었습니다~! 나중에... 꼭 리팩토링해야 할 것 같습니다..

2022-12-01 04:52 UTC, JUNY0110 approved these changes
고생하셨습니다~~

2022-12-01 08:14 UTC, closed without merging