[Feature] 세부시공상태뷰(Detailview) 이미지 및 텍스트 데이터 바인딩 및 공유 기능
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #143
Opened 2022-11-30 19:11 UTC by JUNY0110

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 시공상황뷰(WorkingHistory)에서 받은 서버데이터를 세부시공상태뷰(DetailView)로 바인딩 하기 위함
- 바인딩 받은 데이터를 공유하기 위함

## Key Changes 🔥 (주요 구현/변경 사항)
- 시공상황뷰(WorkingHistory)에서 받은 서버데이터를 세부시공상태뷰(DetailView)로 바인딩
- 바인딩 받은 이미지, 텍스트 데이터 공유하기 기능 수정 ( 기존 코어데이터 -> 서버(바인딩) 데이터 )
  - async 데이터 내에서 sync 처리.
  - ` let imageData = try? Data(contentsOf: URL(string: $0.photoPath)!)`는 main thread가 아닌 곳에서 비동기 처리가 되어야 함
  - image가 모두 append된 이후에 sharing(공유) 기능이 실행되어야 함
    - 즉, 이미지와 공유버튼은 동기처리가 되어야함.
- main.sync는 잘 사용되지 않는 것 같지만, 이번 경우처럼 비동기처리로는 해결되지 않는 특정 순서가 지켜져야 할 때 사용되는 것 같습니다.

## ToDo 📆 (남은 작업)
- [ ] 세부이미지뷰(ImageDetailView)로 이미지 바인딩

## ScreenShot 📷 (참고 사진)
![Simulator Screen Recording - iPhone 13 Pro - 2022-12-01 at 04 05 01](https://user-images.githubusercontent.com/98405970/204886277-11b06a3a-014e-4571-955f-d965ca2ffe1a.gif)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 비동기 내에서 동기처리하는 작업에 난항을 겪어 생각보다 시간이 많이 걸렸습니다. ㅠㅠ

## Reference 🔗
- [main.sync를 사용하지 않는 이유](https://zeddios.tistory.com/519)
  - 이거 하나만 읽어도 될 것 같습니다.

- [iOS 비동기처리방식](https://medium.com/@goehd2538/ios의-비동기-처리방식-65aa81aad0f9)
- [DispatchQueue사용법](https://zeddios.tistory.com/516)
  - 아래 2개는 안 읽어봤지만, 나쁘지 않아 보여서 올립니다. 좀 길기 때문에 시간이 나시면 읽어보세요 

## Close Issues 🔒 (닫을 Issue)
Close #141.

2022-11-30 19:31 UTC, taek0622 approved these changes
고생하셨습니다.
코드로는 몇 줄 안되지만, 실제로 정말 많은 시도를 하신걸 옆에서 보아서 정말 많은 노력이 느껴지네요.
항상 막막해도 열심히 해주셔서 감사해요 에디~

2022-11-30 19:31 UTC, taek0622 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +            }
p5;
위의 appendImage 쪽에 상당히 흡사한 코드가 보이는데, 두 코드를 합칠 수 있는 방법은 없을까요?

2022-11-30 19:35 UTC, taek0622 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +            }
> p5; 위의 appendImage 쪽에 상당히 흡사한 코드가 보이는데, 두 코드를 합칠 수 있는 방법은 없을까요?

해당 부분을 매우 쉽게 합칠 수 있는 방법을 발견해서 아침에 함께 이야기해보면 좋을 것 같습니다.

2022-11-30 19:37 UTC, taek0622 requested changes
코드를 다시 살펴보다가 추가로 수정할 것이 보여서 리뷰 변경합니다.

2022-11-30 19:37 UTC, taek0622 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +    private func shareitems() {
p2;
네이밍 컨벤션이 지켜지고 있지 않습니다. 카멜표기법 지켜주세요~

2022-12-01 02:59 UTC, JUNY0110 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +            }
> p5;
> 위의 appendImage 쪽에 상당히 흡사한 코드가 보이는데, 두 코드를 합칠 수 있는 방법은 없을까요?

9180a7b 굿

2022-12-01 03:00 UTC, JUNY0110 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +    private func shareitems() {
> p2;
> 네이밍 컨벤션이 지켜지고 있지 않습니다. 카멜표기법 지켜주세요~

수정하는 과정에서 삭제되었습니다!

2022-12-01 03:11 UTC, taek0622 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +            }
> > p5;
> > 위의 appendImage 쪽에 상당히 흡사한 코드가 보이는데, 두 코드를 합칠 수 있는 방법은 없을까요?
> 
> [9180a7b](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/9180a7b30bbf45018f30d686f0d16e849e30c9e6) 기능과 뷰를 나눠서 작업하는게 나은지 고민이었는데, 덕분에 해결했습니다!

확인했습니다. 복잡했던 로직이 비교적 가벼워진 것 같네요. 굳!

2022-12-01 03:11 UTC, taek0622 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +    private func shareitems() {
> > p2;
> > 네이밍 컨벤션이 지켜지고 있지 않습니다. 카멜표기법 지켜주세요~
> 
> 수정하는 과정에서 삭제되었습니다!

확인했습니다. 리뷰 리졸브합니다.

2022-12-01 03:14 UTC, taek0622 approved these changes
고생하셨습니다.
항상 에디 부분에서 뭔가 어려운 작업들이 많이 일어나는 것 같은데, 너무너무 고생이 많으세요.
앞으로도 어려운 작업들 잘 부탁드립니다~

2022-12-01 03:19 UTC, merged