Feat/128 new setting
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #144
Opened 2022-12-01 08:15 UTC by CreoHwan

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 설정 뷰 만들기
- 방 정보 수정 기능 구현

## Key Changes 🔥 (주요 구현/변경 사항)
- RoomAPI.swift: 방 정보 수정하는 API 통신, roomID로 방 정보를 가져오는 API 통신 추가
- RoomEndPoint.swift: 방 정보 수정하는 API 통신, roomID로 방 정보를 가져오는 API 통신 추가
- SegmentedControlViewController: 룸리스트에서, 세그먼트로 들어올 때, viewwillapear에서, API통신을 통해 방 정보를 불러오는 부분을 추가 / 방 설정 완료 후 돌아왔을 때, navigaionTitle 변경을 위해, setNavigationBar()를 loadRoomByRoomID() 안에 넣어놈. 비동기 문제를 해결하기 위함.
- RoomCategoryViewController: startDate, endDate, WarrantyTime을 RoomCreationViewController에서 바인딩 받음. 이후 방 생성에 쓰임.
-
- RoomCreationViewContoller 관련 변경 사항
- roomCreation: true일 경우 방 생성, false일 경우 방 수정. didSet으로 각각의 맞는 UI 변경
- warrantyTime: 방 수정일 경우, 기존 값이랑 달라졌을 때, modificationButton(수정버튼)이 달라져야 함으로 didSet이용.
- startDate, endDate: 방 수정일 경우, 기존 값이랑 달라졌을 때, modificationButton(수정버튼)이 달라져야 함으로 didSet이용. / 시간은 달라도 되기에, 날짜만 비교하면 되기에, 각각 deropLast를 적절히 해줘서 비교함.
- customerTextLimit: 고객 이름/주소 입력을 할 때, 10 자리를 넘으면 안되어서, 이를 막기 위해, 오른쪽에 "3/10"를 표시해줌. 이를 위한 UI.
- modificationButton: 방 수정 시, 수정 완료 버튼
- setCounter(count: Int): 고객 이름/주소 입력 시, 변하는 자리수에 맞춰서, customerTextLimit를 변경해주기 위해 필요한 함수
- checkMaxLength(textField: UITextField): 고객 이름/주소 입력 시, 10 초과가 되지 않도록, 10 초과가 되면 입력이 되지 않도록 만드는 함수
- buttonAttributeChanged: 고객 이름/주소 입력 시, setCounter와 checkMaxLength를 돌려주고, 방 생성일 때는 1자리 이상이 입력되었을 때 파란 버튼이 되게, 방 수정일 때는 기존의 값과 다를 때 파란 버튼이 되도록 설정해주는 함수.
- tapModificationButton: 방 정보 수정 시, 수정 완료를 누르면, API통신을 하도록 하는 버튼
- updateRoomImformation: 방 정보 수정 시, 방 정보를 PUT하는 실제 API통신 부분. 
- loadDateImformation: 방 생성 시, 시공일 준공일을 현재로 설정하기 위해 필요한 부분.
- loadRoomImformation: 방 수정 시, 기존 방 정보를 가져오는 부분.
- extension String: string -> Date 포멧으로 바꾸는 함수 만듬.
- extension Date: Date -> string 포멧으로 바꾸는 함수 만듬.
-
- RoomCreationViewWarrantyCell: 불필요하게 사용되던 warrantyCount 삭제
- RoomListViewController: 방 정부 수정 시, 리스트가 섞이는 문제를 해결함. sortby로 해결.
- DeveloperViewController: 개발자 정보 뷰. 추후 수정 예정.
-
- SettingRoomViewController: 방에 들어가서 설정누르면 나오는 뷰
- SettingWorkerViewController: 처음 룸 리스트에서 설정 누르면 나오는 뷰
- VersionViewController: 버전 정보를 보여주는 뷰. 추후 수정 예정

## ToDo 📆 (남은 작업)
- [ ] 이름, 전화번호 수정 기능 추후 구현해야 함
- [ ] 개발자 정보 뷰 만들어야 함

## ScreenShot 📷 (참고 사진)
- 메인 설정
![Simulator Screen Recording - iPhone 14 Pro - 2022-11-23 at 15 12 19](https://user-images.githubusercontent.com/92836045/203482633-58cf189f-e8ee-4908-95a7-cf99bfa3d335.gif)

- 방에서 설정
![Simulator Screen Recording - iPhone 14 Pro - 2022-11-23 at 15 10 40](https://user-images.githubusercontent.com/92836045/203482525-b96982c1-1ca1-4277-ab5a-fa696dd4d30e.gif)

- 방 정보 수정
![Simulator Screen Recording - iPhone 14 Pro - 2022-11-29 at 15 54 19](https://user-images.githubusercontent.com/92836045/204459798-e18e991d-470d-46ff-a89b-38297864eda1.gif)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 이게 너무 길어져서 죄송합니다... 내일 설명 한번 드리겠습니다!
- 
## Reference 🔗
- UITabelView 관련: (오른쪽 글씨 쓸 때 참조한 링크)
https://velog.io/@jangdev/UITableView

## Close Issues 🔒 (닫을 Issue)
Close #128

2022-12-01 17:44 UTC, JUNY0110 approved these changes
컨플릭트가 크게 나서 새로 작업하려니 까다로웠을텐데, 고생하셨습니다~

2022-12-01 17:44 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }
p5.
비슷한 코드가 4번정도 사용되는데, String Extension으로 빼는게 가능할 수도 있겠다는 생각이 드네요..!

2022-12-02 00:39 UTC, taek0622 requested changes
고생하셨습니다.
수정이 필요해 보이는 부분에 리뷰 남겼습니다. 확인 부탁드려요~

2022-12-02 00:39 UTC, taek0622 commented on Network/EndPoint/RoomEndPoint.swift
> +            return "\(APIEnvironment.roomsURL)/\(roomID)"
p2;
이 둘은 같은 주소값을 반환한다면 하나로 합칠 수 있을 것 같습니다.

2022-12-02 00:39 UTC, taek0622 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +        loadRoomByRoomID(roomID: room!.roomID)
p4;
SegmentedControll에서 특정 방 정보를 불러올 이유가 있을까요?
수정에 필요한 것이라면 수정하는 뷰에서만 불러와도 될 것 같습니다.

2022-12-02 00:39 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    var roomCreation: Bool? {
p4;
roomCreation에 기본값을 주는 것은 어떨까요?

2022-12-02 00:39 UTC, taek0622 commented on Samsam/ViewController/SettingView/SettingRoomViewController.swift
> +        if let invitecode = room?.inviteCode {
p2;
invitecode의 네이밍 컨벤션이 지켜지고 있지 않는 것 같습니다. 네이밍 컨벤션을 지켜주세요~

2022-12-02 00:39 UTC, taek0622 commented on Samsam/ViewController/SettingView/SettingRoomViewController.swift
> +        present(navigationController, animated:  true, completion: nil)
p1;
present의 completion 속성이 nil이라면 present의 completion 속성의 기본값이 nil이기 때문에 삭제되어도 될 것 같습니다.

2022-12-02 00:39 UTC, taek0622 commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +            self.present(composeVC, animated: true, completion: nil)
p1;
마찬가지로 present의 completion 속성의 기본값이 nil이기 때문에 nil값이라면 삭제되어도 되는 속성 같습니다.

2022-12-02 00:43 UTC, CreoHwan commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +        loadRoomByRoomID(roomID: room!.roomID)
> p4; SegmentedControll에서 특정 방 정보를 불러올 이유가 있을까요? 수정에 필요한 것이라면 수정하는 뷰에서만 불러와도 될 것 같습니다.

방 수정 이후에, 네비게이션 타이틀이 바꾸어주기 위해서, 불러옵니다!

2022-12-02 00:46 UTC, CreoHwan commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +            self.present(composeVC, animated: true, completion: nil)
> p1; 마찬가지로 present의 completion 속성의 기본값이 nil이기 때문에 nil값이라면 삭제되어도 되는 속성 같습니다.

1b323be 옮기는 과정에서 이유는 잘 모르겠지만 다시 생긴 것 같습니다... 꼼꼼한 리뷰 감사합니다~!

2022-12-02 00:46 UTC, CreoHwan commented on Samsam/ViewController/SettingView/SettingRoomViewController.swift
> +        present(navigationController, animated:  true, completion: nil)
> p1; present의 completion 속성이 nil이라면 present의 completion 속성의 기본값이 nil이기 때문에 삭제되어도 될 것 같습니다.

1b323be 옮기는 과정에서 이유는 잘 모르겠지만 다시 생긴 것 같습니다... 꼼꼼한 리뷰 감사합니다~!

2022-12-02 00:48 UTC, CreoHwan commented on Samsam/ViewController/SettingView/SettingRoomViewController.swift
> +        if let invitecode = room?.inviteCode {
> p2; invitecode의 네이밍 컨벤션이 지켜지고 있지 않는 것 같습니다. 네이밍 컨벤션을 지켜주세요~

dadc544 으갸갹 내 정신!

2022-12-02 00:58 UTC, CreoHwan commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    var roomCreation: Bool? {
> p4; roomCreation에 기본값을 주는 것은 어떨까요?

9149548 감사합니다!

2022-12-02 01:00 UTC, CreoHwan commented on Network/EndPoint/RoomEndPoint.swift
> +            return "\(APIEnvironment.roomsURL)/\(roomID)"
> p2; 이 둘은 같은 주소값을 반환한다면 하나로 합칠 수 있을 것 같습니다.

6e7b2f8 감사합니다~!~

2022-12-02 02:15 UTC, taek0622 commented on Network/EndPoint/RoomEndPoint.swift
> +            return "\(APIEnvironment.roomsURL)/\(roomID)"
> > p2; 이 둘은 같은 주소값을 반환한다면 하나로 합칠 수 있을 것 같습니다.
> 
> [6e7b2f8](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/6e7b2f88152781f4686222dac7185b3fd4d7115c) 감사합니다~!~

확인했습니다. 리뷰 리졸브합니다.

2022-12-02 02:16 UTC, taek0622 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +        loadRoomByRoomID(roomID: room!.roomID)
> > p4; SegmentedControll에서 특정 방 정보를 불러올 이유가 있을까요? 수정에 필요한 것이라면 수정하는 뷰에서만 불러와도 될 것 같습니다.
> 
> 방 수정 이후에, 네비게이션 타이틀이 바꾸어주기 위해서, 불러옵니다!

확인했습니다.

2022-12-02 02:16 UTC, ikanic commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    var roomCreation: Bool? {
> > p4; roomCreation에 기본값을 주는 것은 어떨까요?
> 
> [9149548](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/914954843efad30c07d490d7c7f0432c86dbd7ff) 감사합니다!

확인했습니다. 코드 보기가 한결 편해졌네요. 리뷰 리졸브합니다.

2022-12-02 02:16 UTC, ikanic commented on Samsam/ViewController/SettingView/SettingRoomViewController.swift
> +        if let invitecode = room?.inviteCode {
> > p2; invitecode의 네이밍 컨벤션이 지켜지고 있지 않는 것 같습니다. 네이밍 컨벤션을 지켜주세요~
> 
> [dadc544](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/dadc544b9e9f42a910c79834bc879492bc95f76a) 으갸갹 내 정신!

ㅎㅎㅎ 그럴수 있죠~ 확인했습니다. 리뷰 리졸브합니다.

2022-12-02 02:17 UTC, taek0622 commented on Samsam/ViewController/SettingView/SettingRoomViewController.swift
> +        present(navigationController, animated:  true, completion: nil)
> > p1; present의 completion 속성이 nil이라면 present의 completion 속성의 기본값이 nil이기 때문에 삭제되어도 될 것 같습니다.
> 
> [1b323be](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/1b323bee2c4fda93903f92950181ae8b2e1f6eeb) 옮기는 과정에서 이유는 잘 모르겠지만 다시 생긴 것 같습니다... 꼼꼼한 리뷰 감사합니다~!

확인했습니다. 리뷰 리졸브합니다.

2022-12-02 02:17 UTC, taek0622 commented on Samsam/ViewController/SettingView/SettingWorkerViewController.swift
> +            self.present(composeVC, animated: true, completion: nil)
> > p1; 마찬가지로 present의 completion 속성의 기본값이 nil이기 때문에 nil값이라면 삭제되어도 되는 속성 같습니다.
> 
> [1b323be](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/1b323bee2c4fda93903f92950181ae8b2e1f6eeb) 옮기는 과정에서 이유는 잘 모르겠지만 다시 생긴 것 같습니다... 꼼꼼한 리뷰 감사합니다~!

확인했습니다. 리뷰 리졸브합니다.

2022-12-02 02:22 UTC, taek0622 approved these changes
고생하셨습니다.
이전 브랜치에 컨플릭트도 많고 해서 번거로우셨을 텐데도 새 브랜치로 옮기느라 진짜 고생하셨습니다.

2022-12-02 03:15 UTC, merged