[Feature] 세부이미지뷰(imageDetailView) 이미지 바인딩 및 스타일 변경
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #145
Opened 2022-12-01 17:27 UTC by JUNY0110

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 추후 이미지 클릭 시 확대모션 추가를 위한 Modal로 변경
- 이미지를 보다 뚜렷하게 보기 위한 배경색 추가
- 이미지 바인딩

## Key Changes 🔥 (주요 구현/변경 사항)
- Navigatioin -> Modal형식으로 변경 ( 추후 이미지 클릭 시 확대모션 추가하기 위함 )
- Navigation Title 삭제
- 화면 클릭 시 배경 Black & White 변경
- DetailView에서 선택한 이미지 바인딩
- 화면 줌 기능 시 뷰 배경 Black 기능 추가

## ToDo 📆 (남은 작업)
- [ ] 이미지 클릭 시 확대모션
- [ ] 클릭한 이미지에서 좌우 스크롤 시 다른 이미지 확인

## ScreenShot 📷 (참고 사진)
![Simulator Screen Recording - iPhone 13 Pro - 2022-12-02 at 02 24 07](https://user-images.githubusercontent.com/98405970/205119389-8c13d458-a56f-4a12-88e1-e9035feb4bef.gif)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- didSet을 활용한 '용도'에 맞는 코드와 짧은 코드를 하나의 함수에 넣어 '가독성'을 높인 코드 중 어느 게 더 좋은 코드일까요??

## Reference 🔗
- [사진뷰어만들기](https://velog.io/@kirri1124/사진-뷰어-앱을-만들어봤다)
- [이미지 클릭 시 모달 확대 효과](https://shoveller.tistory.com/entry/UINavigationController-push-할-때-이미지-확대축소-전환효과주기-interactive)
## Close Issues 🔒 (닫을 Issue)
Close #142 .

2022-12-02 02:00 UTC, taek0622 requested changes
고생하셨습니다.
이번에도 사진 확대 기능 때문에 오랜 시간 코드 이해에 시간을 쏟으신걸로 알고 있는데, 정말 고생하셨어요.
몇몇 수정이 필요해보이는 부분에 리뷰 남겼습니다. 확인 부탁드려요.

2022-12-02 02:00 UTC, ikanic commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +        present(navigationController, animated: false)
p1;
해당 부분은 네비게이션이 아니라 모달인 것 같은데 customGestureRecognizer의 이름이 Navigation으로 되어있네요.
수정 부탁드립니다.

2022-12-02 02:00 UTC, ikanic commented on Samsam/ViewController/DetailView/ImageDetailViewController.swift
> +            right: scrollView.contentLayoutGuide.rightAnchor
scrollView의 ContentLayout을 잘 활용하신 것 같네요.
ScrollView에 익숙하지 않으신 분들은 contentLayoutGuide를 잡는 방법을 잘 모르시는 것 같던데, 좋은 공부 하신 것 같아요.
굳 입니다~

2022-12-02 02:00 UTC, ikanic commented on Samsam/ViewController/DetailView/ImageDetailViewController.swift
> +            image: UIImage(systemName: "xmark"),
p5;
해당 부분에 xmark가 들어가는 것이 약간 어색하다는 느낌이 듭니다.
모달이기 때문에 x를 주신 것으로 보입니다만, 일반적으로 사진을 보여주는 어플들은 x 사용이 잘 안되고 있는 것 같아요.
left chevron이나 "닫기" 갇은 글자가 들어가면 어떨까 싶습니다.

2022-12-02 02:00 UTC, ikanic commented on Samsam/ViewController/DetailView/ImageDetailViewController.swift
> +        scrollView.alwaysBounceVertical = true
scrollView의 Bounce 부분의 기본 값이 UIKit에서는 false이군요.
SwiftUI에서는 true 였는데, 신기하네요.
좋은 인사이트 얻어갑니다. 굳~

2022-12-02 02:00 UTC, ikanic commented on Samsam/ViewController/DetailView/ImageDetailViewController.swift
> +            let fixedHeight = image.size.height
p5;
아래에는 ratio는 ratio끼리 new는 new끼리 모여있는데, 이곳만 changed와 fixed가 함께 있어서 약간 헷갈리는 것 같습니다.
changed와 fixed를 분리하는 것은 어떨까요?

2022-12-02 02:00 UTC, ikanic commented on Samsam/ViewController/DetailView/ImageDetailViewController.swift
> +            let newHeight = image.size.height * ratio
p1;
image.size.width와 image.size.height는 이미 fixedWidth와 fixedHeight로 이미 정의된 것 같습니다.
정의되어 있는 변수로 바꿔주세요.

2022-12-03 15:40 UTC, JUNY0110 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +        present(navigationController, animated: false)
> p1;
> 해당 부분은 네비게이션이 아니라 모달인 것 같은데 customGestureRecognizer의 이름이 Navigation으로 되어있네요.
> 수정 부탁드립니다.

코드가 한 곳에 모여있기 때문에 customGestureRecognizer를 같이 표시해줬으면 좋았을 것 같네요. 어느 부분에 대한 의견인지 모호함이 있었습니다. 제가 이해한 게 맞는지 모르네요. 그래서 코드를 가져왔습니다.

```swift
    @objc func changedView(_ sender: NavigationTapRecognizer) {
        let imageDetailViewController = ImageDetailViewController()
        imageDetailViewController.detailImage.image = sender.image
        
        let navigationController = UINavigationController(rootViewController: imageDetailViewController)
        navigationController.modalPresentationStyle = .fullScreen
        
        present(navigationController, animated: false)
    }
}

class NavigationTapRecognizer: UITapGestureRecognizer {
    var image: UIImage?
}

```

changedView함수를 통해 띄우는 것은 Modal이기에 ModalTapRecognizer로 수정하는 것에 동의합니다.
하지만 navigationController는 모달로서 동작하지만, 뷰의 형태는 Navigation입니다.

UIViewController를 present 시킨 것과는 다르게 UINavigationController를 활용한 Modal구현을 한 이유는 UINavigationController에 의해 관리되는 View Controller를 추가해 `navigationItem.leftBarButtonItem`과 같이 NavigationViewController에서도 활용가능한 코드를 사용하기 위함입니다.

NavigationController가 아닌 Modal로 이름짓는다면, Modal 코드에 rootViewController를 사용할 수 있다는 착각을 불러일으킬 수 있다 생각해 수정하지 않았습니다.

2022-12-03 15:51 UTC, JUNY0110 commented on Samsam/ViewController/DetailView/ImageDetailViewController.swift
> +            image: UIImage(systemName: "xmark"),
> p5;
> 해당 부분에 xmark가 들어가는 것이 약간 어색하다는 느낌이 듭니다.
> 모달이기 때문에 x를 주신 것으로 보입니다만, 일반적으로 사진을 보여주는 어플들은 x 사용이 잘 안되고 있는 것 같아요.
> left chevron이나 "닫기" 갇은 글자가 들어가면 어떨까 싶습니다.

40e3b21 수정했습니다.

수정했으나, 익숙함은 UX에 강력한 근거가 되지만, 좋은 UX라고는 할 수 없다고 생각합니다.
[우리의 기준은 우리의 사고방식으로](https://yozm.wishket.com/magazine/detail/1283/) 라는 글을 참고하여 추가로 얘기하자면, 남들이 저렇게 하기 때문에 이렇게 해야한다는 식의 UX보다 명확성을 근거로 사용자에게 의미를 전달하기 쉬워야 한다고 생각합니다. 그런 의미에서 Chevron.Left는 오히려 사용자에게 Swipe동작으로 뒤로가기를 할 수 있다는 착각과 모호함을 증대시키는 UI라는 생각이 듭니다.

'익숙함이 정말 익숙함이 맞는가?, 지금 느끼는 익숙함은 해당 기능이 아닌 해당 앱에 한정된 익숙함이 아닐까?'라는 생각이 듭니다. 다소 개인적인 의견일 수 있지만, 일반 사진앱에서 사용하는 Chevron.left도 모달화면임에도 네비게이션 동작을 할 수 있게 착각하게 만들 수 있다고 생각합니다. 하지만 닫기 또는 close 등의 문구를 사용하는 것은 오히려 앱의 무드를 해칠 수 있다고 생각해 미뉴의 의견대로 Chevron으로 수정하였습니다. 추후 디자인 수정 시 다시 이야기해보면 좋을 것 같습니다.

2022-12-03 15:52 UTC, JUNY0110 commented on Samsam/ViewController/DetailView/ImageDetailViewController.swift
> +            let newHeight = image.size.height * ratio
> p1;
> image.size.width와 image.size.height는 이미 fixedWidth와 fixedHeight로 이미 정의된 것 같습니다.
> 정의되어 있는 변수로 바꿔주세요.

302602a 수정했습니다.
아래의 코드순서를 보게되면 사용순서대로 변수명을 작성했었으나, 오히려 가독성을 해칠 수 있겠네요..!

2022-12-03 15:53 UTC, JUNY0110 commented on Samsam/ViewController/DetailView/ImageDetailViewController.swift
> +            let fixedHeight = image.size.height
> p5;
> 아래에는 ratio는 ratio끼리 new는 new끼리 모여있는데, 이곳만 changed와 fixed가 함께 있어서 약간 헷갈리는 것 같습니다.
> changed와 fixed를 분리하는 것은 어떨까요?

302602a 수정했습니다.
아래의 코드순서를 보게되면 사용순서대로 변수명을 작성했었으나, 오히려 가독성을 해칠 수 있겠네요..!

2022-12-03 16:00 UTC, JUNY0110 commented
> ## Motivation 🥳 (코드를 추가/변경하게 된 이유)
> * 추후 이미지 클릭 시 확대모션 추가를 위한 Modal로 변경
> * 이미지를 보다 뚜렷하게 보기 위한 배경색 추가
> * 이미지 바인딩
> * 아카데미 사진(TestImage) 삭제
> 
> ## Key Changes 🔥 (주요 구현/변경 사항)
> * Navigatioin -> Modal형식으로 변경 ( 추후 이미지 클릭 시 확대모션 추가하기 위함 )
> * Navigation Title 삭제
> * 화면 클릭 시 배경 Black & White 변경
> * DetailView에서 선택한 이미지 바인딩
> * 화면 줌 기능 시 뷰 배경 Black 기능 추가
> 
> ## ToDo 📆 (남은 작업)
> * [ ]  이미지 클릭 시 모달을 이용한 확대 효과
> * [ ]  클릭한 이미지에서 좌우 스크롤 시 다른 이미지 확인
> 
> ## ScreenShot 📷 (참고 사진)
> ![Simulator Screen Recording - iPhone 13 Pro - 2022-12-02 at 02 24 07](https://user-images.githubusercontent.com/98405970/205119389-8c13d458-a56f-4a12-88e1-e9035feb4bef.gif) [ ![Simulator Screen Recording - iPhone 13 Pro - 2022-12-02 at 02 24 07](https://user-images.githubusercontent.com/98405970/205119389-8c13d458-a56f-4a12-88e1-e9035feb4bef.gif) ](https://user-images.githubusercontent.com/98405970/205119389-8c13d458-a56f-4a12-88e1-e9035feb4bef.gif) [ ](https://user-images.githubusercontent.com/98405970/205119389-8c13d458-a56f-4a12-88e1-e9035feb4bef.gif)
> 
> ## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
> * didSet을 활용한 '용도'에 맞는 코드와 짧은 코드를 하나의 함수에 넣어 '가독성'을 높인 코드 중 어느 게 더 좋은 코드일까요??
> 
> ## Reference 🔗
> * [사진뷰어만들기](https://velog.io/@kirri1124/%EC%82%AC%EC%A7%84-%EB%B7%B0%EC%96%B4-%EC%95%B1%EC%9D%84-%EB%A7%8C%EB%93%A4%EC%96%B4%EB%B4%A4%EB%8B%A4)
> * [이미지 클릭 시 모달 확대 효과](https://shoveller.tistory.com/entry/UINavigationController-push-%ED%95%A0-%EB%95%8C-%EC%9D%B4%EB%AF%B8%EC%A7%80-%ED%99%95%EB%8C%80%EC%B6%95%EC%86%8C-%EC%A0%84%ED%99%98%ED%9A%A8%EA%B3%BC%EC%A3%BC%EA%B8%B0-interactive)
> 
> ## Close Issues 🔒 (닫을 Issue)
> Close #142 .

2022-12-03 16:50 UTC, JUNY0110 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +        present(navigationController, animated: false)
> > p1;
> > 해당 부분은 네비게이션이 아니라 모달인 것 같은데 customGestureRecognizer의 이름이 Navigation으로 되어있네요.
> > 수정 부탁드립니다.
> 
새 방식을 생각하자면, 하단에 닫기버튼이 있는 게 낫지 않을까? 라는 생각이 듭니다.
FullScreen모달은 닫기 버튼이 상단에 있을 때, 한 손으로 닫기 어렵기 때문입니다.

2022-12-03 18:43 UTC, taek0622 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +        present(navigationController, animated: false)
> > p1;
> > 해당 부분은 네비게이션이 아니라 모달인 것 같은데 customGestureRecognizer의 이름이 Navigation으로 되어있네요.
> > 수정 부탁드립니다.
> 
> 코드가 한 곳에 모여있기 때문에 customGestureRecognizer를 같이 표시해줬으면 좋았을 것 같네요. 어느 부분에 대한 의견인지 모호함이 있었습니다. 제가 이해한 게 맞는지 모르네요. 그래서 코드를 가져왔습니다.
> 
> ```swift
>     @objc func changedView(_ sender: NavigationTapRecognizer) {
>         let imageDetailViewController = ImageDetailViewController()
>         imageDetailViewController.detailImage.image = sender.image
>         
>         let navigationController = UINavigationController(rootViewController: imageDetailViewController)
>         navigationController.modalPresentationStyle = .fullScreen
>         
>         present(navigationController, animated: false)
>     }
> }
> 
> class NavigationTapRecognizer: UITapGestureRecognizer {
>     var image: UIImage?
> }
> ```
> 
> [d84ea9f](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/d84ea9f95751086672a7baa5a55ae035eded311b) 수정입니다.
> 
> changedView함수를 통해 띄우는 것은 Modal이기에 ModalTapRecognizer로 수정하는 것에 동의합니다. 하지만 navigationController는 모달로서 동작하지만, 뷰의 형태는 Navigation입니다.
> 
> UIViewController를 present 시킨 것과는 다르게 UINavigationController를 활용한 Modal구현을 한 이유는 UINavigationController에 의해 관리되는 View Controller를 추가해 `navigationItem.leftBarButtonItem`과 같이 NavigationViewController에서도 활용가능한 코드를 사용하기 위함입니다.
> 
> NavigationController가 아닌 Modal로 이름짓는다면, Modal 코드에 rootViewController를 사용할 수 있다는 착각을 불러일으킬 수 있다 생각해 수정하지 않았습니다.

확인했습니다.
궁금한 점은 Modal이 아닌 NavigationController로 관리해야하는 이유가 따로 있을까요? 해당 부분은 ImageDetailView로 넘어가기 위한 코드인데, ImageDetailView는 항상 모달 형식으로 나오는 것으로 알고 있습니다. 해당 뷰가 모달 형태 외의 형태로 재사용되는 경우가 없는 것 같은데, 그렇다면 NavigationController로 활용할 일이 있을까요?

2022-12-03 18:45 UTC, taek0622 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +        present(navigationController, animated: false)
> > > p1;
> > > 해당 부분은 네비게이션이 아니라 모달인 것 같은데 customGestureRecognizer의 이름이 Navigation으로 되어있네요.
> > > 수정 부탁드립니다.
> 
> 새 방식을 생각하자면, 하단에 닫기버튼이 있는 게 낫지 않을까? 라는 생각이 듭니다. FullScreen모달은 닫기 버튼이 상단에 있을 때, 한 손으로 닫기 어렵기 때문입니다.

UI적으로는 잘 모르겠으나, 저희 앱 사용자들의 평균 연령대를 생각한다면 UX적으로는 하단에 닫기 버튼이 있는 것도 좋을 것 같습니다.
약간의 걱정은 하단에 닫기 버튼이 있을 때 오동작의 가능성이 생긴다는 것이긴 하다만, 그런 오동작보다는 상단 닫기버튼이 더 불편할 것 같다는 생각이 들긴하네요.

2022-12-03 18:49 UTC, taek0622 commented on Samsam/ViewController/DetailView/ImageDetailViewController.swift
> +            image: UIImage(systemName: "xmark"),
> > p5;
> > 해당 부분에 xmark가 들어가는 것이 약간 어색하다는 느낌이 듭니다.
> > 모달이기 때문에 x를 주신 것으로 보입니다만, 일반적으로 사진을 보여주는 어플들은 x 사용이 잘 안되고 있는 것 같아요.
> > left chevron이나 "닫기" 갇은 글자가 들어가면 어떨까 싶습니다.
> 
> [40e3b21](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/40e3b21b2f3c4f0db9662c573146de61eb1a086f) 수정했습니다.
> 
> 수정했으나, 익숙함은 UX에 강력한 근거가 되지만, 좋은 UX라고는 할 수 없다고 생각합니다. [우리의 기준은 우리의 사고방식으로](https://yozm.wishket.com/magazine/detail/1283/) 라는 글을 참고하여 추가로 얘기하자면, 남들이 저렇게 하기 때문에 이렇게 해야한다는 식의 UX보다 명확성을 근거로 사용자에게 의미를 전달하기 쉬워야 한다고 생각합니다. 그런 의미에서 Chevron.Left는 오히려 사용자에게 Swipe동작으로 뒤로가기를 할 수 있다는 착각과 모호함을 증대시키는 UI라는 생각이 듭니다.
> 
> '익숙함이 정말 익숙함이 맞는가?, 지금 느끼는 익숙함은 해당 기능이 아닌 해당 앱에 한정된 익숙함이 아닐까?'라는 생각이 듭니다. 다소 개인적인 의견일 수 있지만, 일반 사진앱에서 사용하는 Chevron.left도 모달화면임에도 네비게이션 동작을 할 수 있게 착각하게 만들 수 있다고 생각합니다. 하지만 닫기 또는 close 등의 문구를 사용하는 것은 오히려 앱의 무드를 해칠 수 있다고 생각해 미뉴의 의견대로 Chevron으로 수정하였습니다. 추후 디자인 수정 시 다시 이야기해보면 좋을 것 같습니다.

익숙함이 항상 좋은 UX가 될 수 없다는 것에는 동의합니다만, 현재 저희 앱의 사용자는 연령대가 높으신 분들입니다.
그래서 새로운 UX를 적용하면 이 새로운 UX에 적응하는 데에 시간이 걸릴 것이라 생각하여 기존 어플들을 찾아봤던 것입니다.
단순히 남들이 저렇게 하기 때문에 이렇게 해야한다고 생각한 것이 아니라, 앱 사용자를 생각했던 부분인데 이 부분에 대해 전달이 잘 안되었던 것 같네요.

2022-12-03 18:55 UTC, taek0622 commented on Samsam/ViewController/DetailView/ImageDetailViewController.swift
> +            let newHeight = image.size.height * ratio
> > p1;
> > image.size.width와 image.size.height는 이미 fixedWidth와 fixedHeight로 이미 정의된 것 같습니다.
> > 정의되어 있는 변수로 바꿔주세요.
> 
> [302602a](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/302602a93b1084a82f4ee250be3ae1b4bfaaa72d) 수정했습니다.

확인했습니다. 리뷰 리졸브합니다.

2022-12-03 18:56 UTC, taek0622 commented on Samsam/ViewController/DetailView/ImageDetailViewController.swift
> +            let fixedHeight = image.size.height
> > p5;
> > 아래에는 ratio는 ratio끼리 new는 new끼리 모여있는데, 이곳만 changed와 fixed가 함께 있어서 약간 헷갈리는 것 같습니다.
> > changed와 fixed를 분리하는 것은 어떨까요?
> 
> [302602a](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/302602a93b1084a82f4ee250be3ae1b4bfaaa72d) 수정했습니다. 아래의 코드순서를 보게되면 사용순서대로 변수명을 작성했었으나, 오히려 가독성을 해칠 수 있겠네요..!

확인했습니다. 리뷰 리졸브합니다.

2022-12-04 02:00 UTC, JUNY0110 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +        present(navigationController, animated: false)
> 확인했습니다. 궁금한 점은 Modal이 아닌 NavigationController로 관리해야하는 이유가 따로 있을까요? 해당 부분은 ImageDetailView로 넘어가기 위한 코드인데, ImageDetailView는 항상 모달 형식으로 나오는 것으로 알고 있습니다. 해당 뷰가 모달 형태 외의 형태로 재사용되는 경우가 없는 것 같은데, 그렇다면 NavigationController로 활용할 일이 있을까요?

앞서 설명하듯 navigationbar와 같은 네비게이션 관련 메소드를 사용하기 위함입니다.
일반 UIViewcontroller로 present하면 네비게이션 메소드를 사용할 수 없습니다.

2022-12-04 02:02 UTC, JUNY0110 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +        present(navigationController, animated: false)
> > > > p1;
> > > > 해당 부분은 네비게이션이 아니라 모달인 것 같은데 customGestureRecognizer의 이름이 Navigation으로 되어있네요.
> > > > 수정 부탁드립니다.
> > 
> > 
> > 새 방식을 생각하자면, 하단에 닫기버튼이 있는 게 낫지 않을까? 라는 생각이 듭니다. FullScreen모달은 닫기 버튼이 상단에 있을 때, 한 손으로 닫기 어렵기 때문입니다.
> 
> UI적으로는 잘 모르겠으나, 저희 앱 사용자들의 평균 연령대를 생각한다면 UX적으로는 하단에 닫기 버튼이 있는 것도 좋을 것 같습니다. 약간의 걱정은 하단에 닫기 버튼이 있을 때 오동작의 가능성이 생긴다는 것이긴 하다만, 그런 오동작보다는 상단 닫기버튼이 더 불편할 것 같다는 생각이 들긴하네요.

아직 정해진 디자인이 없어 수정하지는 않았습니다. 디자인이 수정되면 반영하겠습니다.

2022-12-04 02:06 UTC, ikanic commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +        present(navigationController, animated: false)
> > 확인했습니다. 궁금한 점은 Modal이 아닌 NavigationController로 관리해야하는 이유가 따로 있을까요? 해당 부분은 ImageDetailView로 넘어가기 위한 코드인데, ImageDetailView는 항상 모달 형식으로 나오는 것으로 알고 있습니다. 해당 뷰가 모달 형태 외의 형태로 재사용되는 경우가 없는 것 같은데, 그렇다면 NavigationController로 활용할 일이 있을까요?
> 
> 앞서 설명하듯 navigationbar와 같은 네비게이션 관련 메소드를 사용하기 위함입니다. 일반 UIViewcontroller로 present하면 네비게이션 메소드를 사용할 수 없습니다.

확인했습니다. 해당 설명만으로 잘 이해가 가지 않았는데, 따로 설명해주셔서 이해했습니다. 감사합니다~

2022-12-04 02:09 UTC, taek0622 approved these changes
고생하셨습니다.
여러모로 피곤하셨을텐데도 빠르게 반영해주셔서 너무 감사합니다.
앞으로도 잘 부탁드려요 에디~

2022-12-04 05:40 UTC, merged