[Feature] 카테고리별시공상황(ChipView)로 데이터 바인딩
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #148
Opened 2022-12-04 07:56 UTC by JUNY0110

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 코어데이터 삭제, 서버데이터 반영
- Extension 활용으로 Human Error를 줄이기 위함
- 카테고리별시공상황(ChipView)로 데이터(이미지, 텍스트, 카테고리) 바인딩하기 위함.

## Key Changes 🔥 (주요 구현/변경 사항)
- 시공내역뷰(WorkingHistoryView)에서 Status 데이터 Get
  - 시공내역뷰(WorkingHistoryView)에서 전체보기 클릭 시 카테고리별시공상황뷰(ChipView)로 Status 데이터 바인딩
- 카테고리별시공상황뷰(ChipView)에서 게시물과 칩 관련 코어데이터를 서버데이터로 전환(CoreData -> Server)
  - 선택된 게시물(selectedPosts) 배열 생성
  - `전체`를 제외한 `나머지 칩`은 selectedPosts를 이용해 구분 및 작업.
- RoomLIstViewController에서 DropLast, DropFirst가 반복되는 것에 대해 Human Error 최소화를 위한 String Extension 생성
 
## ToDo 📆 (남은 작업)
- [ ] 

## ScreenShot 📷 (참고 사진)
![Simulator Screen Recording - iPhone 13 Pro - 2022-12-04 at 16 54 04](https://user-images.githubusercontent.com/98405970/205480188-c24a961a-a4ac-4860-9953-96dccebb991c.gif)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 서버연결 및 바인딩 작업이 마무리되어갑니다.

## Reference 🔗
- 없음

## Close Issues 🔒 (닫을 Issue)
Close #146.

2022-12-04 08:41 UTC, taek0622 requested changes
고생하셨습니다.
WorkingHistoryView와 비슷한 듯 다른 부분이 많아서 생각보다 난이도가 있었을 테고, 특히 칩에 따라 게시물이 바뀌는 부분을 컨트롤하기 어려웠을 것 같은데 잘 해주셔서 매우 감사합니다.
수정이 필요해보이는 부분에 리뷰 남겼습니다. 확인 부탁드려요~

2022-12-04 08:41 UTC, taek0622 commented on Samsam/ViewController/ChipViewController.swift
> +    private var categoryArray: [Int] = []
p2;
이미 statuses라는 카테고리 정보를 담고있는 배열이 있음에도 categoryArray라는 별도의 배열을 만든 이유가 있을까요?
새로 만든 배열이 실제로 사용되는 곳이 단 한군데뿐입니다. 그렇다면 기존의 배열을 사용하는 것이 더 좋지 않을까요?

2022-12-04 08:41 UTC, taek0622 commented on Samsam/ViewController/ChipViewController.swift
> +        return 1
p1;
selectedID가 -가 되는 경우는 없을거라고 생각되어 1로 주신 것으로 보입니다.
또, 실제로 selectedID가 -가 되는 경우가 없을 것이라고 생각됩니다만, 그럼에도 불구하고 만일의 경우를 대비하기 위해 해당 부분은 1이 아닌 0이 되는 것이 더 좋을 것 같습니다.

2022-12-04 08:41 UTC, taek0622 commented on Samsam/ViewController/ChipViewController.swift
> +            }
p1;
해당 If문 구문은 아래와 같이 새로운 배열을 생성함으로 쉽게 하나로 합칠 수 있을 것 같네요.
```swift
let newArray = (selectedID == 0 ? posts : selectedPosts)
        
DispatchQueue.global().async {
    let data = try? Data(contentsOf: URL(string: newArray[indexPath.item].photos![0].photoPath)!)
            
    DispatchQueue.main.async {
        contentCell.uiImageView.image = UIImage(data: data!)
        contentCell.imageDescription.text = newArray[indexPath.item].description
        contentCell.workType.text = Category(rawValue: Int(newArray[indexPath.item].category))?.categoryName()
    }
}
```

2022-12-04 08:41 UTC, taek0622 commented on Samsam/ViewController/ChipViewController.swift
> +                detailViewController.images.append($0)
p4;
마찬가지로 위의 리뷰처럼 새로운 배열로 쉽게 하나로 합칠 수 있을 것 같습니다만, 이 부분은 반복되는 부분이 그렇게 많지 않으므로 그대로 유지되어도 괜찮을 것 같습니다.
위에서 선언해준 배열을 class 전역 property로 빼준다면 이곳에서도 사용할 수 있겠네요.

2022-12-05 07:19 UTC, JUNY0110 commented on Samsam/ViewController/ChipViewController.swift
> +                detailViewController.images.append($0)
> p4;
> 마찬가지로 위의 리뷰처럼 새로운 배열로 쉽게 하나로 합칠 수 있을 것 같습니다만, 이 부분은 반복되는 부분이 그렇게 많지 않으므로 그대로 유지되어도 괜찮을 것 같습니다.
> 위에서 선언해준 배열을 class 전역 property로 빼준다면 이곳에서도 사용할 수 있겠네요.

f1fde3c 굿 어떻게 빼나 고민하고 있었는데 효자손마냥 잘 긁어주셨네요 감사합니다.

2022-12-05 07:19 UTC, JUNY0110 commented on Samsam/ViewController/ChipViewController.swift
> +            }
> p1; 해당 If문 구문은 아래와 같이 새로운 배열을 생성함으로 쉽게 하나로 합칠 수 있을 것 같네요.
> 
> ```swift
> let newArray = (selectedID == 0 ? posts : selectedPosts)
>         
> DispatchQueue.global().async {
>     let data = try? Data(contentsOf: URL(string: newArray[indexPath.item].photos![0].photoPath)!)
>             
>     DispatchQueue.main.async {
>         contentCell.uiImageView.image = UIImage(data: data!)
>         contentCell.imageDescription.text = newArray[indexPath.item].description
>         contentCell.workType.text = Category(rawValue: Int(newArray[indexPath.item].category))?.categoryName()
>     }
> }
> ```

f1fde3c 굿 어떻게 빼나 고민하고 있었는데 효자손마냥 잘 긁어주셨네요 감사합니다.

2022-12-05 07:20 UTC, JUNY0110 commented on Samsam/ViewController/ChipViewController.swift
> +        return 1
> p1;
> selectedID가 -가 되는 경우는 없을거라고 생각되어 1로 주신 것으로 보입니다.
> 또, 실제로 selectedID가 -가 되는 경우가 없을 것이라고 생각됩니다만, 그럼에도 불구하고 만일의 경우를 대비하기 위해 해당 부분은 1이 아닌 0이 되는 것이 더 좋을 것 같습니다.

6aa651e 동의합니다~

2022-12-05 07:21 UTC, JUNY0110 commented on Samsam/ViewController/ChipViewController.swift
> +    private var categoryArray: [Int] = []
> p2;
> 이미 statuses라는 카테고리 정보를 담고있는 배열이 있음에도 categoryArray라는 별도의 배열을 만든 이유가 있을까요?
> 새로 만든 배열이 실제로 사용되는 곳이 단 한군데뿐입니다. 그렇다면 기존의 배열을 사용하는 것이 더 좋지 않을까요?

ffa0ca9 수정했습니다~

2022-12-05 07:24 UTC, taek0622 commented on Samsam/ViewController/ChipViewController.swift
> +    private var categoryArray: [Int] = []
> > p2;
> > 이미 statuses라는 카테고리 정보를 담고있는 배열이 있음에도 categoryArray라는 별도의 배열을 만든 이유가 있을까요?
> > 새로 만든 배열이 실제로 사용되는 곳이 단 한군데뿐입니다. 그렇다면 기존의 배열을 사용하는 것이 더 좋지 않을까요?
> 
> [ffa0ca9](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/ffa0ca9aa3b86d78c8f4117c9c8b39733fbef7e0) 수정했습니다~

확인했습니다. 리뷰 리졸브합니다.

2022-12-05 07:25 UTC, taek0622 commented on Samsam/ViewController/ChipViewController.swift
> +        return 1
> > p1;
> > selectedID가 -가 되는 경우는 없을거라고 생각되어 1로 주신 것으로 보입니다.
> > 또, 실제로 selectedID가 -가 되는 경우가 없을 것이라고 생각됩니다만, 그럼에도 불구하고 만일의 경우를 대비하기 위해 해당 부분은 1이 아닌 0이 되는 것이 더 좋을 것 같습니다.
> 
> [6aa651e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/6aa651e364c4b324a0653494e019e6c06c25df00) 동의합니다~

확인했습니다. 리뷰 리졸브합니다.

2022-12-05 07:26 UTC, taek0622 commented on Samsam/ViewController/ChipViewController.swift
> +            }
> > p1; 해당 If문 구문은 아래와 같이 새로운 배열을 생성함으로 쉽게 하나로 합칠 수 있을 것 같네요.
> > ```swift
> > let newArray = (selectedID == 0 ? posts : selectedPosts)
> >         
> > DispatchQueue.global().async {
> >     let data = try? Data(contentsOf: URL(string: newArray[indexPath.item].photos![0].photoPath)!)
> >             
> >     DispatchQueue.main.async {
> >         contentCell.uiImageView.image = UIImage(data: data!)
> >         contentCell.imageDescription.text = newArray[indexPath.item].description
> >         contentCell.workType.text = Category(rawValue: Int(newArray[indexPath.item].category))?.categoryName()
> >     }
> > }
> > ```
> 
> [f1fde3c](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/f1fde3c45d429a54c4ec178a86df6a5ead31813c) 굿 어떻게 빼나 고민하고 있었는데 효자손마냥 잘 긁어주셨네요 감사합니다.

효자손이라.. 드립력이 상당하시네요.
확인했습니다.
한가지, 새로운 배열 두개가 같은 역할을 하는 것으로 보이는데 해당 배열도 하나로 합칠 수 있지 않을까 하는 생각이 드네요.

2022-12-05 07:27 UTC, taek0622 commented on Samsam/ViewController/ChipViewController.swift
> +                detailViewController.images.append($0)
> > p4;
> > 마찬가지로 위의 리뷰처럼 새로운 배열로 쉽게 하나로 합칠 수 있을 것 같습니다만, 이 부분은 반복되는 부분이 그렇게 많지 않으므로 그대로 유지되어도 괜찮을 것 같습니다.
> > 위에서 선언해준 배열을 class 전역 property로 빼준다면 이곳에서도 사용할 수 있겠네요.
> 
> [f1fde3c](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/f1fde3c45d429a54c4ec178a86df6a5ead31813c) 굿

확인했습니다. 위의 코멘트와 마찬가지로 배열을 하나로 합칠 수도 있을 것 같긴합니다.

2022-12-05 07:27 UTC, taek0622 approved these changes
고생하셨습니다.
주말동안 피곤하셨을텐데도 작업량이 상당히 많네요.
너무너무 고생하셨어요.
앞으로도 잘 부탁드립니다. 에디~

2022-12-05 07:44 UTC, merged