[Feature] 업자 개인 정보 수정 기능 구현
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #150
Opened 2022-12-05 05:41 UTC by CreoHwan

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 업자 개인 정보 수정 기능 구현

## Key Changes 🔥 (주요 구현/변경 사항)
- 업자 개인 정보 수정 기능 구현

## ToDo 📆 (남은 작업)
- [ ] 버전 정보 뷰
- [ ] 개발자 정보 뷰

## ScreenShot 📷 (참고 사진)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 디자인 배치때문에 코드가 조금 길어졌습니다.
- 중복되는 코드가 많은 것 같습니다. 추후 extentsion으로 뺴면 더 좋을 것 같습니다.

## Reference 🔗

## Close Issues 🔒 (닫을 Issue)
Close #147

2022-12-05 09:24 UTC, taek0622 reviewed
고생하셨습니다.
새로운 뷰를 만드느라 작업량이 많으셨는데, 정말 고생하셨어요.
수정이 필요한 부분에 리뷰 남겼습니다. 확인 부탁드려요.

2022-12-05 09:24 UTC, ikanic commented on Samsam/ViewController/SettingView/ModificationWorkerViewController.swift
> +    }(UIView())
p2;
UI쪽에 네이밍 컨벤션이 지텨지고 있지 않은 것 같습니다.

2022-12-05 09:24 UTC, ikanic commented on Samsam/ViewController/SettingView/ModificationWorkerViewController.swift
> +    }(UITextField())
p1;
해당 부분은 업자에 관한 내용인데, customer라는 단어가 들어가서 헷갈리는 것 같습니다.
변수명 수정 부탁드립니다.

2022-12-05 09:24 UTC, ikanic commented on Samsam/ViewController/SettingView/ModificationWorkerViewController.swift
> +            height: 80
p1;
view에 직접 높이가 들어가 이유가 있을까요? view에 높이를 직접 줄 이유가 없을 것 같습니다.

2022-12-05 09:24 UTC, ikanic commented on Samsam/ViewController/SettingView/ModificationWorkerViewController.swift
> +    @objc private func buttonAttributeChanged() {
p1;
@objc 함수에서는 private이 의미가 없습니다.
실제로 objective-c에서는 private method가 존재하지 않습니다.
아래에 관련 레퍼런스 첨부합니다.

- [stack overflow - Why doesn't Objective-C support private methods?](https://stackoverflow.com/questions/2158660/why-doesnt-objective-c-support-private-methods)
- [Outsider's Dev Story - Objective-C에서 private 메서드 사용하기](https://blog.outsider.ne.kr/640)

2022-12-05 09:24 UTC, ikanic commented on Samsam/ViewController/SettingView/ModificationWorkerViewController.swift
> +            || phoneNum.count >= 8 && phoneNum != String((workerData?.number)!.dropFirst(6)).replacingOccurrences(of: " - ", with: "") {
p1;
해당 부분 가독성이 상당히 좋지 못합니다.
조건에 대한 확실한 구분이 필요할 것 같습니다.

2022-12-05 09:24 UTC, ikanic commented on Samsam/ViewController/SettingView/ModificationWorkerViewController.swift
> +    private func requestPut(workerID: Int , workerDTO: WorkerDTO) {
p1;
함수이름이 좋지 못한 것 같습니다.
정확히 어떤 put을 요청하는 것인지 이름에서 더 명확하게 알 수 있으면 좋을 것 같습니다.

2022-12-05 09:24 UTC, taek0622 requested changes
실수로 코멘트로 남겼네요. Request Changes로 변경합니다.

2022-12-06 00:58 UTC, CreoHwan commented on Samsam/ViewController/SettingView/ModificationWorkerViewController.swift
> +    }(UIView())
> p2; UI쪽에 네이밍 컨벤션이 지텨지고 있지 않은 것 같습니다.

021bf70 감사합니다!

2022-12-06 00:58 UTC, CreoHwan commented on Samsam/ViewController/SettingView/ModificationWorkerViewController.swift
> +    }(UITextField())
> p1; 해당 부분은 업자에 관한 내용인데, customer라는 단어가 들어가서 헷갈리는 것 같습니다. 변수명 수정 부탁드립니다.

021bf70 감사합니다!

2022-12-06 00:58 UTC, CreoHwan commented on Samsam/ViewController/SettingView/ModificationWorkerViewController.swift
> +    @objc private func buttonAttributeChanged() {
> p1; @objc 함수에서는 private이 의미가 없습니다. 실제로 objective-c에서는 private method가 존재하지 않습니다. 아래에 관련 레퍼런스 첨부합니다.
> 
> * [stack overflow - Why doesn't Objective-C support private methods?](https://stackoverflow.com/questions/2158660/why-doesnt-objective-c-support-private-methods)
> * [Outsider's Dev Story - Objective-C에서 private 메서드 사용하기](https://blog.outsider.ne.kr/640)

띠용! 감사합니다~! 021bf70

2022-12-06 00:58 UTC, CreoHwan commented on Samsam/ViewController/SettingView/ModificationWorkerViewController.swift
> +    private func requestPut(workerID: Int , workerDTO: WorkerDTO) {
> p1; 함수이름이 좋지 못한 것 같습니다. 정확히 어떤 put을 요청하는 것인지 이름에서 더 명확하게 알 수 있으면 좋을 것 같습니다.

021bf70 감사합니다!

2022-12-06 00:59 UTC, taek0622 commented on Samsam/ViewController/SettingView/ModificationWorkerViewController.swift
> +    }(UIView())
> > p2; UI쪽에 네이밍 컨벤션이 지텨지고 있지 않은 것 같습니다.
> 
> [021bf70](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/021bf705e5faa3c5a01b9f8046854ce726b0fc71) 감사합니다!

확인했습니다. 리뷰 리졸브합니다.

2022-12-06 01:00 UTC, taek0622 commented on Samsam/ViewController/SettingView/ModificationWorkerViewController.swift
> +    }(UITextField())
> > p1; 해당 부분은 업자에 관한 내용인데, customer라는 단어가 들어가서 헷갈리는 것 같습니다. 변수명 수정 부탁드립니다.
> 
> [021bf70](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/021bf705e5faa3c5a01b9f8046854ce726b0fc71) 감사합니다!

확인했습니다. 리뷰 리졸브합니다.

2022-12-06 01:01 UTC, taek0622 commented on Samsam/ViewController/SettingView/ModificationWorkerViewController.swift
> +    private func requestPut(workerID: Int , workerDTO: WorkerDTO) {
> > p1; 함수이름이 좋지 못한 것 같습니다. 정확히 어떤 put을 요청하는 것인지 이름에서 더 명확하게 알 수 있으면 좋을 것 같습니다.
> 
> [021bf70](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/021bf705e5faa3c5a01b9f8046854ce726b0fc71) 감사합니다!

확인했습니다. 리뷰 리졸브합니다.

2022-12-06 01:11 UTC, CreoHwan commented on Samsam/ViewController/SettingView/ModificationWorkerViewController.swift
> +            || phoneNum.count >= 8 && phoneNum != String((workerData?.number)!.dropFirst(6)).replacingOccurrences(of: " - ", with: "") {
> p1; 해당 부분 가독성이 상당히 좋지 못합니다. 조건에 대한 확실한 구분이 필요할 것 같습니다.

감사합니다~ 4fd06e7

2022-12-06 01:11 UTC, CreoHwan commented on Samsam/ViewController/SettingView/ModificationWorkerViewController.swift
> +            height: 80
> p1; view에 직접 높이가 들어가 이유가 있을까요? view에 높이를 직접 줄 이유가 없을 것 같습니다.

추후 고민해보도록 하겠습니다~!

2022-12-06 01:45 UTC, closed without merging

2022-12-06 02:04 UTC, taek0622 commented on Samsam/ViewController/SettingView/ModificationWorkerViewController.swift
> +    @objc private func buttonAttributeChanged() {
> > p1; @objc 함수에서는 private이 의미가 없습니다. 실제로 objective-c에서는 private method가 존재하지 않습니다. 아래에 관련 레퍼런스 첨부합니다.
> > 
> > * [stack overflow - Why doesn't Objective-C support private methods?](https://stackoverflow.com/questions/2158660/why-doesnt-objective-c-support-private-methods)
> > * [Outsider's Dev Story - Objective-C에서 private 메서드 사용하기](https://blog.outsider.ne.kr/640)
> 
> 띠용! 감사합니다~! [021bf70](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/021bf705e5faa3c5a01b9f8046854ce726b0fc71) [d03c7e1](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/d03c7e112892b1aef4ac221f5059cac3def5f52d)

확인했습니다~

2022-12-06 02:05 UTC, taek0622 commented on Samsam/ViewController/SettingView/ModificationWorkerViewController.swift
> +            || phoneNum.count >= 8 && phoneNum != String((workerData?.number)!.dropFirst(6)).replacingOccurrences(of: " - ", with: "") {
> > p1; 해당 부분 가독성이 상당히 좋지 못합니다. 조건에 대한 확실한 구분이 필요할 것 같습니다.
> 
> 감사합니다~ [4fd06e7](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/4fd06e7a06dd57967a6f8f3de820bc983a27193a)

확인했습니다. 리뷰 리졸브합니다.

2022-12-06 02:05 UTC, ikanic commented on Samsam/ViewController/SettingView/ModificationWorkerViewController.swift
> +            height: 80
> > p1; view에 직접 높이가 들어가 이유가 있을까요? view에 높이를 직접 줄 이유가 없을 것 같습니다.
> 
> 추후 고민해보도록 하겠습니다~!

우선 높이를 주는 방향으로 하기로 했습니다. 리뷰 리졸브합니다.