[Design] 백그라운드 및 버튼 색상 변경
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #161
Opened 2022-12-08 02:00 UTC by CreoHwan

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 백그라운드 및 버튼 색상 변경

## Key Changes 🔥 (주요 구현/변경 사항)
- Asset에 backgroundGray 추가

## ToDo 📆 (남은 작업)
- [ ] todo

## ScreenShot 📷 (참고 사진)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)

## Reference 🔗

## Close Issues 🔒 (닫을 Issue)
Close #160

2022-12-08 02:10 UTC, JUNY0110 approved these changes
굿 고생하셨습니다.

2022-12-08 02:36 UTC, taek0622 requested changes
고생하셨습니다.
앱 전체적으로 색을 바뀐 다지인에 맞게 변경해주셔서 감사합니다.
일부 수정이 필요한 부분에 리뷰 남겼습니다. 확인 부탁드려요~

2022-12-08 02:36 UTC, ikanic commented on Samsam/ViewController/PostingView/PostingImageButtonCell.swift
> +        backgroundColor = .clear
p2;
하이어라키로 확인해보니 cell의 경우 background를 주지 않으면 기본 clear로 들어가네요.
불필요한 코드인 것 같습니다. 삭제 부탁드려요~

2022-12-08 02:36 UTC, ikanic commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateFirstCell.swift
> +        backgroundColor = .clear
p2;
마찬가지로 cell은 배경을 안주면 기본 clear입니다.

2022-12-08 02:36 UTC, ikanic commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateHeader.swift
> +        backgroundColor = .clear
p2;
마찬가지로 cell에 배경을 안주면 기본 clear입니다.

2022-12-08 02:36 UTC, ikanic commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateSecondCell.swift
> +        backgroundColor = .clear
p2;
마찬가지로 cell에 배경을 주지 않으면 기본 clear입니다.

2022-12-08 02:36 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewWarrantyCell.swift
> +        backgroundColor = .clear
p2;
마찬가지로 cell에 배경을 주지 않으면 기본 clear입니다.

2022-12-08 16:20 UTC, JUNY0110 commented
컨플릭트 설명드릴게요!
ChipView는 배경색은 AppColor 그대로 하고, 수정사항 반영하시면 됩니다.
SegmentedControlView에서 button은 삭제되었습니다.

2022-12-09 06:54 UTC, CreoHwan commented on Samsam/ViewController/PostingView/PostingImageButtonCell.swift
> +        backgroundColor = .clear
> p2; 하이어라키로 확인해보니 cell의 경우 background를 주지 않으면 기본 clear로 들어가네요. 불필요한 코드인 것 같습니다. 삭제 부탁드려요~

ec2b3c5 감사합니다!

2022-12-09 06:55 UTC, CreoHwan commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateFirstCell.swift
> +        backgroundColor = .clear
> p2; 마찬가지로 cell은 배경을 안주면 기본 clear입니다.

ec2b3c5 감사합니다!

2022-12-09 06:55 UTC, CreoHwan commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateHeader.swift
> +        backgroundColor = .clear
> p2; 마찬가지로 cell에 배경을 안주면 기본 clear입니다.

ec2b3c5 감사합니다!

2022-12-09 06:55 UTC, CreoHwan commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateSecondCell.swift
> +        backgroundColor = .clear
> p2; 마찬가지로 cell에 배경을 주지 않으면 기본 clear입니다.

ec2b3c5 감사합니다!

2022-12-09 06:55 UTC, CreoHwan commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewWarrantyCell.swift
> +        backgroundColor = .clear
> p2; 마찬가지로 cell에 배경을 주지 않으면 기본 clear입니다.

ec2b3c5 감사합니다!

2022-12-09 08:49 UTC, taek0622 commented on Samsam/ViewController/PostingView/PostingImageButtonCell.swift
> +        backgroundColor = .clear
> > p2; 하이어라키로 확인해보니 cell의 경우 background를 주지 않으면 기본 clear로 들어가네요. 불필요한 코드인 것 같습니다. 삭제 부탁드려요~
> 
> [ec2b3c5](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/ec2b3c53a9c36ea8dff2292176fd858c2ddbd952) 감사합니다!

확인했습니다. 리뷰 리졸브합니다.

2022-12-09 08:49 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateFirstCell.swift
> +        backgroundColor = .clear
> > p2; 마찬가지로 cell은 배경을 안주면 기본 clear입니다.
> 
> [ec2b3c5](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/ec2b3c53a9c36ea8dff2292176fd858c2ddbd952) 감사합니다!

확인했습니다. 리뷰 리졸브합니다.

2022-12-09 08:49 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateHeader.swift
> +        backgroundColor = .clear
> > p2; 마찬가지로 cell에 배경을 안주면 기본 clear입니다.
> 
> [ec2b3c5](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/ec2b3c53a9c36ea8dff2292176fd858c2ddbd952) 감사합니다!

확인했습니다. 리뷰 리졸브합니다.

2022-12-09 08:49 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewDateSecondCell.swift
> +        backgroundColor = .clear
> > p2; 마찬가지로 cell에 배경을 주지 않으면 기본 clear입니다.
> 
> [ec2b3c5](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/ec2b3c53a9c36ea8dff2292176fd858c2ddbd952) 감사합니다!

확인했습니다. 리뷰 리졸브합니다.

2022-12-09 08:49 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/UIComponent/RoomCreationViewWarrantyCell.swift
> +        backgroundColor = .clear
> > p2; 마찬가지로 cell에 배경을 주지 않으면 기본 clear입니다.
> 
> [ec2b3c5](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/ec2b3c53a9c36ea8dff2292176fd858c2ddbd952) 감사합니다!

확인했습니다. 리뷰 리졸브합니다.

2022-12-09 08:50 UTC, taek0622 approved these changes
고생하셨습니다~

2022-12-10 00:57 UTC, merged