[Design] 룸 리스트 뷰 디자인 변경
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #176
Opened 2022-12-09 06:50 UTC by CreoHwan

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 륨 리스트 뷰 디자인 변경

## Key Changes 🔥 (주요 구현/변경 사항)

## ToDo 📆 (남은 작업)
- [ ] todo

## ScreenShot 📷 (참고 사진)
![IMG_5972](https://user-images.githubusercontent.com/92836045/206642521-4cc3a2a9-5018-4450-8fa1-75aa1ebfe7e5.PNG)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 늦어서 죄송합니다

## Reference 🔗

## Close Issues 🔒 (닫을 Issue)
Close #163

2022-12-09 17:13 UTC, JUNY0110 requested changes
고생하셨습니다. 역시.. 디너의 코드는 재밌네요..

2022-12-09 17:13 UTC, JUNY0110 commented on Samsam/ViewController/RoomListCell.swift
>          $0.layer.shadowRadius = 15
p1.
쉐도우는 없는 게 맞습니다~

2022-12-09 17:13 UTC, JUNY0110 commented on Samsam/ViewController/RoomListCell.swift
> +        $0.textAlignment = .left
p2.
인터넷 문제가 생겼을 때 디폴트로 보여지는 이름이 '방이름'인 것보다, ""처럼 작성되지 않은 내용이 더 자연스러울 것 같습니다.

2022-12-09 17:13 UTC, JUNY0110 commented on Samsam/ViewController/RoomListCell.swift
> +            paddingBottom: 10
p3. 
 이 뷰는 기존 코드를 부분 수정하신 것 같은데, 제 생각엔 코드가 재작성되는 게 더 좋은 코드인 것 같습니다.
 일단, roomStack는 최초 디자인에서 초대코드를 위해 만들었던 코드이기 때문에 없어도 무방할 것 같습니다. 
spacer로 사용된 뷰도 굳이 사용하지 않고 기존 `방 이름`과 `날짜`를 하나의 UIView로 묶으면 해결되기 때문입니당..

혹여 시간소요가 많이 드는 작업이라면,, 이라는 이유로 P3를 남깁니다

2022-12-09 17:13 UTC, JUNY0110 commented on Samsam/ViewController/RoomListViewController.swift
> +    var asRooms = [Room]()
p1.
제가... 뭘 본걸까요..? 이걸 직관적이라 해야할지 비직관적이라 해야할까요? 지금은 알고 봐서 이해가 되지만, 나중에 보게되면 곤란한 변수명일 것 같습니다.

2022-12-09 17:13 UTC, JUNY0110 commented on Samsam/ViewController/RoomListViewController.swift
> +
p3.
현재 present에 competion은 불필요한 코드라 삭제해주셔도 될 것 같습니다.

2022-12-10 01:01 UTC, creohwan commented on Samsam/ViewController/RoomListCell.swift
>          $0.layer.shadowRadius = 15
> p1. 쉐도우는 없는 게 맞습니다~

a253526 감사합니다~!

2022-12-10 01:01 UTC, creohwan commented on Samsam/ViewController/RoomListCell.swift
> +        $0.textAlignment = .left
> p2. 인터넷 문제가 생겼을 때 디폴트로 보여지는 이름이 '방이름'인 것보다, ""처럼 작성되지 않은 내용이 더 자연스러울 것 같습니다.

a253526 감사합니다~!

2022-12-10 01:03 UTC, CreoHwan commented on Samsam/ViewController/RoomListViewController.swift
> +
> p3. 현재 present에 competion은 불필요한 코드라 삭제해주셔도 될 것 같습니다.

23fca3f 넵 감사합니다~!

2022-12-10 01:34 UTC, closed without merging

2022-12-10 01:35 UTC, CreoHwan commented on Samsam/ViewController/RoomListCell.swift
> +            paddingBottom: 10
> p3. 이 뷰는 기존 코드를 부분 수정하신 것 같은데, 제 생각엔 코드가 재작성되는 게 더 좋은 코드인 것 같습니다. 일단, roomStack는 최초 디자인에서 초대코드를 위해 만들었던 코드이기 때문에 없어도 무방할 것 같습니다. spacer로 사용된 뷰도 굳이 사용하지 않고 기존 `방 이름`과 `날짜`를 하나의 UIView로 묶으면 해결되기 때문입니당..
> 
> 혹여 시간소요가 많이 드는 작업이라면,, 이라는 이유로 P3를 남깁니다

추후 수정하도록 하겠습니다... 감사합니다... ㅠㅠ :)