[Design]  룸 리스트 뷰 디자인 변경 / 시공 상황 작성하기 버튼 색상 변경
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #184
Opened 2022-12-10 01:41 UTC by CreoHwan

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
-룸 리스트 뷰 디자인 변경
- 시공 상황 작성하기 버튼 색상 변경

## Key Changes 🔥 (주요 구현/변경 사항)

## ToDo 📆 (남은 작업)
- [ ] todo

## ScreenShot 📷 (참고 사진)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)

## Reference 🔗

## Close Issues 🔒 (닫을 Issue)
Close #No.

2022-12-10 07:38 UTC, JUNY0110 requested changes
Section 간 간격에 차이가 있어야 합니다~  AS관리고객 상단은 24, AS관리고객의 하단은 16입니다.

2022-12-10 13:07 UTC, CreoHwan commented
> Section 간 간격에 차이가 있어야 합니다~ AS관리고객 상단은 24, AS관리고객의 하단은 16입니다.

31000ed 감사합니다~!

2022-12-10 16:36 UTC, JUNY0110 commented
> > Section 간 간격에 차이가 있어야 합니다~ AS관리고객 상단은 24, AS관리고객의 하단은 16입니다.
> 
> [31000ed](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/31000ed29457fe762ba6344580b2eadc67aa4caf) 감사합니다~!

CollectionView의 EdgeInset을 80정도 주면 최하단의 방목록이 버튼에 가려지지 않을 것 같습니당

2022-12-11 06:09 UTC, CreoHwan commented
> > > Section 간 간격에 차이가 있어야 합니다~ AS관리고객 상단은 24, AS관리고객의 하단은 16입니다.
> > 
> > 
> > [31000ed](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/31000ed29457fe762ba6344580b2eadc67aa4caf) 감사합니다~!
> 
> CollectionView의 EdgeInset을 80정도 주면 최하단의 방목록이 버튼에 가려지지 않을 것 같습니당

넵 감사합니다~ f78416f

2022-12-11 06:58 UTC, JUNY0110 approved these changes

2022-12-11 07:59 UTC, taek0622 requested changes
고생하셨습니다.
수정이 필요해보이는 부분 리뷰 남겼습니다. 확인 부탁드려요.

2022-12-11 07:59 UTC, taek0622 commented on Samsam/ViewController/RoomListView/RoomListViewController.swift
> +    var doneRooms = [Room]()
p4;
변수 이름이 애매하네요..
당장 떠오르는 이름이 없긴하지만, 비직관적이라는 생각이 들긴합니다.

2022-12-11 07:59 UTC, taek0622 commented on Samsam/ViewController/RoomListView/RoomListViewController.swift
> +            cell.chipText.text = "\(cell.startDate.text!) ~ \(cell.endDate.text!)"
p1;
해당 부분은 비슷한 구문이 반복되고 있는 것 같습니다. 해당 부분은
```swift
let newArray = indexPath.section == 0 ? doingRooms : doneRooms

tapRoomListButton.rooms = newArray[indexPath.item]
cell.roomTitle.text = neweArray[indexPath.row].clientName
cell.startDate.text = convertDate(dateString: newArray[indexPath.row].startDate)
cell.endDate.text = convertDate(dateString: newArray[indexPath.row].endDate)
cell.chipText.text = "\(cell.startDate.teext!) ~ \(String(describing: cell.endDate.text!))"
```
와 같이 변경할 수 있겠네요.

또, indexPath.item과 indexPath.row가 혼용되고 있는 것 같은데 이렇게 되어야 하는 이유가 있을까요?

2022-12-11 07:59 UTC, taek0622 commented on Samsam/ViewController/RoomListView/RoomListCell.swift
> +    }(UIStackView())
p1;
해당 부분은 제가 예전 디자인을 가지고 셀에서 두가지 액션을 주기 위해서 나눠줬던 부분입니다.
현재의 디자인에서는 이렇게 나뉠 이유가 없는 것 같습니다.

2022-12-11 07:59 UTC, taek0622 commented on Samsam/ViewController/RoomListView/RoomListCell.swift
> +    }(UIView())
p1;
마찬가지로 Spacer들 또한 제가 예전 디자인을 위해 만들어 두었던 부분입니다.
현재 디자인에서는 Spacer 없이 패딩으로 충분히 조절이 가능한 것 같네요.

2022-12-11 11:35 UTC, CreoHwan commented on Samsam/ViewController/RoomListView/RoomListViewController.swift
> +            cell.chipText.text = "\(cell.startDate.text!) ~ \(cell.endDate.text!)"
> p1; 해당 부분은 비슷한 구문이 반복되고 있는 것 같습니다. 해당 부분은
> 
> ```swift
> let newArray = indexPath.section == 0 ? doingRooms : doneRooms
> 
> tapRoomListButton.rooms = newArray[indexPath.item]
> cell.roomTitle.text = neweArray[indexPath.row].clientName
> cell.startDate.text = convertDate(dateString: newArray[indexPath.row].startDate)
> cell.endDate.text = convertDate(dateString: newArray[indexPath.row].endDate)
> cell.chipText.text = "\(cell.startDate.teext!) ~ \(String(describing: cell.endDate.text!))"
> ```
> 
> 와 같이 변경할 수 있겠네요.
> 
> 또, indexPath.item과 indexPath.row가 혼용되고 있는 것 같은데 이렇게 되어야 하는 이유가 있을까요?

c3038ba 감사합니다~!

2022-12-11 11:43 UTC, taek0622 commented on Samsam/ViewController/RoomListView/RoomListViewController.swift
> +            cell.chipText.text = "\(cell.startDate.text!) ~ \(cell.endDate.text!)"
> > p1; 해당 부분은 비슷한 구문이 반복되고 있는 것 같습니다. 해당 부분은
> > ```swift
> > let newArray = indexPath.section == 0 ? doingRooms : doneRooms
> > 
> > tapRoomListButton.rooms = newArray[indexPath.item]
> > cell.roomTitle.text = neweArray[indexPath.row].clientName
> > cell.startDate.text = convertDate(dateString: newArray[indexPath.row].startDate)
> > cell.endDate.text = convertDate(dateString: newArray[indexPath.row].endDate)
> > cell.chipText.text = "\(cell.startDate.teext!) ~ \(String(describing: cell.endDate.text!))"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 와 같이 변경할 수 있겠네요.
> > 또, indexPath.item과 indexPath.row가 혼용되고 있는 것 같은데 이렇게 되어야 하는 이유가 있을까요?
> 
> [c3038ba](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/c3038ba53da29f713dd9b6a32179f5c0713d4eed) 감사합니다~!

확인했습니다~

2022-12-11 11:52 UTC, CreoHwan commented on Samsam/ViewController/RoomListView/RoomListCell.swift
> +    }(UIStackView())
> p1; 해당 부분은 제가 예전 디자인을 가지고 셀에서 두가지 액션을 주기 위해서 나눠줬던 부분입니다. 현재의 디자인에서는 이렇게 나뉠 이유가 없는 것 같습니다.

24ae2fd 감사합니다~

2022-12-11 11:52 UTC, CreoHwan commented on Samsam/ViewController/RoomListView/RoomListCell.swift
> +    }(UIView())
> p1; 마찬가지로 Spacer들 또한 제가 예전 디자인을 위해 만들어 두었던 부분입니다. 현재 디자인에서는 Spacer 없이 패딩으로 충분히 조절이 가능한 것 같네요.

24ae2fd 감사합니다~

2022-12-11 11:54 UTC, taek0622 commented on Samsam/ViewController/RoomListView/RoomListCell.swift
> +    }(UIStackView())
> > p1; 해당 부분은 제가 예전 디자인을 가지고 셀에서 두가지 액션을 주기 위해서 나눠줬던 부분입니다. 현재의 디자인에서는 이렇게 나뉠 이유가 없는 것 같습니다.
> 
> [24ae2fd](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/24ae2fdfbf6653ea2d301b05fb895d1ce6ae196c) 감사합니다~

확인했습니다. 리뷰 리졸브합니다.

2022-12-11 11:55 UTC, taek0622 commented on Samsam/ViewController/RoomListView/RoomListCell.swift
> +    }(UIView())
> > p1; 마찬가지로 Spacer들 또한 제가 예전 디자인을 위해 만들어 두었던 부분입니다. 현재 디자인에서는 Spacer 없이 패딩으로 충분히 조절이 가능한 것 같네요.
> 
> [24ae2fd](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/24ae2fdfbf6653ea2d301b05fb895d1ce6ae196c) 감사합니다~

확인했습니다. 리뷰 리졸브합니다.

2022-12-11 11:57 UTC, taek0622 approved these changes
고생하셨습니다.
변경 사항과 수정 사항이 많아서 힘드셨을텐데, 정말 고생 많으셨어요.

2022-12-11 11:59 UTC, merged