[Design] 시공상황 작성 뷰 디자인 변경 / 시공상황 수정 기능 구현 / 셀 백그라운드 버그 해결
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #188
Opened 2022-12-10 06:55 UTC by CreoHwan

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 시공상황 작성 뷰 디자인 변경 
- 시공상황 수정 기능 구현 
- 셀 백그라운드 버그 해결

## Key Changes 🔥 (주요 구현/변경 사항)

## ToDo 📆 (남은 작업)
- [ ] todo

## ScreenShot 📷 (참고 사진)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)

## Reference 🔗
- pop 2번 하는 방법!
- https://stackoverflow.com/questions/26132658/pop-2-view-controllers-in-nav-controller-in-swift

## Close Issues 🔒 (닫을 Issue)
Close #187

2022-12-10 07:48 UTC, JUNY0110 requested changes
버그가 생겼네요.. 수정바랍니다 ㅠㅠ

2022-12-10 07:48 UTC, JUNY0110 commented on Samsam/ViewController/PostingView/PostingWritingView.swift
> +        $0.addTarget(self, action: #selector(modifyPostBTN), for: .touchUpInside)
p1. 
설명수정 화면에서 돌아오면 네비게이션 버튼이 모두 회색으로 바뀌는 버그 발생.. 수정요망입니다 ㅠㅠ

2022-12-11 06:15 UTC, CreoHwan commented on Samsam/ViewController/PostingView/PostingWritingView.swift
> +        $0.addTarget(self, action: #selector(modifyPostBTN), for: .touchUpInside)
> p1. 설명수정 화면에서 돌아오면 네비게이션 버튼이 모두 회색으로 바뀌는 버그 발생.. 수정요망입니다 ㅠㅠ

7288de2 해결했습니다!

2022-12-11 07:00 UTC, JUNY0110 commented on Samsam/ViewController/PostingView/PostingWritingView.swift
> +        $0.addTarget(self, action: #selector(modifyPostBTN), for: .touchUpInside)
> > p1. 설명수정 화면에서 돌아오면 네비게이션 버튼이 모두 회색으로 바뀌는 버그 발생.. 수정요망입니다 ㅠㅠ
> 
> [7288de2](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/7288de2804545cc3188442f06ae3e347a69f6436) 해결했습니다!

고생하셨습니다~

2022-12-11 07:00 UTC, JUNY0110 approved these changes
고생하셨습니다!

2022-12-11 08:11 UTC, taek0622 requested changes
고생하셨습니다.
수정이 필요해보이는 부분에 리뷰 남겼습니다. 확인 부탁드려요.

2022-12-11 08:11 UTC, taek0622 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +    var postID: Int?
p1;
MARK 주석 위 아래로는 한줄씩 띄워줘야한다는 컨벤션이 있습니다.
위에 공백 한줄이 필요할 것 같네요.

2022-12-11 08:11 UTC, taek0622 commented on Samsam/ViewController/PostingView/PostingWritingView.swift
> +        if textView.text == textViewPlaceHolder && postCreation {
p2;
if 구문의 조건 구분이 불명확합니다. 괄호 등으로 `(textView.text == textViewPlaceHolder) && postCreation`인지 혹은 `textView.text == (textViewPlaceHoler && postCreation)`인지 구분 부탁드립니다.

2022-12-11 11:24 UTC, CreoHwan commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +    var postID: Int?
> 

8254f77 으악! 감사합니다!

2022-12-11 11:24 UTC, CreoHwan commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +    var postID: Int?
> p1; MARK 주석 위 아래로는 한줄씩 띄워줘야한다는 컨벤션이 있습니다. 위에 공백 한줄이 필요할 것 같네요.

8254f77 으악! 감사합니다!

2022-12-11 11:25 UTC, CreoHwan commented on Samsam/ViewController/PostingView/PostingWritingView.swift
> +        if textView.text == textViewPlaceHolder && postCreation {
> p2; if 구문의 조건 구분이 불명확합니다. 괄호 등으로 `(textView.text == textViewPlaceHolder) && postCreation`인지 혹은 `textView.text == (textViewPlaceHoler && postCreation)`인지 구분 부탁드립니다.

8fc77ef 그렇군요! 감사합니다~

2022-12-11 11:58 UTC, taek0622 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +    var postID: Int?
> > p1; MARK 주석 위 아래로는 한줄씩 띄워줘야한다는 컨벤션이 있습니다. 위에 공백 한줄이 필요할 것 같네요.
> 
> [8254f77](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/8254f770e45463b6a1d92f7fbe65fc102eee8b63) 으악! 감사합니다!

확인했습니다. 리뷰 리졸브합니다.

2022-12-11 11:58 UTC, taek0622 commented on Samsam/ViewController/PostingView/PostingWritingView.swift
> +        if textView.text == textViewPlaceHolder && postCreation {
> > p2; if 구문의 조건 구분이 불명확합니다. 괄호 등으로 `(textView.text == textViewPlaceHolder) && postCreation`인지 혹은 `textView.text == (textViewPlaceHoler && postCreation)`인지 구분 부탁드립니다.
> 
> [8fc77ef](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/8fc77ef64be5a5163aa551afbad5e1f10b69cf4b) 그렇군요! 감사합니다~

확인했습니다. 리뷰 리졸브합니다.

2022-12-11 11:58 UTC, taek0622 approved these changes
고생하셨습니다.
연달아 여러 태스크들을 하시느라 힘드셨을텐데, 정말 고생하셨어요.

2022-12-11 11:59 UTC, merged