[Design] 담당자 연락처 입력 뷰 레이아웃 그리기
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #19
Opened 2022-10-18 09:14 UTC by ikanic

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 고객이 업자에게 쉽게 연락할 수 있도록 앱 내에서 전화로 이어지는 기능의 추가가 필요하여 업자의 연락처를 받아야 했음
- 애플 로그인 API에서는 해당 아이디 사용자의 연락처를 받아올 수 없음
- 별도의 뷰에서 업자의 연락처를 받아와야했기 때문에 담당자 연락처를 입력받을 수 있는 뷰가 필요하여 코드 추가

## Key Changes 🔥 (주요 구현/변경 사항)
- PhoneNumView 레이아웃 생성

## ToDo 📆 (남은 작업)
- [ ] 연락처를 입력했을 때, 올바른 형식인지 확인하고 올바른 형식일 때만 다음 뷰로 넘어가는 기능 추가
- [ ] 버튼 색 변경
- [ ] 온보딩 추가

## ScreenShot 📷 (참고 사진)
<img src="https://user-images.githubusercontent.com/81027256/196389064-90f7ad44-7acf-4d15-9116-54458cd700ae.gif" width=300>

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 간단한 뷰 그리기 작업입니다. 가볍게 리뷰해 주셔도 좋습니다.

## Reference 🔗
- 없음

## Close Issues 🔒 (닫을 Issue)
Close #18.

2022-10-18 13:39 UTC, JUNY0110 approved these changes
고생하셨습니다.

2022-10-18 13:39 UTC, JUNY0110 commented on Samsam/ViewController/PhoneNumViewController.swift
> +        $0.setHeight(height: 60)
p1. 
figma에 있는 버튼 사이즈는 50입니다.

2022-10-18 13:39 UTC, JUNY0110 commented on Samsam/ViewController/PhoneNumViewController.swift
> +    }(UITextField())
Q.
lazy로 하는 이유가 있을까요?

2022-10-18 13:39 UTC, JUNY0110 requested changes
고생하셨습니다. 버튼 사이즈만 조정하시면 될 것 같습니다.

2022-10-18 14:55 UTC, taek0622 commented on Samsam/ViewController/PhoneNumViewController.swift
> +        $0.setHeight(height: 60)
> p1. figma에 있는 버튼 사이즈는 50입니다.

처음에 50으로 맞췄다가 너무 버튼이 얇아보여 60으로 수정했습니다만, Figma에 맞춰 다시 50으로 수정했습니다.
해당 부분은 6246906 에서 반영 되었습니다. 감사합니다.

2022-10-18 15:03 UTC, ikanic commented on Samsam/ViewController/PhoneNumViewController.swift
> +    }(UITextField())
> Q. lazy로 하는 이유가 있을까요?

현재와 같은 경우 사실 `let`으로 선언한 것과 결과가 다르지 않습니다.
`lazy var`의 경우 swift에서 메모리 관리를 위해 사용될 수 있습니다.
자세한 내용은 `lazy variable`이라는 키워드로 찾아보시면 좋을 것 같습니다.

아래에 레퍼런스 첨부합니다.
- [Hyunndy iOS Dev log - [Swift] lazy 키워드](https://baked-corn.tistory.com/45)
- [이동건의 이유있는 코드 - [Swift] lazy Variables](https://hyunndyblog.tistory.com/155)

2022-10-18 15:03 UTC, taek0622 commented
@JUNY0110 리뷰해 주신 부분 수정했습니다. 재검토 부탁드립니다. 항상 감사합니다 에디~

2022-10-19 01:54 UTC, JUNY0110 approved these changes
고생하셨습니다

2022-10-19 01:56 UTC, merged