Design/5 makingcategory
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #24
Opened 2022-10-19 02:53 UTC by CreoHwan

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 시공상황 작성 뷰에서 카테고리 선택 뷰 생성

## Key Changes 🔥 (주요 구현/변경 사항)
- UICollectionViewCell 생성
- UICollectionView 레이아웃 생성
- Button 을 이용하여 '시공상황 작성 이미지 뷰'로 Navigatioin 이동

## ToDo 📆 (남은 작업)
- [ ] 클릭 시 개수 제한 작업

## ScreenShot 📷 (참고 사진)
![#5](https://user-images.githubusercontent.com/92836045/196586056-7bc74b5c-fca0-46d7-96a4-1fa3fe09b220.gif)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 빡센 리뷰 환영

## Reference 🔗

## Close Issues 🔒 (닫을 Issue)
Close #5 .

2022-10-19 09:00 UTC, taek0622 requested changes
첫 PR 감사합니다 디너
정말 고생하셨어요.
변경이 필요한 부분에 코멘트 남겼으니 참고하시고 수정 부탁드립니다.
더불어 PR 제목도 규칙이 있으니 Wiki의 [Pull Request Convention](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/wiki/Pull-Request-Convention) 참고해서 제목 수정 부탁드려요.
또, 한 PR은 최대 250 라인으로 제한하고 있는데 현재 331 라인이 PR에 들어와 있습니다.
다음 PR부터는 250 라인 안쪽으로 부탁드리겠습니다~

2022-10-19 09:00 UTC, taek0622 commented on .gitignore
> +Samsam/Global/SceneDelegate.swift
p2;
SceneDelegate가 gitignore에 들어가게되면 테스트할 때는 편하지만, 실제로 첫 뷰를 변경할 때는 좋지 못할 것 같습니다.
SceneDelegate를 ignore에 넣는 것은 메인 뷰를 SceneDelegate에 넣어두고 나서가 어떨까요?

2022-10-19 09:00 UTC, taek0622 commented on Samsam/Base.lproj/Main.storyboard
> +<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="21225" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitColle
p1;
스토리보드의 수정사항이 생길 이유가 없습니다.
또한, 스토리보드가 github에 올라갈 이유도 없는 것 같아요.
해당 부분은 제외하고 올려주시면 감사하겠습니다.

2022-10-19 09:00 UTC, taek0622 commented on Samsam/Global/SceneDelegate.swift
> +        let navi = UINavigationController(rootViewController: PostingCategoryViewController())
p1;
SceneDelegate가 변경되어 올라오고 있는 것 같네요.
해당 부분 수정 부탁드립니다~

2022-10-19 09:00 UTC, taek0622 commented on Samsam/ViewController/CategoryCell.swift
> +                        self.categoryImage.image = UIImage(named:"category1")
p3;
현재는 테스트 이미지이기 때문에 변경하지 않아도 좋지만, 실제 이미지를 사용할 때는 enum으로 이미지 리터럴을 만들어서 사용하는 것이 더 좋을 것 같습니다.

2022-10-19 09:00 UTC, taek0622 commented on Samsam/ViewController/CategoryCell.swift
> +        $0.image = UIImage(named: "")
p3;
여기는 일부러 비워두신 것 같은데, 기본 이미지라도 넣어두는 것이 더 좋을 것 같네요.

2022-10-19 09:00 UTC, taek0622 commented on Samsam/ViewController/CategoryCell.swift
> +    }
p3;
cell의 layout과 setupCell이 잘 구분되지 않고 있는 것 같습니다.
해당 내용은 setupCell 안쪽으로 이동시켜도 될 것 같아요.

2022-10-19 09:00 UTC, taek0622 commented on Samsam/ViewController/PostingCategoryViewController.swift
> +
p2;
여기 공백 한 줄은 불필요할 것 같습니다. 삭제 부탁드려요~

2022-10-19 09:00 UTC, taek0622 commented on Samsam/ViewController/PostingCategoryViewController.swift
> +
p2;
공백이 한 줄 이상이 될 이유가 없는 것 같습니다.
공백은 최대 한 줄까지만 사용 부탁드러요.

2022-10-19 09:00 UTC, taek0622 commented on Samsam/ViewController/PostingCategoryViewController.swift
> +            right: view.rightAnchor
p2;
top, left, right anchor는 의도하신 것이 아니라면 safeAreaLayoutGuide라인을 기준으로 주시는 것이 더 좋을 것 같습니다.

2022-10-19 09:00 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +
p1;
불필요한 주석 삭제 부탁드려요~

2022-10-19 13:54 UTC, JUNY0110 commented
고생하셨습니다. PR Label이 안 되어 있어 추가했습니다~

2022-10-20 01:33 UTC, CreoHwan commented on Samsam/ViewController/CategoryCell.swift
> +        $0.image = UIImage(named: "")
넵!

2022-10-20 01:44 UTC, CreoHwan commented on .gitignore
> +Samsam/Global/SceneDelegate.swift
해결했습니다! [e4a5883]

2022-10-20 01:45 UTC, CreoHwan commented on Samsam/Global/SceneDelegate.swift
> +        let navi = UINavigationController(rootViewController: PostingCategoryViewController())
해결했습니다! [67ff338]

2022-10-20 01:51 UTC, creohwan commented on Samsam/ViewController/CategoryCell.swift
> +    }
감사합니다! 해결했습니다! e7ad9c1

2022-10-20 01:53 UTC, CreoHwan commented on Samsam/ViewController/PostingCategoryViewController.swift
> +
넵! 감사합니다! c9d9aa0

2022-10-20 01:53 UTC, creohwan commented on Samsam/ViewController/PostingCategoryViewController.swift
> +
넵! 감사합니다! c9d9aa0

2022-10-20 01:53 UTC, creohwan commented on Samsam/ViewController/PostingImageViewController.swift
> +
넵! 감사합니다! c9d9aa0

2022-10-20 01:56 UTC, creohwan commented on Samsam/ViewController/PostingCategoryViewController.swift
> +            right: view.rightAnchor
넵! 감사합니다! 95a353b

2022-10-20 02:02 UTC, CreoHwan commented on Samsam/Base.lproj/Main.storyboard
> +<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="21225" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitColle
넵! 감사합니다!

2022-10-20 02:14 UTC, creohwan commented on Samsam/ViewController/CategoryCell.swift
> +                        self.categoryImage.image = UIImage(named:"category1")
넵! 꿀팁 감사합니다! c6c0cf8

2022-10-20 03:42 UTC, taek0622 commented on .gitignore
> +Samsam/Global/SceneDelegate.swift
> 해결했습니다! [[e4a5883](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/e4a5883fadd4a4b9f6086579845221fd1ea40475)]

확인했습니다. 리뷰 리졸브합니다.

2022-10-20 03:43 UTC, taek0622 commented on Samsam/Global/SceneDelegate.swift
> +        let navi = UINavigationController(rootViewController: PostingCategoryViewController())
> 해결했습니다! [[67ff338](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/67ff3380aa87098f6cb33fde7f7b46ac9aafc8dd)]

확인했습니다. 다만, 해당 커밋은 커밋 타입이 Docs:books:가 아니라 Chore:wrench:가 더 어울릴 것 같습니다.

2022-10-20 03:46 UTC, taek0622 commented on Samsam/ViewController/CategoryCell.swift
> +                        self.categoryImage.image = UIImage(named:"category1")
> 넵! 꿀팁 감사합니다! [c6c0cf8](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/c6c0cf85ef5eec886306c79d2b920a8edb9bd9db)

확인했습니다. 다만 ImageLiteral은 셀 안이 아니라 Global로 빼주시는 것이 다른 곳에서도 접근할 수 있어서 더 좋을 것 같습니다.

2022-10-20 03:46 UTC, taek0622 commented on Samsam/ViewController/CategoryCell.swift
> +        $0.image = UIImage(named: "")
> 감사합니다! 해결했습니다! [a3cb180](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/a3cb1803e4ff628ea68a840d898fe1d1d8c3adf3)

확인했습니다. 해당 리뷰 리졸브 하겠습니다.

2022-10-20 03:47 UTC, taek0622 commented on Samsam/ViewController/CategoryCell.swift
> +    }
> 감사합니다! 해결했습니다! [e7ad9c1](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/e7ad9c1678c830cb24507334b9fbdee55d0b3156)

vStack도 setupCell 안으로 옮겨주시고 layout은 아예 삭제하는게 더 좋을 것 같습니다~

2022-10-20 03:47 UTC, taek0622 commented on Samsam/ViewController/PostingCategoryViewController.swift
> +
> 넵! 감사합니다! [c9d9aa0](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/c9d9aa0bda988300d58bf4669af8db912c19af31)

확인했습니다. 해당 리뷰 리졸브합니다.

2022-10-20 03:48 UTC, taek0622 commented on Samsam/ViewController/PostingCategoryViewController.swift
> +
> 넵! 감사합니다! [c9d9aa0](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/c9d9aa0bda988300d58bf4669af8db912c19af31)

확인했습니다. 해당 리뷰 리졸브합니다.

2022-10-20 03:48 UTC, ikanic commented on Samsam/ViewController/PostingCategoryViewController.swift
> +            right: view.rightAnchor
> 넵! 감사합니다! [95a353b](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/95a353bd4e18c68659c174652df13404824f2609)

확인했습니다. 해당 리뷰 리졸브합니다.

2022-10-20 03:49 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +
> 넵! 감사합니다! [c9d9aa0](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/c9d9aa0bda988300d58bf4669af8db912c19af31)

확인했습니다. 해당 리뷰 리졸브합니다.

2022-10-20 06:55 UTC, CreoHwan commented on Samsam/Global/SceneDelegate.swift
> +        let navi = UINavigationController(rootViewController: PostingCategoryViewController())
> > 해결했습니다! [[67ff338](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/67ff3380aa87098f6cb33fde7f7b46ac9aafc8dd)]
> 
> 확인했습니다. 다만, 해당 커밋은 커밋 타입이 Docs📚가 아니라 Chore🔧가 더 어울릴 것 같습니다.

넵~ 변경했습니다~ 감사합니다~

2022-10-20 06:56 UTC, CreoHwan commented on Samsam/ViewController/CategoryCell.swift
> +                        self.categoryImage.image = UIImage(named:"category1")
> > 넵! 꿀팁 감사합니다! [c6c0cf8](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/c6c0cf85ef5eec886306c79d2b920a8edb9bd9db)
> 
> 확인했습니다. 다만 ImageLiteral은 셀 안이 아니라 Global로 빼주시는 것이 다른 곳에서도 접근할 수 있어서 더 좋을 것 같습니다.

넵! 다음에 이미지 리터럴 함께 사용할 일 있다면 호다닥 만들도록 하겠습니다!

2022-10-20 06:59 UTC, CreoHwan commented on Samsam/ViewController/CategoryCell.swift
> +    }
> > 감사합니다! 해결했습니다! [e7ad9c1](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/e7ad9c1678c830cb24507334b9fbdee55d0b3156)
> 
> vStack도 setupCell 안으로 옮겨주시고 layout은 아예 삭제하는게 더 좋을 것 같습니다~

감사합니다! 바꿨습니다! 7bca4b7

2022-10-20 07:46 UTC, CreoHwan commented
@taek0622 확인 부탁드립니다~

2022-10-20 08:46 UTC, taek0622 commented on Samsam/Global/SceneDelegate.swift
> +        let navi = UINavigationController(rootViewController: PostingCategoryViewController())
> > > 해결했습니다! [[67ff338](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/67ff3380aa87098f6cb33fde7f7b46ac9aafc8dd)]
> > 
> > 
> > 확인했습니다. 다만, 해당 커밋은 커밋 타입이 Docs📚가 아니라 Chore🔧가 더 어울릴 것 같습니다.
> 
> 넵~ 변경했습니다~ 감사합니다~

확인했습니다. 해당 리뷰 리졸브합니다.

2022-10-20 08:47 UTC, ikanic commented on Samsam/ViewController/CategoryCell.swift
> +    }
> > > 감사합니다! 해결했습니다! [e7ad9c1](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/e7ad9c1678c830cb24507334b9fbdee55d0b3156)
> > 
> > 
> > vStack도 setupCell 안으로 옮겨주시고 layout은 아예 삭제하는게 더 좋을 것 같습니다~
> 
> 감사합니다! 바꿨습니다! [7bca4b7](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/7bca4b722c8983f8945638039fba609f46ae32e0)

확인했습니다. 해당 리뷰 리졸브합니다.

2022-10-20 09:08 UTC, taek0622 requested changes
고생하셨습니다.
추가로 수정사항 몇가지 리뷰했습니다. 확인 부탁드려요.

2022-10-20 09:08 UTC, ikanic commented on Samsam/ViewController/CategoryCell.swift
> +        $0.font = UIFont.systemFont(ofSize: 16, weight: .bold)
p2;
figma 상으로 현재 이 부분은 bold가 아니라 semibold로 되어있습니다.
아직 디자인이 확정되지 않은 상황이지만 우선은 피그마에 맞게 semibold로 맞춰주시면 좋을 것 같습니다.

2022-10-20 09:08 UTC, ikanic commented on Samsam/ViewController/CategoryCell.swift
> +        $0.backgroundColor = .white
p2;
이미 배경에 색이 따로 들어가있기 때문에 collectionview의 cell에는 배경색을 따로 주지 않는 쪽이 더 좋을 것 같습니다.

2022-10-20 09:08 UTC, taek0622 commented on Samsam/ViewController/PostingCategoryViewController.swift
> +        return true
p2;
어떻게 해도 return true라면 굳이 if문 안에 return true가 있을 이유가 있을까요?

2022-10-20 09:08 UTC, taek0622 commented on Samsam/ViewController/PostingCategoryViewController.swift
> +        return true
p2;
마찬가지로 어떻게 해도 return true라면 굳이 if문 안에서는 return true가 필요없을 것 같습니다.

2022-10-21 00:52 UTC, CreoHwan commented on Samsam/ViewController/CategoryCell.swift
> +        $0.font = UIFont.systemFont(ofSize: 16, weight: .bold)
> p2; figma 상으로 현재 이 부분은 bold가 아니라 semibold로 되어있습니다. 아직 디자인이 확정되지 않은 상황이지만 우선은 피그마에 맞게 semibold로 맞춰주시면 좋을 것 같습니다.

넵! 감사합니다! f1fa88c

2022-10-21 00:52 UTC, CreoHwan commented on Samsam/ViewController/CategoryCell.swift
> +        $0.backgroundColor = .white
> p2; 이미 배경에 색이 따로 들어가있기 때문에 collectionview의 cell에는 배경색을 따로 주지 않는 쪽이 더 좋을 것 같습니다.

그렇군요! 감사합니다! f1fa88c

2022-10-21 00:52 UTC, CreoHwan commented on Samsam/ViewController/PostingCategoryViewController.swift
> +        return true
> p2; 어떻게 해도 return true라면 굳이 if문 안에 return true가 있을 이유가 있을까요?

감사합니다! 82786a2

2022-10-21 00:52 UTC, CreoHwan commented on Samsam/ViewController/PostingCategoryViewController.swift
> +        return true
> p2; 마찬가지로 어떻게 해도 return true라면 굳이 if문 안에서는 return true가 필요없을 것 같습니다.

감사합니다! 82786a2

2022-10-21 00:57 UTC, CreoHwan commented
@taek0622 확인부탁드려요! :)

2022-10-21 01:47 UTC, taek0622 commented on Samsam/ViewController/CategoryCell.swift
> +        $0.font = UIFont.systemFont(ofSize: 16, weight: .bold)
> > p2; figma 상으로 현재 이 부분은 bold가 아니라 semibold로 되어있습니다. 아직 디자인이 확정되지 않은 상황이지만 우선은 피그마에 맞게 semibold로 맞춰주시면 좋을 것 같습니다.
> 
> 넵! 감사합니다! [f1fa88c](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/f1fa88cdf6c7b5cf330a8c28b1def7b1175f23fc)

확인했습니다. 리뷰 리졸브합니다.

2022-10-21 01:48 UTC, ikanic commented on Samsam/ViewController/PostingCategoryViewController.swift
> +        return true
> > p2; 어떻게 해도 return true라면 굳이 if문 안에 return true가 있을 이유가 있을까요?
> 
> 감사합니다! [82786a2](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/82786a2a8d9d70e558d5ee6840578032c69394a0)

확인했습니다. 리뷰 리졸브 하겠습니다.

2022-10-21 01:48 UTC, ikanic commented on Samsam/ViewController/PostingCategoryViewController.swift
> +        return true
> > p2; 마찬가지로 어떻게 해도 return true라면 굳이 if문 안에서는 return true가 필요없을 것 같습니다.
> 
> 감사합니다! [82786a2](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/82786a2a8d9d70e558d5ee6840578032c69394a0)

확인했습니다. 리뷰 리졸브합니다.

2022-10-21 01:49 UTC, taek0622 commented on Samsam/ViewController/CategoryCell.swift
> +        $0.backgroundColor = .white
> > p2; 이미 배경에 색이 따로 들어가있기 때문에 collectionview의 cell에는 배경색을 따로 주지 않는 쪽이 더 좋을 것 같습니다.
> 
> 그렇군요! 감사합니다! [f1fa88c](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/f1fa88cdf6c7b5cf330a8c28b1def7b1175f23fc)

확인했습니다. 리뷰 리졸브합니다.

2022-10-21 01:51 UTC, ikanic approved these changes
고생하셨습니다.
오랜 시간 한 PR 수정하셨는데, 정말 고생 많으셨어요~

2022-10-21 01:51 UTC, taek0622 commented on Samsam/ViewController/CategoryCell.swift
> +        $0.translatesAutoresizingMaskIntoConstraints = false
p4;
이미 `anchor`에 같은 기능이 포함되어 있습니다.
해당 부분은 삭제하셔도 될 것 같습니다.

2022-10-21 01:53 UTC, CreoHwan commented on Samsam/ViewController/CategoryCell.swift
> +        $0.translatesAutoresizingMaskIntoConstraints = false
> p4; 이미 `anchor`에 같은 기능이 포함되어 있습니다. 해당 부분은 삭제하셔도 될 것 같습니다.

감사합니다! 749bb8b

2022-10-21 01:53 UTC, merged