[Design] 시공상황 작성 텍스트 뷰 Layout 생성
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #31
Opened 2022-10-20 07:37 UTC by CreoHwan

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 시공상황 작성 텍스트 뷰 Layout 생성

## Key Changes 🔥 (주요 구현/변경 사항)
- 작성 완료 버튼 만들기
- TextView PlaceHolder 만들기
- 텍스트 작성 중, 다른 곳 클릭 시, 키보드 내려가기
- NavigationBar 만들기

## ToDo 📆 (남은 작업)
- [ ] 서버와의 연결 준비

## ScreenShot 📷 (참고 사진)
![Simulator Screen Recording - iPhone 14 - 2022-10-20 at 16 34 15](https://user-images.githubusercontent.com/92836045/196885610-dd3c0fab-bb2f-4aca-a662-d978861a83f0.gif)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 화이팅입니다! 빡센 리뷰 환영입니다!
- 
## Reference 🔗

## Close Issues 🔒 (닫을 Issue)
Close #23

2022-10-20 09:20 UTC, taek0622 requested changes
고생하셨습니다.
수정 필요한 부분 리뷰했으니 확인 부탁드려요~

2022-10-20 09:20 UTC, taek0622 commented on Samsam/Samsam.entitlements
> +<dict/>
p1;
해당 부분은 PR에 포함되면 안될 것 같습니다.
이 부분이 없으면 애플 로그인 기능 및 버튼 모양이 전혀 나오지 않게 됩니다.

2022-10-20 09:20 UTC, ikanic commented on Samsam/ViewController/PostingWritingView.swift
> +    lazy var textContent: UITextView = {
p2;
해당 컴포넌트가 외부에서 사용될 일이 없다면 private으로 접근지정자를 붙여주는 것이 좋을 것 같습니다.

2022-10-20 09:20 UTC, ikanic commented on Samsam/ViewController/PostingWritingView.swift
> +        $0.layer.shadowOpacity = 0.2
p2;
현재 피그마 상의 모든 그림자는 투명도가 0.25로 지정되어 있습니다.
이 부분 맞춰주시면 좋을 것 같습니다.

2022-10-20 09:20 UTC, ikanic commented on Samsam/ViewController/PostingWritingView.swift
> +    private let finalBtn: UIButton = {
p2;
변수명 약어 컨벤션을 지켜주세요~
약어로 시작하는 경우 소문자로 표기하고, 그 외의 경우 약어는 모두 대문자로 표기하는 컨벤션이 있습니다.
해당 부분 아래에 레퍼런스로 첨부합니다.

- [약어 컨벤션](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/wiki/Swift-Code-Convention#%EC%95%BD%EC%96%B4)

2022-10-20 09:20 UTC, taek0622 commented on Samsam/ViewController/PostingWritingView.swift
> +            right: view.rightAnchor,
p2;
특별한 이유가 없다면 left와 right anchor는 view가 아니라 safeAreaLayoutGuide에 지정해주시는 것이 더 좋을 것 같습니다.

2022-10-20 09:20 UTC, taek0622 commented on Samsam/ViewController/PostingWritingView.swift
> +            right: view.rightAnchor,
p2;
마찬가지로 특별한 이유가 있어서 view에 anchor를 잡으신 것이 아니라면 safeAreaLayoutGuide에 anchor를 지정해주시는 것이 더 좋을 것 같습니다.

2022-10-20 09:20 UTC, taek0622 commented on Samsam/ViewController/PostingWritingView.swift
> +    @objc func tapNextBtn(_sender: UIButton) {
p2;
약어 컨벤션을 지켜주시면 좋을 것 같습니다~

2022-10-20 09:20 UTC, taek0622 commented on Samsam/ViewController/PostingWritingView.swift
> +        }
p2;
이 부분 인덴트가 이상하게 적용되고 있는 것 같습니다.

2022-10-20 10:02 UTC, JUNY0110 requested changes
고생하셨습니다
자잘한 컨벤션 관련된 내용만 지켜주시면 될 것 같습니다~

2022-10-20 10:02 UTC, JUNY0110 commented on Samsam/ViewController/PostingWritingView.swift
> +    let textViewPlaceHolder = "텍스트를 입력하세요"
P2.
textViewPlaceHolder는 Property이니 View 위에 따로 MARK: - Property로 구분하는 컨벤션이 있습니다~

2022-10-20 10:02 UTC, JUNY0110 commented on Samsam/ViewController/PostingWritingView.swift
> +    }
p2.
들여쓰기가 잘못 잡혀있는 것 같습니다.

2022-10-20 10:02 UTC, JUNY0110 commented on Samsam/ViewController/PostingWritingView.swift
> +        }(UIButton())
p2.
들여쓰기가 잘못되어있습니다. 
Ctrl + i를 하시면 편하게 정렬 가능합니다.

2022-10-20 10:02 UTC, JUNY0110 commented on Samsam/ViewController/PostingWritingView.swift
> +    }(UITextView())
Q1.
typingAttribute가 있는 이유가 무엇일까요? 
typingAttribute가 필요없다면 LineStyle도 삭제가능할 것 같습니다.

Q2.
autocapitalizationType을 None으로 한 이유는 무엇일까요?

2022-10-20 10:02 UTC, JUNY0110 commented on Samsam/ViewController/PostingWritingView.swift
> +            navigationController?.navigationBar.backgroundColor = .white
Q.
저는 NavigationBar가 원래 흰색이라고 생각했는데, white가 아니었을까요?

2022-10-21 01:30 UTC, creohwan commented on Samsam/ViewController/PostingWritingView.swift
> +    lazy var textContent: UITextView = {
> p2; 해당 컴포넌트가 외부에서 사용될 일이 없다면 private으로 접근지정자를 붙여주는 것이 좋을 것 같습니다.

감사합니다! 32aa853

2022-10-21 01:30 UTC, creohwan commented on Samsam/ViewController/PostingWritingView.swift
> +    let textViewPlaceHolder = "텍스트를 입력하세요"
> P2. textViewPlaceHolder는 Property이니 View 위에 따로 MARK: - Property로 구분하는 컨벤션이 있습니다~

감사합니다! 32aa853

2022-10-21 01:32 UTC, CreoHwan commented on Samsam/ViewController/PostingWritingView.swift
> +        $0.layer.shadowOpacity = 0.2
> p2; 현재 피그마 상의 모든 그림자는 투명도가 0.25로 지정되어 있습니다. 이 부분 맞춰주시면 좋을 것 같습니다.

피그마에서 확인을 안하고 제가 했습니다 ㅜ 담부터 주의하겠습니다~ 4bfc67f

2022-10-21 01:33 UTC, CreoHwan commented on Samsam/ViewController/PostingWritingView.swift
> +    private let finalBtn: UIButton = {
> p2; 변수명 약어 컨벤션을 지켜주세요~ 약어로 시작하는 경우 소문자로 표기하고, 그 외의 경우 약어는 모두 대문자로 표기하는 컨벤션이 있습니다. 해당 부분 아래에 레퍼런스로 첨부합니다.
> 
> * [약어 컨벤션](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/wiki/Swift-Code-Convention#%EC%95%BD%EC%96%B4)

주의하겠습니다! 감사합니다! 6428b77

2022-10-21 01:34 UTC, CreoHwan commented on Samsam/ViewController/PostingWritingView.swift
> +            right: view.rightAnchor,
> p2; 특별한 이유가 없다면 left와 right anchor는 view가 아니라 safeAreaLayoutGuide에 지정해주시는 것이 더 좋을 것 같습니다.

감사합니다! 6a36efb

2022-10-21 01:35 UTC, CreoHwan commented on Samsam/ViewController/PostingWritingView.swift
> +            right: view.rightAnchor,
> p2; 마찬가지로 특별한 이유가 있어서 view에 anchor를 잡으신 것이 아니라면 safeAreaLayoutGuide에 anchor를 지정해주시는 것이 더 좋을 것 같습니다.

감사합니다! 6a36efb

2022-10-21 01:36 UTC, CreoHwan commented on Samsam/ViewController/PostingWritingView.swift
> +    @objc func tapNextBtn(_sender: UIButton) {
> p2; 약어 컨벤션을 지켜주시면 좋을 것 같습니다~

넵! 감사합니다!~ d9ac4c2

2022-10-21 01:37 UTC, CreoHwan commented on Samsam/ViewController/PostingWritingView.swift
> +    }
> p2. 들여쓰기가 잘못 잡혀있는 것 같습니다.

감사합니다! 3e980b4

2022-10-21 01:37 UTC, creohwan commented on Samsam/ViewController/PostingWritingView.swift
> +        }(UIButton())
> p2. 들여쓰기가 잘못되어있습니다. Ctrl + i를 하시면 편하게 정렬 가능합니다.

헐~ 꿀팁 감사합니다! 3e980b4

2022-10-21 01:38 UTC, CreoHwan commented on Samsam/ViewController/PostingWritingView.swift
> +        }
> p2; 이 부분 인덴트가 이상하게 적용되고 있는 것 같습니다.

감사합니다! 3e980b4

2022-10-21 01:40 UTC, CreoHwan commented on Samsam/ViewController/PostingWritingView.swift
> +    }(UITextView())
> Q1. typingAttribute가 있는 이유가 무엇일까요? typingAttribute가 필요없다면 LineStyle도 삭제가능할 것 같습니다.
> 
> Q2. autocapitalizationType을 None으로 한 이유는 무엇일까요?

A1: 글자 사이 간격을 조절하기 위해서 만들었습니다!

A2: 영어일 경우, 첫 시작을 대문자가 아닌 소문자로 하기 위해서 만들었습니다!

2022-10-21 01:43 UTC, CreoHwan commented on Samsam/ViewController/PostingWritingView.swift
> +            navigationController?.navigationBar.backgroundColor = .white
> Q. 저는 NavigationBar가 원래 흰색이라고 생각했는데, white가 아니었을까요?

A: 꿀팁 감사합니다! 5b05fd4

2022-10-21 01:48 UTC, CreoHwan commented on Samsam/Samsam.entitlements
> +<dict/>
> p1; 해당 부분은 PR에 포함되면 안될 것 같습니다. 이 부분이 없으면 애플 로그인 기능 및 버튼 모양이 전혀 나오지 않게 됩니다.

감사합니다! 49f1a41

2022-10-21 01:52 UTC, taek0622 commented on Samsam/Samsam.entitlements
> +<dict/>
> > p1; 해당 부분은 PR에 포함되면 안될 것 같습니다. 이 부분이 없으면 애플 로그인 기능 및 버튼 모양이 전혀 나오지 않게 됩니다.
> 
> 감사합니다! [49f1a41](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/49f1a4152ee4303618e41e9fe550c816b8bc25f8)

확인했습니다. 리뷰 리졸브 합니다.

2022-10-21 01:53 UTC, taek0622 commented on Samsam/ViewController/PostingWritingView.swift
> +        $0.layer.shadowOpacity = 0.2
> > p2; 현재 피그마 상의 모든 그림자는 투명도가 0.25로 지정되어 있습니다. 이 부분 맞춰주시면 좋을 것 같습니다.
> 
> 피그마에서 확인을 안하고 제가 했습니다 ㅜ 담부터 주의하겠습니다~ [4bfc67f](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/4bfc67f1bb0185efac9a45007a294113760c790c)

확인했습니다. 해당 리뷰 리졸브합니다.

2022-10-21 01:53 UTC, taek0622 commented on Samsam/ViewController/PostingWritingView.swift
> +            right: view.rightAnchor,
> > p2; 특별한 이유가 없다면 left와 right anchor는 view가 아니라 safeAreaLayoutGuide에 지정해주시는 것이 더 좋을 것 같습니다.
> 
> 감사합니다! [6a36efb](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/6a36efb040346d085701605f96acac0f80829555)

확인했습니다. 해당 리뷰 리졸브합니다.

2022-10-21 01:55 UTC, taek0622 commented on Samsam/ViewController/PostingWritingView.swift
> +    private let finalBtn: UIButton = {
> > p2; 변수명 약어 컨벤션을 지켜주세요~ 약어로 시작하는 경우 소문자로 표기하고, 그 외의 경우 약어는 모두 대문자로 표기하는 컨벤션이 있습니다. 해당 부분 아래에 레퍼런스로 첨부합니다.
> > 
> > * [약어 컨벤션](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/wiki/Swift-Code-Convention#%EC%95%BD%EC%96%B4)
> 
> 주의하겠습니다! 감사합니다! [6428b77](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/6428b775d88c06fc79defc4c5ddcf861abeeb446)

p2;
btn은 소문자가 아닌, 대문자로 BTN을 쓰시거나 Button으로 바꿔주시는 것이 좋을 것 같습니다.

2022-10-21 01:56 UTC, taek0622 commented on Samsam/ViewController/PostingWritingView.swift
> +            right: view.rightAnchor,
> > p2; 마찬가지로 특별한 이유가 있어서 view에 anchor를 잡으신 것이 아니라면 safeAreaLayoutGuide에 anchor를 지정해주시는 것이 더 좋을 것 같습니다.
> 
> 감사합니다! [6a36efb](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/6a36efb040346d085701605f96acac0f80829555)

확인했습니다. 해당 리뷰 리졸브합니다.

2022-10-21 01:57 UTC, taek0622 commented on Samsam/ViewController/PostingWritingView.swift
> +    @objc func tapNextBtn(_sender: UIButton) {
> > p2; 약어 컨벤션을 지켜주시면 좋을 것 같습니다~
> 
> 넵! 감사합니다!~ [d9ac4c2](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/d9ac4c29f5673e3bfff0737645db13e52786607a)

p2;
약어 컨벤션상 뒤에 오는 btn은 소문자가 아닌, 대문자로 BTN을 쓰시거나 Button으로 바꿔주시는 것이 좋을 것 같습니다.

2022-10-21 01:57 UTC, taek0622 commented on Samsam/ViewController/PostingWritingView.swift
> +        }
> > p2; 이 부분 인덴트가 이상하게 적용되고 있는 것 같습니다.
> 
> 감사합니다! [3e980b4](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/3e980b4121ff39daf4632c1367f2b98655f0c581)

확인했습니다. 해당 리뷰 리졸브합니다.

2022-10-21 01:58 UTC, taek0622 commented on Samsam/ViewController/PostingWritingView.swift
> +    lazy var textContent: UITextView = {
> > p2; 해당 컴포넌트가 외부에서 사용될 일이 없다면 private으로 접근지정자를 붙여주는 것이 좋을 것 같습니다.
> 
> 감사합니다! [32aa853](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/32aa8536b919514f0da1286ed3e8e44ff0054b0e)

priavate이 빠져있는 컴포넌트가 남아있는 것 같습니다. 다시 확인하시고 수정 부탁드려요~

2022-10-21 02:09 UTC, JUNY0110 commented on Samsam/ViewController/PostingWritingView.swift
> +    }(UITextView())
> > Q1. typingAttribute가 있는 이유가 무엇일까요? typingAttribute가 필요없다면 LineStyle도 삭제가능할 것 같습니다.
> > Q2. autocapitalizationType을 None으로 한 이유는 무엇일까요?
> 
> A1: 글자 사이 간격을 조절하기 위해서 만들었습니다!
> 
> A2: 영어일 경우, 첫 시작을 대문자가 아닌 소문자로 하기 위해서 만들었습니다!

Q1. 
글자 사이간격(lineSpacing)의 기본값이 어떻게 될까요?? 
코드를 지워봐도 차이가 잘 안 느껴져서 질문 남깁니다.

2022-10-22 06:43 UTC, CreoHwan commented on Samsam/ViewController/PostingWritingView.swift
> +    lazy var textContent: UITextView = {
> > > p2; 해당 컴포넌트가 외부에서 사용될 일이 없다면 private으로 접근지정자를 붙여주는 것이 좋을 것 같습니다.
> > 
> > 
> > 감사합니다! [32aa853](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/32aa8536b919514f0da1286ed3e8e44ff0054b0e)
> 
> p2; 여전히 priavate이 빠져있는 컴포넌트가 남아있는 것 같습니다. 다시 확인하시고 수정 부탁드려요~

앗! private 안 쓴 곳이 2곳이었군요! 담부터 더욱 꼼꼼히 보겠습니다! fd9ba58

2022-10-22 06:45 UTC, CreoHwan commented on Samsam/ViewController/PostingWritingView.swift
> +    private let finalBtn: UIButton = {
> > > p2; 변수명 약어 컨벤션을 지켜주세요~ 약어로 시작하는 경우 소문자로 표기하고, 그 외의 경우 약어는 모두 대문자로 표기하는 컨벤션이 있습니다. 해당 부분 아래에 레퍼런스로 첨부합니다.
> > > 
> > > * [약어 컨벤션](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/wiki/Swift-Code-Convention#%EC%95%BD%EC%96%B4)
> > 
> > 
> > 주의하겠습니다! 감사합니다! [6428b77](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/6428b775d88c06fc79defc4c5ddcf861abeeb446)
> 
> p2; btn은 소문자가 아닌, 대문자로 BTN을 쓰시거나 Button으로 바꿔주시는 것이 좋을 것 같습니다.

죄송합니다! 담부터 더욱 꼼꼼하게 하겠습니다! 57c1b25

2022-10-22 06:52 UTC, CreoHwan commented on Samsam/ViewController/PostingWritingView.swift
> +    @objc func tapNextBtn(_sender: UIButton) {
> > > p2; 약어 컨벤션을 지켜주시면 좋을 것 같습니다~
> > 
> > 
> > 넵! 감사합니다!~ [d9ac4c2](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/d9ac4c29f5673e3bfff0737645db13e52786607a)
> 
> p2; 약어 컨벤션상 뒤에 오는 btn은 소문자가 아닌, 대문자로 BTN을 쓰시거나 Button으로 바꿔주시는 것이 좋을 것 같습니다.

다음부터 더욱 신경쓰겠습니다! 감사합니다! 8cb6683

2022-10-22 07:16 UTC, CreoHwan commented on Samsam/ViewController/PostingWritingView.swift
> +    }(UITextView())
> > > Q1. typingAttribute가 있는 이유가 무엇일까요? typingAttribute가 필요없다면 LineStyle도 삭제가능할 것 같습니다.
> > > Q2. autocapitalizationType을 None으로 한 이유는 무엇일까요?
> > 
> > 
> > A1: 글자 사이 간격을 조절하기 위해서 만들었습니다!
> > A2: 영어일 경우, 첫 시작을 대문자가 아닌 소문자로 하기 위해서 만들었습니다!
> 
> Q1. 글자 사이간격(lineSpacing)의 기본값이 어떻게 될까요?? 코드를 지워봐도 차이가 잘 안 느껴져서 질문 남깁니다.

A1. 0으로 확인되었습니다! 저도 지우고 값을 넣어봐도 큰 차이는 느껴지지 않는게 보이더라고요.

2022-10-22 07:31 UTC, CreoHwan commented on Samsam/ViewController/PostingWritingView.swift
> +    }(UITextView())
> > > > Q1. typingAttribute가 있는 이유가 무엇일까요? typingAttribute가 필요없다면 LineStyle도 삭제가능할 것 같습니다.
> > > > Q2. autocapitalizationType을 None으로 한 이유는 무엇일까요?
> > > 
> > > 
> > > A1: 글자 사이 간격을 조절하기 위해서 만들었습니다!
> > > A2: 영어일 경우, 첫 시작을 대문자가 아닌 소문자로 하기 위해서 만들었습니다!
> > 
> > 
> > Q1. 글자 사이간격(lineSpacing)의 기본값이 어떻게 될까요?? 코드를 지워봐도 차이가 잘 안 느껴져서 질문 남깁니다.
> 
> A1. 기본값 0으로 확인되었습니다! 저도 지우고 값을 넣어봐도 큰 차이는 느껴지지 않는게 보이더라고요.
> 
> <img alt="스크린샷 2022-10-22 16 15 23" width="137" src="https://user-images.githubusercontent.com/92836045/197326105-aae13c9d-3756-4df2-a91c-2d5375915ec0.png">
> 
> <img alt="스크린샷 2022-10-22 16 15 59" width="126" src="https://user-images.githubusercontent.com/92836045/197326112-e73cee59-ff4f-4d23-ac6d-24e73ad4e8ae.png">
> 
> 하지만 값은 바뀌는 것은 확인 되었습니다. 값은 변하지만 왜 적용이 안 되는지 조금 더 연구해보겠습니다~

d703d3c 
linespacing이 정확히는 줄 사이 간격입니다! 제가 text를 넣고 나서 변경하여, 눈에 보이는 변화가 없었던 것 같습니다. 

변경 전 코드 및 사진(기본 값 0)
<img width="524" alt="변경 전 코드" src="https://user-images.githubusercontent.com/92836045/197326495-90e2732a-9376-4a3c-b50e-f564fc35aff5.png">

<img width="341" alt="변경 전 0" src="https://user-images.githubusercontent.com/92836045/197326501-bbf65278-6cc3-4136-9739-6d137d7d0f5b.png">

변경 후 코드 및 사진(변경 값 4)
<img width="524" alt="변경 후 코드" src="https://user-images.githubusercontent.com/92836045/197326525-83b7dfb4-4f41-4fea-b51b-92aa6a9c83bf.png">

<img width="365" alt="4 0" src="https://user-images.githubusercontent.com/92836045/197326530-cd46712d-044d-4077-8ed0-cb6146bbd50f.png">

이번에는 처음이라서 일단 구현하자는 마음이 컸던 것 같습니다. 다음부터는 천천히 하나씩 정확히 구현하도록 노력하겠습니다. linespacing에 관하여서는 추후에 어떤 값을 줘야할 지 함께 이야기해봐야 할 것 같습니다!

2022-10-22 07:32 UTC, CreoHwan commented
@taek0622 @JUNY0110 확인부탁드립니다!

2022-10-22 09:48 UTC, taek0622 commented on Samsam/ViewController/PostingWritingView.swift
> +    lazy var textContent: UITextView = {
> > > > p2; 해당 컴포넌트가 외부에서 사용될 일이 없다면 private으로 접근지정자를 붙여주는 것이 좋을 것 같습니다.
> > > 
> > > 
> > > 감사합니다! [32aa853](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/32aa8536b919514f0da1286ed3e8e44ff0054b0e)
> > 
> > 
> > p2; 여전히 priavate이 빠져있는 컴포넌트가 남아있는 것 같습니다. 다시 확인하시고 수정 부탁드려요~
> 
> 앗! private 안 쓴 곳이 2곳이었군요! 담부터 더욱 꼼꼼히 보겠습니다! [fd9ba58](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/fd9ba582ca8b6e750d99e876213e227cc8b6f0d1)

확인했습니다. 리뷰 리졸브합니다~

2022-10-22 09:48 UTC, taek0622 commented on Samsam/ViewController/PostingWritingView.swift
> +    @objc func tapNextBtn(_sender: UIButton) {
> > > > p2; 약어 컨벤션을 지켜주시면 좋을 것 같습니다~
> > > 
> > > 
> > > 넵! 감사합니다!~ [d9ac4c2](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/d9ac4c29f5673e3bfff0737645db13e52786607a)
> > 
> > 
> > p2; 약어 컨벤션상 뒤에 오는 btn은 소문자가 아닌, 대문자로 BTN을 쓰시거나 Button으로 바꿔주시는 것이 좋을 것 같습니다.
> 
> 다음부터 더욱 신경쓰겠습니다! 감사합니다! [8cb6683](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/8cb66834bf71949f7ff40c3b30ed138dca644a61)

확인했습니다. 리뷰 리졸브합니다~

2022-10-22 09:49 UTC, taek0622 commented on Samsam/ViewController/PostingWritingView.swift
> +    private let finalBtn: UIButton = {
> > > > p2; 변수명 약어 컨벤션을 지켜주세요~ 약어로 시작하는 경우 소문자로 표기하고, 그 외의 경우 약어는 모두 대문자로 표기하는 컨벤션이 있습니다. 해당 부분 아래에 레퍼런스로 첨부합니다.
> > > > 
> > > > * [약어 컨벤션](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/wiki/Swift-Code-Convention#%EC%95%BD%EC%96%B4)
> > > 
> > > 
> > > 주의하겠습니다! 감사합니다! [6428b77](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/6428b775d88c06fc79defc4c5ddcf861abeeb446)
> > 
> > 
> > p2; btn은 소문자가 아닌, 대문자로 BTN을 쓰시거나 Button으로 바꿔주시는 것이 좋을 것 같습니다.
> 
> 죄송합니다! 담부터 더욱 꼼꼼하게 하겠습니다! [57c1b25](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/57c1b2569a64622dcf3e1ba3142bc1bbc0b4fef0)

확인했습니다. 리뷰 리졸브합니다~

2022-10-22 10:51 UTC, taek0622 approved these changes
고생하셨습니다.
꽤 어려워보이는 코드가 몇부분 있는데 이 부분에 대해서는 개인적으로 공부해봐야겠네요.

2022-10-24 02:02 UTC, JUNY0110 commented on Samsam/ViewController/PostingWritingView.swift
> +    }(UITextView())
> 
> [d703d3c](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/d703d3c3ee97e71d78cd04951c671f9359bcfa7a) linespacing이 정확히는 줄 사이 간격입니다! 제가 text를 넣고 나서 변경하여, 눈에 보이는 변화가 없었던 것 같습니다.
> 
> 변경 전 코드 및 사진(기본 값 0) <img alt="변경 전 코드" width="524" src="https://user-images.githubusercontent.com/92836045/197326495-90e2732a-9376-4a3c-b50e-f564fc35aff5.png">
> 
> <img alt="변경 전 0" width="341" src="https://user-images.githubusercontent.com/92836045/197326501-bbf65278-6cc3-4136-9739-6d137d7d0f5b.png">
> 
> 변경 후 코드 및 사진(변경 값 4) <img alt="변경 후 코드" width="524" src="https://user-images.githubusercontent.com/92836045/197326525-83b7dfb4-4f41-4fea-b51b-92aa6a9c83bf.png">
> 
> <img alt="4 0" width="365" src="https://user-images.githubusercontent.com/92836045/197326530-cd46712d-044d-4077-8ed0-cb6146bbd50f.png">
> 
> 이번에는 처음이라서 일단 구현하자는 마음이 컸던 것 같습니다. 다음부터는 천천히 하나씩 정확히 구현하도록 노력하겠습니다. linespacing에 관하여서는 추후에 어떤 값을 줘야할 지 함께 이야기해봐야 할 것 같습니다!

굿굿 감사합니다!

2022-10-24 02:04 UTC, JUNY0110 approved these changes
고생하셨습니다! 좋은 인사이트가 되는 것들이 많네요

2022-10-24 05:56 UTC, merged