[Feature] 세부사항 뷰(DetailView) 공유기능 추가
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #41
Opened 2022-10-20 14:46 UTC by JUNY0110

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 테스트 플라이트를 위한 임시 공유기능

## Key Changes 🔥 (주요 구현/변경 사항)
- 공유기능 추가
- plist 사진 라이브러리 접근권한 설명 추가

## ToDo 📆 (남은 작업)
- [ ] 공유기능 삭제
- [ ] 이미지 클릭 시 이미지뷰로 이동

## ScreenShot 📷 (참고 사진)

https://user-images.githubusercontent.com/98405970/196980780-dde07166-8bdc-4317-b666-9667a47d229f.mp4

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 코드가 상당히 저급합니다. 
- 노약자, 심신미약, 임산부는 시청을 자제바랍니다.
- 반복문을 이용해 변수명을 수정하는 방법이 있을까요? 있다면 해결할 수 있을 것 같습니다.

## Reference 🔗
공유하기 기능 참고자료: https://www.youtube.com/watch?v=jxhq1_7HkJg&t=674s

## Close Issues 🔒 (닫을 Issue)
Close #29

2022-10-20 15:05 UTC, taek0622 requested changes
고생하셨습니다.
조금만 더 하면 될 것 같은데 상당히 아쉽네요.
그래도 정말 고생하셨어요. 자세한 이야기는 세션시간에 나누는 걸로 하고, 세션 시간에 마음에 준비하시고 조용히 룸3로 따라오시면 될 것 같습니다.

2022-10-20 15:05 UTC, taek0622 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +    }
p1;
이 부분을 꼭 if문으로 컨트롤해야 했을까요?
다른 방법도 있을 것 같은데, 우선 UIActivityViewController에 대한 이해가 부족해 보입니다.
사실 정답에 상당히 근접할 수 있었는데 갑자기 선로 우회해서 엉뚱한 길로 빠져버린 코드 같아요.
조금만 더 고민해 보거나, 주변에 도움을 구하거나, UIActivityViewController 사용법에 대해서 더 찾아보았다면 더 좋은 코드가 될 수 있었을 것 같습니다.
이 부분에 대한 자세한 이야기는 오전 세션 시간에 직접 만나서 이야기하는 걸로 해요.

2022-10-21 04:36 UTC, taek0622 requested changes
고생하셨습니다.
그 길고 길었던 코드에 대해서 오랜 시간 이야기 듣느라 고생하셨고, 또 생각하고 수정하시느라 고생하셨어요.
그래도 항상 잘 받아들여주셔서 감사합니다 에디
추가로 몇 부분에 리뷰 달았습니다. 확인 부탁드려요
항상 감사해요 에디~

2022-10-21 04:36 UTC, taek0622 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +
p2;
불필요한 공백이 포함 되어있습니다. 삭제 부탁드려요~

2022-10-21 04:36 UTC, taek0622 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +    }
코드가 상당히 간결해졌네요.
누가 지도한 코드인지 정말 멋져요~
하나만 짚어보자면 172 라인 마지막의 applicationActivities는 꼭 필요한 걸까요?
용도가 궁금합니다.

2022-10-21 06:02 UTC, JUNY0110 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +
5cd58f6
반영했습니다~

2022-10-21 06:10 UTC, JUNY0110 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +    }
필수 입력 argument입니다. 
UIActivity타입을 생성하여 사용하면 될 것 같습니다.
참고자료입니다. https://zeddios.tistory.com/395

2022-10-21 06:11 UTC, JUNY0110 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +    }
> 코드가 상당히 간결해졌네요.
> 누가 지도한 코드인지 정말 멋져요~
> 하나만 짚어보자면 172 라인 마지막의 applicationActivities는 꼭 필요한 걸까요?
> 용도가 궁금합니다.

필수 입력 argument입니다. 
UIActivity타입을 생성하여 사용하면 될 것 같습니다.
UIActivity타입은 어떤 공유기능을 이용할 것인가에 대한 내용인 것 같습니다.
참고자료입니다. https://zeddios.tistory.com/395

2022-10-21 06:12 UTC, taek0622 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +
> [5cd58f6](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/5cd58f60dc34137cac3d743900e0d23e88289c5f) 반영했습니다~

확인했습니다. 리뷰 리졸브합니다.

2022-10-21 06:13 UTC, taek0622 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +    }
> > 코드가 상당히 간결해졌네요.
> > 누가 지도한 코드인지 정말 멋져요~
> > 하나만 짚어보자면 172 라인 마지막의 applicationActivities는 꼭 필요한 걸까요?
> > 용도가 궁금합니다.
> 
> 필수 입력 argument입니다. UIActivity타입을 생성하여 사용하면 될 것 같습니다. 참고자료입니다. https://zeddios.tistory.com/395

참고자료 감사합니다.
제가 더 공부해보고 자세한 내용 공유할게요~

2022-10-21 06:13 UTC, JUNY0110 commented on Samsam/ViewController/DetailView/DetailViewController.swift
> +    }
> p1;
> 이 부분을 꼭 if문으로 컨트롤해야 했을까요?
> 다른 방법도 있을 것 같은데, 우선 UIActivityViewController에 대한 이해가 부족해 보입니다.
> 사실 정답에 상당히 근접할 수 있었는데 갑자기 선로 우회해서 엉뚱한 길로 빠져버린 코드 같아요.
> 조금만 더 고민해 보거나, 주변에 도움을 구하거나, UIActivityViewController 사용법에 대해서 더 찾아보았다면 더 좋은 코드가 될 수 있었을 것 같습니다.
> 이 부분에 대한 자세한 이야기는 오전 세션 시간에 직접 만나서 이야기하는 걸로 해요.

테스트플라이트 이후 삭제될 코드이고, 메모리 소모도 감당가능한 부분이라 생각했지만, 미뉴의 의견을 반영해 코드를 더 간결하게 구성해봤습니다. ^^7

2022-10-21 06:16 UTC, taek0622 approved these changes
고생하셨습니다.
이번 PR에 대해서 오랜 시간 같이 이야기 나누고 들어주셔서 감사합니다.
앞으로도 잘 부탁드려요 에디~

참고로, 앞으로 심신 미약 코드는 올리기 전에 자세하게 저랑 전화해서 상의하고 코드에 대해 다시 이야기해 본 다음 올리는 것으로 해요.

2022-10-21 06:17 UTC, merged