[Design] 방 생성 카테코리 뷰 Layout 생성
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #45
Opened 2022-10-21 08:36 UTC by CreoHwan

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 방 생성 카테고리 뷰 Layout 생성

## Key Changes 🔥 (주요 구현/변경 사항)
- UICollectionView 레이아웃 생성
- Button 을 이용하여 '방 생성 완료(RoomCodeView)'로 Navigatioin 이동
- UILabel 중간 Text 변화시키기

## ToDo 📆 (남은 작업)
- [ ] VC에서 선택된 cell 을 알 수 있도록 조치하기

## ScreenShot 📷 (참고 사진)
![Simulator Screen Recording - iPhone 14 - 2022-10-21 at 17 34 11](https://user-images.githubusercontent.com/92836045/197151402-f709436e-76b3-4989-ad50-afa5739edd6f.gif)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- UILabel 중간 텍스트 바꾸는 효과를 구현했는데, 엄격한 리뷰 부탁드립니다!

## Reference 🔗

## Close Issues 🔒 (닫을 Issue)
Close #36

2022-10-21 10:43 UTC, JUNY0110 requested changes
고생하셨습니다! 질문이 조금 있는데 답해주시면 감사하겠습니다

2022-10-21 10:43 UTC, JUNY0110 commented on Samsam/ViewController/RoomCategoryViewController.swift
> +    }(UIButton())
Q. 
#selector(tapNextBTN(_sender:)의 경우, Sender 타입이 별도로 지정되지 않았는데, 저 코드가 없어도 정상동작을 할 것 같습니다. sender:를 남겨두신 이유가 있을까요?

2022-10-21 10:43 UTC, JUNY0110 commented on Samsam/ViewController/RoomCategoryViewController.swift
> +    }
Q.
cellHeight가 Int값인데, Int로 다시 한 번 감싸는 이유가 있을까요?

2022-10-21 10:43 UTC, JUNY0110 commented on Samsam/ViewController/RoomCategoryViewController.swift
> +    }
p4.
코드 순서를 이렇게 짠 이유가 있을까요??
동작 자체는 차이가 없어보이는데, categoryView가 nextBTN보다 선행되어야 Constraint에 대해 더 직관적으로 이해할 수 있을 것 같습니다.

2022-10-21 10:43 UTC, JUNY0110 commented on Samsam/ViewController/RoomCategoryViewController.swift
> +    }
Q. 
sender를 따로 사용하지 않는다면 없어도 되지 않을까요??

2022-10-21 10:43 UTC, JUNY0110 commented on Samsam/ViewController/RoomCategoryViewController.swift
> +
p3.
 navigationController?.setNavigationBarHidden(false, animated: false)는 원래 navigationBar의 기본값인 것 같습니다. 기본 세팅이 Hidden되지 않기 때문에 해당 코드는 삭제해도 무방할 것 같습니다.

2022-10-21 10:57 UTC, taek0622 approved these changes
고생하셨어요 디너
보면서 이런 식으로도 func을 만들 수 있구나를 느낄 수 있는 좋은 코드였습니다.
굳~

2022-10-21 10:57 UTC, taek0622 commented on Samsam/ViewController/RoomCategoryViewController.swift
> +        titleText.attributedText = statement
이런 식으로 텍스트의 일부 색을 변경하는 방법이 있었네요.
아주 좋습니다.

2022-10-21 10:57 UTC, taek0622 commented on Samsam/ViewController/RoomCategoryViewController.swift
> +}
이렇게 extension에서 func을 만들어서 색을 변경하는 방법이군요.
아주 좋습니다.
해당 코드는 보면서 공부 해봐야겠어요.

2022-10-21 10:57 UTC, taek0622 commented on Samsam/ViewController/RoomCategoryViewController.swift
> +        return 24
p4;
후에 데이터를 받아왔을 때 데이터 개수로 변경할 필요가 있어보이는 코드네요.

2022-10-21 14:36 UTC, JUNY0110 reviewed
p3였어서 comment로 수정했습니다!

2022-10-22 04:45 UTC, CreoHwan commented on Samsam/ViewController/RoomCategoryViewController.swift
> +}
> 이렇게 extension에서 func을 만들어서 색을 변경하는 방법이군요. 아주 좋습니다. 해당 코드는 보면서 공부 해봐야겠어요.

저는 조금 복잡하게 짰는데, extension을 UILabel에 바로 주는 방법도 있는 것 같았습니다!

2022-10-22 04:46 UTC, CreoHwan commented on Samsam/ViewController/RoomCategoryViewController.swift
> +        return 24
> p4; 후에 데이터를 받아왔을 때 데이터 개수로 변경할 필요가 있어보이는 코드네요.

맞습니다! 내일 vc와 cell을 오가는 다리 역할을 하는 친구를 생각해보겠습니다!

2022-10-22 05:10 UTC, CreoHwan commented on Samsam/ViewController/RoomCategoryViewController.swift
> +    }(UIButton())
> Q. #selector(tapNextBTN(_sender:)의 경우, Sender 타입이 별도로 지정되지 않았는데, 저 코드가 없어도 정상동작을 할 것 같습니다. sender:를 남겨두신 이유가 있을까요?

A. 사실 저도 그냥 작동해서 냅두긴 했었는데... 덕분에 sender에 관하여 공부하게 되었습니다! 감사합니다~

2022-10-22 05:15 UTC, CreoHwan commented on Samsam/ViewController/RoomCategoryViewController.swift
> +    }(UIButton())
A. 에디 말씀이 맞는 것 같습니다! 덕분에 sender에 대해서 공부하게 되었습니다! 감사합니다!

2022-10-22 05:18 UTC, CreoHwan commented on Samsam/ViewController/RoomCategoryViewController.swift
> +    }
A. 처음에 정사각형으로 만들었다가, 나중에 직사각형으로 만들었는데, 그때 까먹고 수정하지 않은 것 같습니다! 감사합니다!

2022-10-22 05:19 UTC, CreoHwan commented on Samsam/ViewController/RoomCategoryViewController.swift
> +    }(UIButton())
> Q. #selector(tapNextBTN(_sender:)의 경우, Sender 타입이 별도로 지정되지 않았는데, 저 코드가 없어도 정상동작을 할 것 같습니다. sender:를 남겨두신 이유가 있을까요?

A. 에디 말씀이 맞는 것 같습니다! 덕분에 sender에 대해서 공부하게 되었습니다! 감사합니다! 9167e50

2022-10-22 05:20 UTC, CreoHwan commented on Samsam/ViewController/RoomCategoryViewController.swift
> +    }
> Q. cellHeight가 Int값인데, Int로 다시 한 번 감싸는 이유가 있을까요?

A. 처음에 정사각형으로 만들었다가, 나중에 직사각형으로 만들었는데, 그때 까먹고 수정하지 않은 것 같습니다! 감사합니다! b173f72

2022-10-22 05:22 UTC, CreoHwan commented on Samsam/ViewController/RoomCategoryViewController.swift
> +    }
> p4. 코드 순서를 이렇게 짠 이유가 있을까요?? 동작 자체는 차이가 없어보이는데, categoryView가 nextBTN보다 선행되어야 Constraint에 대해 더 직관적으로 이해할 수 있을 것 같습니다.

좋은 의견 감사합니다! 앞으로 신경써서 짜도록 하겠습니다! 34b65a1

2022-10-22 05:27 UTC, CreoHwan commented on Samsam/ViewController/RoomCategoryViewController.swift
> +    }
A. 맞습니다! 감사합니다! 939f286

2022-10-22 06:06 UTC, taek0622 commented on Samsam/ViewController/RoomCategoryViewController.swift
> +}
> > 이렇게 extension에서 func을 만들어서 색을 변경하는 방법이군요. 아주 좋습니다. 해당 코드는 보면서 공부 해봐야겠어요.
> 
> 저는 조금 복잡하게 짰는데, extension을 UILabel에 바로 주는 방법도 있는 것 같았습니다!

이 부분에 대해서는 저도 한번 찾아봐야겠네요. 좋은 인사이트 감사합니다~

2022-10-22 06:19 UTC, CreoHwan commented on Samsam/ViewController/RoomCategoryViewController.swift
> +
> p3. navigationController?.setNavigationBarHidden(false, animated: false)보다 animated: true가 사용자에게 더 자연스러운 느낌을 줄 것 같습니다. animated true로 동작 시, 네비게이션 바가 네비게이션 동작 시 네비게이션 동작과 동일하게 이동하는 모션이 나타나기 때문입니다. 아래는 참고자료입니다.
> 
> https://velog.io/@ryan-son/Swift-%ED%8A%B9%EC%A0%95-View-Controller%EC%97%90%EC%84%9C-Navigation-Bar-%EC%88%A8%EA%B8%B0%EA%B8%B0
> 
> Q. standardAppearance와 scrollEdgeAppearance를 사용하신 이유가 있을까요? 어떤 문제를 해결하기 위해 사용한 코드인지 궁금합니다.

1. 감사합니다!

2022-10-22 07:32 UTC, CreoHwan commented
@taek0622 @JUNY0110 확인부탁드립니다!

2022-10-24 02:24 UTC, JUNY0110 commented on Samsam/ViewController/RoomCategoryViewController.swift
> +
감사합니다! 다음에 Appearance를 사용해 커스텀해보고 싶네요

2022-10-24 02:24 UTC, JUNY0110 commented on Samsam/ViewController/RoomCategoryViewController.swift
> +
> 
> 1. 감사합니다! [9cbc53e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/9cbc53eb35966f2b14a5c1664979dbb65babc2ca)
> 2. 처음에 네비게이션바 맨 위에 있는 부분이 흰색이 아니었습니다. 왜냐하면 제가 구분을 위해 view.backgroundcolor를 white가 아닌 yelloew를 주었기 때문입니다. 이후 윗 부분을 흰색으로 바꾸기 위해 찾아본 결과 UINavigationBarAppearance 를 활용하면 된다는 것을 알게 되었습니다. 그러다 나중에 view.backgroundcolor를 white로 바꾸자, 이 부분이 필요없어졌다고 판단하여 지웠습니다! 그 과정에서 저 친구들은 그냥 냅둔 것 같습니다(하지만 일단 우리 앱의 background가 결국은 white이니 고려할 상황은 아니었다고 생각합니다!) 아래는 관련 내용입니다! [5dadd59](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/5dadd5940cb193e7f312c068bd06f982fa1c79a6)
>    (scrolledge: 스크롤 하기 전 색상, standard 스크롤 하는 중 색상)
> 
> [Toyproject-IOS/CarrotMarket#21](https://github.com/Toyproject-IOS/CarrotMarket/issues/21)

감사합니다! 다음에 Appearance를 사용해 커스텀해보고 싶네요

2022-10-24 02:25 UTC, JUNY0110 commented on Samsam/ViewController/RoomCategoryViewController.swift
> +    }
> > p4. 코드 순서를 이렇게 짠 이유가 있을까요?? 동작 자체는 차이가 없어보이는데, categoryView가 nextBTN보다 선행되어야 Constraint에 대해 더 직관적으로 이해할 수 있을 것 같습니다.
> 
> 좋은 의견 감사합니다! 앞으로 신경써서 짜도록 하겠습니다! [34b65a1](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/34b65a1a5db52fb957d1c1f8cd4a0defd60a528a)

확인된 코드이니 resolve하겠습니다.

2022-10-24 02:25 UTC, JUNY0110 commented on Samsam/ViewController/RoomCategoryViewController.swift
> +    }
> 
> A. 처음에 정사각형으로 만들었다가, 나중에 직사각형으로 만들었는데, 그때 까먹고 수정하지 않은 것 같습니다! 감사합니다! [b173f72](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/b173f72c8f21602a430226a7324eb350dd20c008)

굿굿 확인된 코드이니 resolve하겠습니다.

2022-10-24 02:26 UTC, JUNY0110 commented on Samsam/ViewController/RoomCategoryViewController.swift
> +    }(UIButton())
> A. 에디 말씀이 맞는 것 같습니다! 덕분에 sender에 대해서 공부하게 되었습니다! 감사합니다! [9167e50](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/9167e50056ceef50a8e57c8e30d4fbc65c586b36)

확인된 코드이니 resolve하겠습니다.

2022-10-24 02:27 UTC, JUNY0110 approved these changes
고생하셨습니다~ 재밌는 코드가 많네요

2022-10-24 06:01 UTC, merged