[Design] 방 생성 뷰(RoomCreationView) 레이아웃
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #46
Opened 2022-10-21 15:27 UTC by JUNY0110

## Motivation 🥳 (코드를 추가/변경하게 된 이유)

## Key Changes 🔥 (주요 구현/변경 사항)
- DatePicker
- Stepper
- navigation

## ToDo 📆 (남은 작업)
- [ ] DatePicker 시공일 기준으로, 준공일이 시공일 이전을 선택할 수 없도록 하는 것.

## ScreenShot 📷 (참고 사진)
https://user-images.githubusercontent.com/98405970/197232427-f9cbd866-57c4-4be9-b5de-c78ec1035c83.mp4

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- stepper를 0개월일 때, 또는 24개월일 때 - 또는 + 클릭 시 0에서 24로, 24에서 0으로 넘어가지 않도록 하는 게 좋을까요?
- 아니면 넘어갈 수 있도록 하는 게 좋을까요?

## Reference 🔗

## Close Issues 🔒 (닫을 Issue)
Close #43 .

2022-10-21 15:40 UTC, taek0622 requested changes
고생하셨습니다.
수정이 필요한 부분에 대해 리뷰 남겼으니 반드시 꼼꼼하게 확인해주시기 바랍니다.
항상 감사합니다 에디~

2022-10-21 15:40 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }(UITextField())
p5;
이 부분은 폰트 사이즈와 웨이트를 따로 주지 않아도 되는 것일까요?

2022-10-21 15:40 UTC, ikanic commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    private let textUnderLine: UIView = {
p5;
textUnderLine이라는 이름도 좋지만 현재 뷰에 텍스트가 많습니다.
차라리 textInputUnderLine이나 textInputSeparator 등의 더 명확한 이름은 어떨까요?

2022-10-21 15:40 UTC, ikanic commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }(UIStackView())
p1;
hstack인데 stack의 axis가 따로 지정되어있지 않네요.
axis를 명확하게 지정해주는 것이 좋을 것 같습니다.

2022-10-21 15:40 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }(UIStackView())
p1;
여기도 hstack인데 stack의 axis가 따로 지정되어있지 않네요.
axis를 명확하게 지정해주는 것이 좋을 것 같습니다.

2022-10-21 15:40 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }(UIStackView())
p1;
이것도 마찬가지로 hstack인데 stack의 axis가 따로 지정되어있지 않네요.
axis를 명확하게 지정해주는 것이 좋을 것 같습니다.

2022-10-21 15:40 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +//
p1;
이곳에는 왜 주석이 있을까요?
불필요한 주석은 삭제하는 것이 좋을 것 같습니다.

2022-10-21 15:40 UTC, ikanic commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +        view.backgroundColor = .white
p5;
view.backgroundColor는 attribute로 이동하는 것이 어떨까요?

2022-10-21 15:40 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +        view.addSubview(nextButton)
p5;
너무 뭉떵이로 코드가 뭉쳐있어서 가독성이 떨어지는 것 같습니다.
라인 분리 부탁드려요.

2022-10-21 15:40 UTC, ikanic commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }
p3;
해당 부분 padding이 일정 이상 반드시 잡히고 있는 것 같은데, 이런 경우 겉을 UIView 등으로 한번 감싸고 해당 부분을 padding으로 주는 것이 더 효율적이지 않을까 싶습니다.

2022-10-21 15:45 UTC, taek0622 requested changes
추가적으로 발견한 부분이 있어서 추가 리뷰 남겼습니다.
확인 부탁드려요.

2022-10-21 15:45 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +
p2;
불필요한 공백이 들어가있는 것 같습니다.
컨벤션에 따라 공백은 한 줄만 부탁드려요.

2022-10-21 15:49 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +        view.addSubview(nextButton)
a01f435
반영했습니다~

2022-10-21 15:50 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +        view.backgroundColor = .white
d412703
반영했습니다~

2022-10-22 01:00 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }
a996b1e
좋은 생각인 것 같습니다. 반복되는 constraints코드를 어떻게 줄일지 고민하고 있었는데, uiview를 통해 해결할 수 있었네요!

2022-10-22 01:01 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +//
d412703
빠뜨린 주석이 있었네요..! 반영했습니다~

2022-10-22 01:02 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +        view.backgroundColor = .white
> [d412703](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/d41270399bf9cb173dc715c7fb59400e2f74ab65) 반영했습니다~

확인했습니다. 은근슬쩍 빠져있던 `MARK`도 추가하셨군요. 아주 좋습니다.
해당 리뷰 리졸브 하겠습니다~

2022-10-22 01:03 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +        view.addSubview(nextButton)
> [a01f435](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/a01f435f4e80f629876e308a93bf5bf3617d199e) 반영했습니다~

확인했습니다. 적절하게 나누니 훨씬 코드가 잘 보이는 것 같네요. 리뷰 리졸브합니다~

2022-10-22 01:04 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }
> [a996b1e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/a996b1eaade29e3c2432a5748851d4c25eb11d82) 좋은 생각인 것 같습니다. 반복되는 constraints코드를 어떻게 줄일지 고민하고 있었는데, uiview를 통해 해결할 수 있었네요!

확인했습니다. 지금처럼 반복되는 padding이라면 반복되는 부분을 감싸는 UIView를 만들어서 공통으로 padding을 주는 것이 확실히 더 코드도 깔끔하고 반복을 줄일 수 있어서 좋은 것 같네요. 해당 리뷰 리졸브합니다.

2022-10-22 01:04 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    private let textUnderLine: UIView = {
> p5;
> textUnderLine이라는 이름도 좋지만 현재 뷰에 텍스트가 많습니다.
> 차라리 textInputUnderLine이나 textInputSeparator 등의 더 명확한 이름은 어떨까요?

좋은 것 같습니다. 하지만 현재 뷰에 밑줄이라고 할 수 있는 것은 단 한 줄 뿐이기 때문에, 수정할 소요까지는 없다고 생각해 추후 다른 밑줄이 생기거나 모호함이 있다면 수정하겠습니다.

2022-10-22 01:04 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +//
> [d412703](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/d41270399bf9cb173dc715c7fb59400e2f74ab65) 빠뜨린 주석이 있었네요..! 반영했습니다~

확인했습니다. 해당 리뷰 리졸브합니다.

2022-10-22 01:08 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    private let textUnderLine: UIView = {
> > p5;
> > textUnderLine이라는 이름도 좋지만 현재 뷰에 텍스트가 많습니다.
> > 차라리 textInputUnderLine이나 textInputSeparator 등의 더 명확한 이름은 어떨까요?
> 
> 좋은 것 같습니다. 하지만 현재 뷰에 밑줄이라고 할 수 있는 것은 단 한 줄 뿐이기 때문에, 수정할 소요까지는 없다고 생각해 추후 다른 밑줄이 생기거나 모호함이 있다면 수정하겠습니다.

좋습니다. 다만, 현재 뷰에서 라인이 하나뿐이라 모호함이 없어서 이름을 포괄적으로 짓는 것보다는, 앞으로는 컴포넌트가 모호함이 적어보여도 이름은 명확하게 지어주는 것이 어떨까 생각합니다.

2022-10-22 01:12 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }(UITextField())
68561af
누락했었네요!
다만 현재 피그마 상으로 16으로 되어있는데, 그렇게 했을 때, 다른 라벨(타이틀)과 사이즈 차이가 나지 않아 다른 고객명/주소 등과 같은 타이틀들의 사이즈를 18로 일부 수정(16+2)했습니다.

2022-10-22 01:14 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }(UIStackView())
df4e045
uiStack의 기본값이 horizontal이라 누락된 것 같습니다 감사합니다.

2022-10-22 01:14 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }(UIStackView())
df4e045
uiStack의 기본값이 horizontal이라 누락된 것 같습니다 감사합니다.

2022-10-22 01:14 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }(UIStackView())
df4e045
uiStack의 기본값이 horizontal이라 누락된 것 같습니다 감사합니다.

2022-10-22 01:14 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }(UITextField())
> [68561af](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/68561af2180179ecbaaadee11be26e61a4de76e9) 누락했었네요! 다만 현재 피그마 상으로 16으로 되어있는데, 그렇게 했을 때, 다른 라벨(타이틀)과 사이즈 차이가 나지 않아 불편함을 야기할 것 같아 다른 고객명/주소 등과 같은 타이틀들의 사이즈를 18로 일부 수정(16+2)했습니다.

좋습니다. 다만, 이 부분에 대해서는 전체적으로 변경되어야 할 부분이기 때문에 다시 한번 논의할 필요가 있는 것 같습니다.
또한, AS기간의 `n개월` 부분은 레이블이지만 변경될 수 있는 일종의 인풋같은 컴포넌트라고 생각합니다.
그렇기 때문에 `n개월` 부분은 사이즈를 16으로 두는 것이 어떨까요?

2022-10-22 01:15 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +
a996b1e
Uiview작업을 하면서 같이 반영했습니다. 감사합니다.

2022-10-22 01:17 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }(UIStackView())
> [df4e045](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/df4e045c7701e1899a30151840b99ea1a0cacda3) uiStack의 기본값이 horizontal이라 누락된 것 같습니다 감사합니다.

UIStackView의 axis의 기본값이 .horizontal이라서 변경되지 않아도 되는 부분이긴 합니다만, 추후 헷갈릴일이 없도록 명시해주는 것이 더 좋다고 생각했습니다. 반영 감사합니다. 해당 리뷰는 리졸브합니다~

2022-10-22 01:17 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }(UIStackView())
> [df4e045](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/df4e045c7701e1899a30151840b99ea1a0cacda3) uiStack의 기본값이 horizontal이라 누락된 것 같습니다 감사합니다.

마찬가지로 UIStackView의 axis의 기본값이 .horizontal이라서 변경되지 않아도 되는 부분이긴 합니다만, 추후 헷갈릴일이 없도록 명시해주는 것이 더 좋다고 생각했습니다. 반영 감사합니다. 해당 리뷰는 리졸브합니다~

2022-10-22 01:17 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }(UIStackView())
> [df4e045](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/df4e045c7701e1899a30151840b99ea1a0cacda3) uiStack의 기본값이 horizontal이라 누락된 것 같습니다 감사합니다.

여기도 UIStackView의 axis의 기본값이 .horizontal이라서 변경되지 않아도 되는 부분이긴 합니다만, 추후 헷갈릴일이 없도록 명시해주는 것이 더 좋다고 생각했습니다. 반영 감사합니다. 해당 리뷰는 리졸브합니다~

2022-10-22 01:17 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }(UITextField())
22fa47b
확인 후 수정했습니다.

2022-10-22 01:18 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +
> [a996b1e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/a996b1eaade29e3c2432a5748851d4c25eb11d82) Uiview작업을 하면서 같이 반영했습니다. 감사합니다.

확인했습니다. 리뷰 리졸브합니다.

2022-10-22 01:18 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }(UITextField())
> [22fa47b](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/22fa47b807c6ca3930600234c12be4c8cdd3b82c) 확인 후 수정했습니다.

확인했습니다. 리뷰 리졸브합니다. 감사합니다~

2022-10-22 01:27 UTC, taek0622 reviewed
고생하셨습니다.
추가적으로 필요해보이는 곳에 의견 남겼으니 확인하시고 코멘트 남겨주세요.
항상 감사합니다 에디~

2022-10-22 01:27 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    private var warrantyCount = 0
p3;
해당 부분은 바로 호출되지 않는 프로퍼티인 것 같은데, lazy를 사용하는 것은 어떨까요?

2022-10-22 01:27 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +
p3;
표준 계약서상 AS기간은 기본 1년입니다.
해당 부분에 맞춰 기본 값을 12개월로 두는 것은 어떨까요?
현재 저희 스테퍼가 24개월까지 가능한데
0개월부터 24개월로 가는 것보다는 12개월부터 24개월, 12개월부터 0개월로 가는 것이 더 편하고 자연스럽지 않을까 생각합니다.

2022-10-22 01:29 UTC, taek0622 reviewed
고생하셨습니다.
추가적으로 필요해보이는 곳에 의견 남겼으니 확인하시고 코멘트 남겨주세요.
항상 감사합니다 에디~

2022-10-22 01:29 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }(UIStepper())
p3;
표준 계약서상 AS기간은 기본 1년입니다.
해당 부분에 맞춰 기본 값을 12개월로 두는 것은 어떨까요?
현재 저희 스테퍼가 24개월까지 가능한데
0개월부터 24개월로 가는 것보다는 12개월부터 24개월, 12개월부터 0개월로 가는 것이 더 편하고 자연스럽지 않을까 생각합니다.

2022-10-22 01:29 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    private var warrantyCount = 0
p3;
해당 부분은 바로 호출되지 않는 프로퍼티인 것 같은데, lazy를 사용하는 것은 어떨까요?

2022-10-22 01:33 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    private var warrantyCount = 0
> p3;
> 해당 부분은 바로 호출되지 않는 프로퍼티인 것 같은데, lazy를 사용하는 것은 어떨까요?

152b1b1
좋네요! 아주 잘 작동합니다.

2022-10-22 01:34 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }(UIStepper())
> p3;
> 표준 계약서상 AS기간은 기본 1년입니다.
> 해당 부분에 맞춰 기본 값을 12개월로 두는 것은 어떨까요?
> 현재 저희 스테퍼가 24개월까지 가능한데
> 0개월부터 24개월로 가는 것보다는 12개월부터 24개월, 12개월부터 0개월로 가는 것이 더 편하고 자연스럽지 않을까 생각합니다.

이 부분은 논의가 필요할 것 같습니다. '표준 계약상'은 12개월이지만, 24개월, 36개월까지 AS를 보장해주는 업체도 있다고 합니다. '표준'에 맞춰서 그 외의 가능성을 닫아버리는 게 아닐까요? 추후 유저테스트를 하면서 결정하는 게 좋을 것 같습니다.

2022-10-22 01:37 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    private var warrantyCount = 0
> > p3;
> > 해당 부분은 바로 호출되지 않는 프로퍼티인 것 같은데, lazy를 사용하는 것은 어떨까요?
> 
> [152b1b1](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/152b1b1a724316fcbbff6cff8e7fd0348d2e5dc2) 좋네요! 아주 잘 작동합니다.

확인했습니다. 해당 리뷰 리졸브합니다.

2022-10-22 01:39 UTC, JUNY0110 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }(UIStepper())
9021a57
굿굿 좋은 생각인 것 같습니다.

2022-10-22 01:40 UTC, taek0622 commented on Samsam/ViewController/RoomCreationView/RoomCreationViewContoller.swift
> +    }(UIStepper())
> [9021a57](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/9021a5705ba543433e114758395274bf0f141330) 굿굿 좋은 생각인 것 같습니다.

확인했습니다. 해당 리뷰 리졸브하겠습니다~

2022-10-22 01:43 UTC, ikanic approved these changes
고생하셨습니다.
한 뷰에 많은 컨트롤들이 들어가서 작업하기 조금 까다로울 수도 있으셨을텐데 잘 그려진 것 같아서 매우 만족스럽네요.
앞으로 더 복잡한 작업도 에디한테 믿고 맡길 수 있을 것 같아요.
항상 감사하고 믿고, 응원해요 에디~

2022-10-22 01:44 UTC, merged