[Design] 시공상황 작성 이미지 업로드 뷰 Layout 생성 및 기능 구현
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #55
Opened 2022-10-25 05:00 UTC by CreoHwan

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 시공상황 작성 이미지 업로드 뷰 Layout 생성 및 기능 구현

## Key Changes 🔥 (주요 구현/변경 사항)
- Layout 생성
- 이미지 뷰 업로드 기능 (최대 4개)

## ToDo 📆 (남은 작업)
- [ ] 업로드 되는 사진 순서를 바꾸어야 함

## ScreenShot 📷 (참고 사진)
![Uploading Simulator Screen Recording - iPhone 14 - 2022-10-25 at 13.56.56.gif…]()

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 늦어서 죄송합니다!
- 이미지 업로드 부분(개수 제한 포함) 빡센 리뷰 환영합니다!

## Reference 🔗

## Close Issues 🔒 (닫을 Issue)
Close #34

2022-10-25 05:40 UTC, taek0622 requested changes
고생하셨습니다.
수정이 필요해보이거나, 의문이 생기는 부분에 코멘트 남겼습니다. 확인 부탁드려요~

2022-10-25 05:40 UTC, taek0622 commented on Samsam.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_NSPhotoLibraryUsageDescription = "사진 업로드를 위해 라이브러리 접근권한이 필요합니다.";
p1;
plist가 정상 동작하고 있는게 맞을까요?
앱을 실행했을 때, 권한을 물어보지 않는 것 같습니다.

2022-10-25 05:40 UTC, taek0622 commented on Samsam.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_NSPhotoLibraryUsageDescription = "사진 업로드를 위해 라이브러리 접근권한이 필요합니다.";
p1;
마찬가지로 앱을 실행했을 때, 권한을 물어보지 않는 것 같습니다.
확인이 필요합니다.

2022-10-25 05:40 UTC, taek0622 commented on Samsam/Info.plist
> +	<string>사진 업로드를 위해 라이브러리 접근권한이 필요합니다.</string>
p1;
마찬가지로 앱을 실행했을 때, 권한을 물어보지 않는 것 같습니다.
plist에 대한 확인이 필요할 것 같아요.

2022-10-25 05:40 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +    var imgItems:[PreviewItem] = [PreviewItem(name: 0, image: UIImage(named: "CameraBTN"))]
p1;
현재 이미지 버튼을 위한 기본 버튼 이미지가 에셋으로 들어가 있는 것 같습니다. 해당 부분은 에셋이 아니라 기본 컴포넌트로도 똑같이 만들 수 있을 것 같은데, 기본 컴포넌트를 활용하는 것이 더 좋을 것 같습니다.

2022-10-25 05:40 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +    }
p2;
해당 struct는 어떻게 사용되고 있는 것일까요?
받아올 데이터를 위한 struct인 것 같은데, class 밖에서 선언하는게 어떨까 싶습니다.
또한, image는 어떻게 사용되는지 예상이 가나, name은 어떻게 사용되는지 용도가 궁금합니다.

2022-10-25 05:40 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +        $0.text = "시공한 사진을 추가해주세요. \n (최대 4장까지 가능합니다)."
p2;
\n 앞 뒤로 있는 공백은 불필요한 공백인 것 같습니다.
특히, 뒤의 공백은 `(` 앞에 공백 한칸을 함께 출력하는 문제가 있을 것 같습니다.
불필요한 공백 삭제 부탁드려요.

2022-10-25 05:40 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +    }(UIImageView())
p2;
이 부분은 외부에서 접근할 일이 있을까요?
의도하신 것이 아니라면 접근지정자가 필요해보입니다.

2022-10-25 05:40 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +        navigationController?.setNavigationBarHidden(false, animated: false)
p1;
serNavigationBarHidden의 기본 속성이 모두 false라면 해당 메서드가 사용될 이유가 없을 것 같습니다.
원하시는 동작이 둘 다 false라면 사용할 필요 없는 구문인 것 같습니다.
다만, setNavigationBarHidden의 animated 동작이 true일 때 더 부드럽게 보여서 해당 부분을 true로 바꾸는 것이 어떨까 제안해봅니다.
해당 부분에 대한 레퍼런스는 저번 PR에서 에디가 남겨두셨던 걸로 기억해서 별도로 남기진 않겠습니다.

2022-10-25 05:40 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +    }
p1;
해당 부분은 네비게이션을 이용해 다른 뷰로 넘어가는 부분으로 보이는데, 그렇다면 아무것도 정의되지 않은 ViewController가 아니라 필요한 뷰의 컨트롤러가 들어가야할 것 같습니다.

2022-10-25 05:40 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +        cell.preview.image = item.image
p1;
해당 부분은 `cell.preview.image = imgItems[indexPath.row].image`와 같이 줄일 수도 있을 것 같습니다.

2022-10-25 05:40 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +        if numberOfItem > 3 {
질문;
이 부분을 numberOfItem을 global scope로 설정한 뒤, 그 값을 갱신해서 if문을 적용하는 방법 밖에 없었을까요?
indexPath에는 마지막 노드의 index를 가져오는 방법이 있는 것으로 알고 있습니다.
해당 부분을 이용해서 다른 방법으로 불러오는 방법은 없었을까요?
혹은 배열의 요소 개수를 새는 방법도 있었을 것 같네요.

2022-10-25 06:08 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> +    }(UIImageView())
> p2; 이 부분은 외부에서 접근할 일이 있을까요? 의도하신 것이 아니라면 접근지정자가 필요해보입니다.

감사합니다! 2c606a4

2022-10-25 06:11 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> +    }
> p1; 해당 부분은 네비게이션을 이용해 다른 뷰로 넘어가는 부분으로 보이는데, 그렇다면 아무것도 정의되지 않은 ViewController가 아니라 필요한 뷰의 컨트롤러가 들어가야할 것 같습니다.

166d9af 으악! 깜빡 잊었습니다! 감사합니다!

2022-10-25 06:13 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> +        cell.preview.image = item.image
> p1; 해당 부분은 `cell.preview.image = imgItems[indexPath.row].image`와 같이 줄일 수도 있을 것 같습니다.

그렇군요! 감사합니다! f475dbe

2022-10-25 06:25 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> +    var imgItems:[PreviewItem] = [PreviewItem(name: 0, image: UIImage(named: "CameraBTN"))]
> p1; 현재 이미지 버튼을 위한 기본 버튼 이미지가 에셋으로 들어가 있는 것 같습니다. 해당 부분은 에셋이 아니라 기본 컴포넌트로도 똑같이 만들 수 있을 것 같은데, 기본 컴포넌트를 활용하는 것이 더 좋을 것 같습니다.

맞습니다! cell 안에 버튼이 있기 때문에, 피그마에서 이미지를 가져와서, 그걸 사용했습니다! 이미지가 아니면 해당 부분은 처리가 어려울 것 같다고 판단했습니다!
에셋이 아니라 기본 컴포넌트를 이용하여 버튼 이미지를 만들 수 있나요??!

2022-10-25 06:32 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +    }(UIImageView())
> > p2; 이 부분은 외부에서 접근할 일이 있을까요? 의도하신 것이 아니라면 접근지정자가 필요해보입니다.
> 
> 감사합니다! [2c606a4](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/2c606a41c3c1e293298d4c5a277dd324e31431b0)

확인했습니다. 해당 리뷰 리졸브합니다.

2022-10-25 06:33 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +    }
> > p1; 해당 부분은 네비게이션을 이용해 다른 뷰로 넘어가는 부분으로 보이는데, 그렇다면 아무것도 정의되지 않은 ViewController가 아니라 필요한 뷰의 컨트롤러가 들어가야할 것 같습니다.
> 
> [166d9af](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/166d9afce35cace602ad37989b55552786d18d4f) 으악! 깜빡 잊었습니다! 감사합니다!

확인했습니다. 해당 리뷰 리졸브합니다.

2022-10-25 06:33 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> +    }
> p2; 해당 struct는 어떻게 사용되고 있는 것일까요? 받아올 데이터를 위한 struct인 것 같은데, class 밖에서 선언하는게 어떨까 싶습니다. 또한, image는 어떻게 사용되는지 예상이 가나, name은 어떻게 사용되는지 용도가 궁금합니다.

맞습니다! name은 받아올 데이터의 이름이 필요하지 않을까? 해서 만들었습니다! (Int 가 아니라 String이어야 했지만 ㅜ)
배열 안에서 무언가를 조작할 때, 데이터의 이름으로 조작하면 편하지 않을까? 혹은
받아올 데이터의 사진에 이름이 필요하지 않을까? 했는데
생각해보니 딱히 필요 없는 것 같습니다! 639295f d8cf7d9

2022-10-25 06:34 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +        cell.preview.image = item.image
> > p1; 해당 부분은 `cell.preview.image = imgItems[indexPath.row].image`와 같이 줄일 수도 있을 것 같습니다.
> 
> 그렇군요! 감사합니다! [f475dbe](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/f475dbe697cdb7292eea3fee45f52658135f72d1)

확인했습니다. 해당 리뷰 리졸브합니다.

2022-10-25 06:34 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> +        $0.text = "시공한 사진을 추가해주세요. \n (최대 4장까지 가능합니다)."
> p2; \n 앞 뒤로 있는 공백은 불필요한 공백인 것 같습니다. 특히, 뒤의 공백은 `(` 앞에 공백 한칸을 함께 출력하는 문제가 있을 것 같습니다. 불필요한 공백 삭제 부탁드려요.

맞습니다! 감사합니다! 1980ea2

2022-10-25 06:35 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +    }
> > p2; 해당 struct는 어떻게 사용되고 있는 것일까요? 받아올 데이터를 위한 struct인 것 같은데, class 밖에서 선언하는게 어떨까 싶습니다. 또한, image는 어떻게 사용되는지 예상이 가나, name은 어떻게 사용되는지 용도가 궁금합니다.
> 
> 맞습니다! name은 받아올 데이터의 이름이 필요하지 않을까? 해서 만들었습니다! (Int 가 아니라 String이어야 했지만 ㅜ) 배열 안에서 무언가를 조작할 때, 데이터의 이름으로 조작하면 편하지 않을까? 혹은 받아올 데이터의 사진에 이름이 필요하지 않을까? 했는데 생각해보니 딱히 필요 없는 것 같습니다! [639295f](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/639295f26e84a0b5efa07c0c4572f020005b7c36) [d8cf7d9](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/d8cf7d9a7b01ec340a05b59ed456a55380832539)

확인했습니다. 해당 부분 리뷰 리졸브합니다.

2022-10-25 06:36 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +        $0.text = "시공한 사진을 추가해주세요. \n (최대 4장까지 가능합니다)."
> > p2; \n 앞 뒤로 있는 공백은 불필요한 공백인 것 같습니다. 특히, 뒤의 공백은 `(` 앞에 공백 한칸을 함께 출력하는 문제가 있을 것 같습니다. 불필요한 공백 삭제 부탁드려요.
> 
> 맞습니다! 감사합니다! [1980ea2](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/1980ea262e4ccc42337525ec6619232739a35f9f)

확인했습니다. 해당 리뷰 리졸브합니다.

2022-10-25 06:38 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +    var imgItems:[PreviewItem] = [PreviewItem(name: 0, image: UIImage(named: "CameraBTN"))]
> > p1; 현재 이미지 버튼을 위한 기본 버튼 이미지가 에셋으로 들어가 있는 것 같습니다. 해당 부분은 에셋이 아니라 기본 컴포넌트로도 똑같이 만들 수 있을 것 같은데, 기본 컴포넌트를 활용하는 것이 더 좋을 것 같습니다.
> 
> 맞습니다! cell 안에 버튼이 있기 때문에, 피그마에서 이미지를 가져와서, 그걸 사용했습니다! 이미지가 아니면 해당 부분은 처리가 어려울 것 같다고 판단했습니다! 에셋이 아니라 기본 컴포넌트를 이용하여 버튼 이미지를 만들 수 있나요??!

사진 추가에 대해서는 잘 모르지만, 버튼에 이미지를 넣는 방법도 생각해볼 수 있을 것 같습니다.

2022-10-25 06:42 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> +        navigationController?.setNavigationBarHidden(false, animated: false)
> p1; serNavigationBarHidden의 기본 속성이 모두 false라면 해당 메서드가 사용될 이유가 없을 것 같습니다. 원하시는 동작이 둘 다 false라면 사용할 필요 없는 구문인 것 같습니다. 다만, setNavigationBarHidden의 animated 동작이 true일 때 더 부드럽게 보여서 해당 부분을 true로 바꾸는 것이 어떨까 제안해봅니다. 해당 부분에 대한 레퍼런스는 저번 PR에서 에디가 남겨두셨던 걸로 기억해서 별도로 남기진 않겠습니다.

띠용! 호다닥 조치했습니다! df59bae

2022-10-25 06:54 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> +        if numberOfItem > 3 {
> 질문; 이 부분을 numberOfItem을 global scope로 설정한 뒤, 그 값을 갱신해서 if문을 적용하는 방법 밖에 없었을까요? indexPath에는 마지막 노드의 index를 가져오는 방법이 있는 것으로 알고 있습니다. 해당 부분을 이용해서 다른 방법으로 불러오는 방법은 없었을까요? 혹은 배열의 요소 개수를 새는 방법도 있었을 것 같네요.

그런 방법으로 카운트는 가능합니다! 그런데 cell 개수가 5개가 되면, 버튼 cell이 빠지면서 4개로 바뀌게 됩니다! 이를 고려하여 조건문을 만드는 것이 까다로워져서 따로 뺐습니다!

2022-10-25 07:15 UTC, CreoHwan commented on Samsam.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_NSPhotoLibraryUsageDescription = "사진 업로드를 위해 라이브러리 접근권한이 필요합니다.";
> p1; plist가 정상 동작하고 있는게 맞을까요? 앱을 실행했을 때, 권한을 물어보지 않는 것 같습니다.

으악! 코드가 분실되었군요! 감사합니다! 2e248f3

2022-10-25 07:16 UTC, CreoHwan commented on Samsam.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_NSPhotoLibraryUsageDescription = "사진 업로드를 위해 라이브러리 접근권한이 필요합니다.";
> p1; 마찬가지로 앱을 실행했을 때, 권한을 물어보지 않는 것 같습니다. 확인이 필요합니다.


으악! 코드가 분실되었군요! 감사합니다! 2e248f3

2022-10-25 07:16 UTC, CreoHwan commented on Samsam/Info.plist
> +	<string>사진 업로드를 위해 라이브러리 접근권한이 필요합니다.</string>
> p1; 마찬가지로 앱을 실행했을 때, 권한을 물어보지 않는 것 같습니다. plist에 대한 확인이 필요할 것 같아요.


으악! 코드가 분실되었군요! 감사합니다! 2e248f3

2022-10-25 07:19 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> +    var imgItems:[PreviewItem] = [PreviewItem(name: 0, image: UIImage(named: "CameraBTN"))]
> > > p1; 현재 이미지 버튼을 위한 기본 버튼 이미지가 에셋으로 들어가 있는 것 같습니다. 해당 부분은 에셋이 아니라 기본 컴포넌트로도 똑같이 만들 수 있을 것 같은데, 기본 컴포넌트를 활용하는 것이 더 좋을 것 같습니다.
> > 
> > 
> > 맞습니다! cell 안에 버튼이 있기 때문에, 피그마에서 이미지를 가져와서, 그걸 사용했습니다! 이미지가 아니면 해당 부분은 처리가 어려울 것 같다고 판단했습니다! 에셋이 아니라 기본 컴포넌트를 이용하여 버튼 이미지를 만들 수 있나요??!
> 
> 사진 추가에 대해서는 잘 모르지만, 버튼에 이미지를 넣는 방법도 생각해볼 수 있을 것 같습니다.

cell 안에 버튼이 들어가면 작동이 안되어서 UIImageView로 넣었습니다!

2022-10-25 08:59 UTC, taek0622 commented on Samsam.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_NSPhotoLibraryUsageDescription = "사진 업로드를 위해 라이브러리 접근권한이 필요합니다.";
> > p1; plist가 정상 동작하고 있는게 맞을까요? 앱을 실행했을 때, 권한을 물어보지 않는 것 같습니다.
> 
> 으악! 코드가 분실되었군요! 감사합니다! [2e248f3](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/2e248f3883f0cccad1db2d378831f29306f0b816)

확인했습니다. 해당 리뷰 리졸브합니다.

2022-10-25 08:59 UTC, taek0622 commented on Samsam.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_NSPhotoLibraryUsageDescription = "사진 업로드를 위해 라이브러리 접근권한이 필요합니다.";
> > p1; 마찬가지로 앱을 실행했을 때, 권한을 물어보지 않는 것 같습니다. 확인이 필요합니다.
> 
> 으악! 코드가 분실되었군요! 감사합니다! [2e248f3](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/2e248f3883f0cccad1db2d378831f29306f0b816) 사진 저장은 사실 제가 추가한 것이 아니라, 에디가 추가했었는데, 저번에 같이 보았던 오류때문에 이렇게 뜬 것 같습니다!

확인했습니다. 해당 리뷰 리졸브합니다.

2022-10-25 08:59 UTC, taek0622 commented on Samsam/Info.plist
> +	<string>사진 업로드를 위해 라이브러리 접근권한이 필요합니다.</string>
> > p1; 마찬가지로 앱을 실행했을 때, 권한을 물어보지 않는 것 같습니다. plist에 대한 확인이 필요할 것 같아요.
> 
> 으악! 코드가 분실되었군요! 감사합니다! [2e248f3](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/2e248f3883f0cccad1db2d378831f29306f0b816)

확인했습니다. 해당 리뷰 리졸브합니다.

2022-10-25 09:00 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +        navigationController?.setNavigationBarHidden(false, animated: false)
> df59bae

확인했습니다. 해당 리뷰 리졸브합니다.

2022-10-25 09:06 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +        if numberOfItem > 3 {
> > 질문; 이 부분을 numberOfItem을 global scope로 설정한 뒤, 그 값을 갱신해서 if문을 적용하는 방법 밖에 없었을까요? indexPath에는 마지막 노드의 index를 가져오는 방법이 있는 것으로 알고 있습니다. 해당 부분을 이용해서 다른 방법으로 불러오는 방법은 없었을까요? 혹은 배열의 요소 개수를 새는 방법도 있었을 것 같네요.
> 
> 그런 방법으로 카운트는 가능합니다! 그런데 cell 개수가 5개가 되면, 버튼 cell이 빠지면서 4개로 바뀌게 됩니다! 이를 고려하여 조건문을 만드는 것이 까다로워져서 따로 뺐습니다!

이 부분에 대해서는 조금 더 생각이 필요할 것 같습니다.
우선은 이대로 진행해도 무리가 없을 것 같고, 우선 순위가 아닌 것 같아 이 리뷰는 다음에 생각해보는 걸로 하고 넘어가겠습니다.

2022-10-25 09:10 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +    var imgItems:[PreviewItem] = [PreviewItem(name: 0, image: UIImage(named: "CameraBTN"))]
> > > > p1; 현재 이미지 버튼을 위한 기본 버튼 이미지가 에셋으로 들어가 있는 것 같습니다. 해당 부분은 에셋이 아니라 기본 컴포넌트로도 똑같이 만들 수 있을 것 같은데, 기본 컴포넌트를 활용하는 것이 더 좋을 것 같습니다.
> > > 
> > > 
> > > 맞습니다! cell 안에 버튼이 있기 때문에, 피그마에서 이미지를 가져와서, 그걸 사용했습니다! 이미지가 아니면 해당 부분은 처리가 어려울 것 같다고 판단했습니다! 에셋이 아니라 기본 컴포넌트를 이용하여 버튼 이미지를 만들 수 있나요??!
> > 
> > 
> > 사진 추가에 대해서는 잘 모르지만, 버튼에 이미지를 넣는 방법도 생각해볼 수 있을 것 같습니다.
> 
> cell 안에 버튼이 들어가면 작동이 안되어서 UIImageView로 넣었습니다! 시스템 이미지를 사용하면 시스템 이미지 크기 조정, 색갈 변경 이후 cell.backgroundcolor(extension에서 해당 cell만 바꿔주든지, 혹은 어차피 이미지를 씌우니깐 다른 cell 자체 background를 회색으로 주든지)까지 다 구현해야 하는데, 그것 보다는 asset에 있는 이미지를 사용하는 것이 더 편할 것 같다는 생각이 듭니다!

현재 UIImageView를 버튼처럼 보이게 해서 이 방식 밖에 답이 없어 보이는데, `UIImagePickerController` 같은 이미지를 선택할 수 있는 기본 컴포넌트를 두고, UIImageView를 사용한 이유가 따로 있을까요?
현재와 같은 방식으로 했을 때는 확실이 Asset에 있는 이미지를 사용하는 것 외에는 딱히 좋은 아이디어가 떠오르지 않습니다.
하지만, Asset을 계속해서 끌어와야해서 이게 좋은 해답인지는 조금 생각해봐야할 것 같습니다.

2022-10-25 10:37 UTC, JUNY0110 commented on Samsam/ViewController/PostingImageViewController.swift
> +    var imgItems:[PreviewItem] = [PreviewItem(name: 0, image: UIImage(named: "CameraBTN"))]
미뉴의 의견처럼 해당 방식이 좋은 방식이라고 생각하지는 않지만, 현재 최선이라면 저는 괜찮다고 생각합니다.
추후 리팩토링을 통해 수정하는 방향으로 가고 데이터 링크를 하는 것이 어떨까라는 의견입니다.

2022-10-26 06:30 UTC, taek0622 approved these changes
고생하셨습니다.
두 가지 수정이 필요한 부분이 보이는데, 이 부분은 당장 하지 않아도 될 것 같아서 추후에 수정하는 쪽으로 하는 걸로 해요~

2022-10-26 07:13 UTC, creohwan commented on Samsam/ViewController/PostingImageViewController.swift
> +    var imgItems:[PreviewItem] = [PreviewItem(name: 0, image: UIImage(named: "CameraBTN"))]
다음 리팩토링 때 고민하여 구현해보겠습니다!

2022-10-26 07:14 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> +        if numberOfItem > 3 {
다음 리팩토링 때 고민하고 구현해보겠습니다!

2022-10-26 07:14 UTC, merged