[Design] 방생성 완료 뷰 Layout 생성 및 기능 구현
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #63
Opened 2022-10-26 01:18 UTC by CreoHwan

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 방생성 완료 뷰 Layout 생성 및 기능 구현

## Key Changes 🔥 (주요 구현/변경 사항)
- Layout 생성
- 초대 코드 클릭시 복사 기능

## ToDo 📆 (남은 작업)
- [ ] 디자인 고려해서 다시 뷰를 짜야할 것 같습니다

## ScreenShot 📷 (참고 사진)
![Simulator Screen Recording - iPhone 14 - 2022-10-26 at 10 17 27](https://user-images.githubusercontent.com/92836045/197912011-fb5d37a2-3d94-4811-b06b-c2c3902eac2f.gif)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 제가 임의로 복사 완료시, 밑에 문구를 띄웠는데, 피드백 부탁드립니다. 감사합니다!

## Reference 🔗

## Close Issues 🔒 (닫을 Issue)
Close #56

2022-10-26 03:44 UTC, taek0622 requested changes
고생하셨습니다.
토스트 같은 재밌는 기능이 추가되었네요.
수정이 필요해보이는 부분과 질문 몇개 코멘트 남겼습니다. 확인 부탁드려요~

2022-10-26 03:44 UTC, ikanic commented on Samsam/ViewController/RoomCodeViewController.swift
> +var code = "ASD12d"
p1;
임시 코드이긴 합니다만, 전역 변수 설정은 지양하는 것이 좋을 것 같습니다.

자세한 내용에 대해서는 아래 레퍼런스의 댓글을 보시면 좋을 것 같습니다.
해당 글만으로 왜 전역 변수를 지양하는 것이 좋은지 잘 이해가 가지 않는다면 더 좋은 레퍼런스를 찾아보셔도 좋을 것 같아요.

- [Apple Developer Forums - How do I make a variable accessible across my project?](https://developer.apple.com/forums/thread/98423)

2022-10-26 03:44 UTC, taek0622 commented on Samsam/ViewController/RoomCodeViewController.swift
> +    }(UIImageView())
p1;
이 이미지 뷰는 어디에 사용되는 걸까요?
화면상으로 보았을때 UIImageView로 보이는 화면이 없는 것 같습니다.

2022-10-26 03:44 UTC, taek0622 commented on Samsam/ViewController/RoomCodeViewController.swift
> +        let attachmentString = NSAttributedString(attachment: attachment)
질문;
이미지를 UILabel에 포함시킨 이유가 따로 있을까요?
UILabel과 UIImageView를 Stack에 넣는 방법도 있었을 것 같은데, UILabel에 전부 포함시킨 특별한 이유가 있는지 궁금합니다~

2022-10-26 03:44 UTC, taek0622 commented on Samsam/ViewController/RoomCodeViewController.swift
> +    }
p3;
Toast를 직접 구현하셨네요. 사실 Toast 메시지 자체가 iOS에서 그리 권장되는 방법이 아닌지라 이걸 적용시키는게 맞나 고민되긴 합니다.
다만, 사용자에게 메시지가 복사되었다는 것을 알리기 위한 수단으로 토스트만큼 사용자 경험을 방해하지 않으면서 보여주는 방법도 없는 것 같아서 이 부분에 대해서는 논의가 필요할 것 같네요.

Toast 메시지 자체로만 보자면 배경 색이 너무 회색빛이 강한 것 같습니다. 텍스트 컬러를 white로 하고 백그라운드 컬러를 black에 opacity를 약간 죽여서 보여주는게 더 좋지 않을까 싶네요.

2022-10-26 04:04 UTC, JUNY0110 requested changes
사소한 컨벤션으로 p2를 드렸으나, 재밌는 코드가 많고 배울 게 많았던 것 같습니다.
고생하셨습니다.

2022-10-26 04:04 UTC, JUNY0110 commented on Samsam/ViewController/RoomCodeViewController.swift
> +
p3.
패딩값을 직접 숫자로 주게 되면, 기종에 따라 위치가 달라지게 됩니다.
view의 중심에서 상단으로 얼마만큼 위로 띄우거나, 비율값으로 주는 등 다른 방법을 생각해보심이 좋을 것 같습니다.

2022-10-26 04:04 UTC, JUNY0110 commented on Samsam/ViewController/RoomCodeViewController.swift
> +        let attachmentString = NSAttributedString(attachment: attachment)
재밌는 코드네요. 여러 view를 사용하지 않고 한 코드로 끝낼 수 있어 좋은 것 같습니다.

2022-10-26 04:04 UTC, JUNY0110 commented on Samsam/ViewController/RoomCodeViewController.swift
> +        UIPasteboard.general.string = code
복사하는 코드가 단 한줄짜리 코드였군요. 잘 배워갑니다.

2022-10-26 04:04 UTC, JUNY0110 commented on Samsam/ViewController/RoomCodeViewController.swift
> +    }
p2.
들여쓰기가 잘못잡혀있는 것 같습니다. 확인부탁드려요

p5.
알림의 등장이 너무 서서히 나오는 것 같습니다.
알림의 등장은 duration을 0.5 낮추거나 instant로 즉각호출하고 , 종료는 2로 늘려 빠르게 확인하고 천천히 사라지는 방식이 어떨까요?

2022-10-26 04:04 UTC, JUNY0110 commented on Samsam/ViewController/RoomCodeViewController.swift
> +    }
> p3; Toast를 직접 구현하셨네요. 사실 Toast 메시지 자체가 iOS에서 그리 권장되는 방법이 아닌지라 이걸 적용시키는게 맞나 고민되긴 합니다. 다만, 사용자에게 메시지가 복사되었다는 것을 알리기 위한 수단으로 토스트만큼 사용자 경험을 방해하지 않으면서 보여주는 방법도 없는 것 같아서 이 부분에 대해서는 논의가 필요할 것 같네요.
> 
> Toast 메시지 자체로만 보자면 배경 색이 너무 회색빛이 강한 것 같습니다. 텍스트 컬러를 white로 하고 백그라운드 컬러를 black에 opacity를 약간 죽여서 보여주는게 더 좋지 않을까 싶네요.

컬러에 대한 얘기는 28일 이후 진행하면 좋을 것 같습니다. 이미 대부분의 뷰에 컬러가 반영되지 않았기 때문에, 이 부분에 대해서도 디자인을 확정하면서 함께 진행하면 좋을 것 같네요.

2022-10-26 04:04 UTC, JUNY0110 commented on Samsam/ViewController/RoomCodeViewController.swift
> +        navigationController?.navigationBar.topItem?.title = "생성 완료"
p5. 
현재 페이지에서는 적용되지 않는 부분이지만, navigationController.navigationBar.topItem.title로 작성 시, 네비게이션 뒤로가기 버튼을 클릭하면 "생성 완료'가 그대로 이전 뷰의 타이틀로 잡히는 문제가 있습니다. 
navigationItem.title로 작성을 하면 해당 부분의 문제가 해결되니 참고하시면 좋을 것 같습니다.

2022-10-26 07:23 UTC, CreoHwan commented on Samsam/ViewController/RoomCodeViewController.swift
> +var code = "ASD12d"
> Member

감사합니다! dac9e44

2022-10-26 07:24 UTC, CreoHwan commented on Samsam/ViewController/RoomCodeViewController.swift
> +    }(UIImageView())
> p1; 이 이미지 뷰는 어디에 사용되는 걸까요? 화면상으로 보았을때 UIImageView로 보이는 화면이 없는 것 같습니다.

화면 가운데에 모여 있는 친구들을 다 contentViwe에 넣었습니다! 위치 조정 하는 것이 편할 것 같아서 그랬습니다!

2022-10-26 07:25 UTC, CreoHwan commented on Samsam/ViewController/RoomCodeViewController.swift
> +        let attachmentString = NSAttributedString(attachment: attachment)
> 질문; 이미지를 UILabel에 포함시킨 이유가 따로 있을까요? UILabel과 UIImageView를 Stack에 넣는 방법도 있었을 것 같은데, UILabel에 전부 포함시킨 특별한 이유가 있는지 궁금합니다~

단순하게 이미지가 UILabel Text에서 다룰 수 있다면 편할 것 같아서 했습니다! Stack 방법도 있군요!

2022-10-26 07:26 UTC, CreoHwan commented on Samsam/ViewController/RoomCodeViewController.swift
> +    }
> > p3; Toast를 직접 구현하셨네요. 사실 Toast 메시지 자체가 iOS에서 그리 권장되는 방법이 아닌지라 이걸 적용시키는게 맞나 고민되긴 합니다. 다만, 사용자에게 메시지가 복사되었다는 것을 알리기 위한 수단으로 토스트만큼 사용자 경험을 방해하지 않으면서 보여주는 방법도 없는 것 같아서 이 부분에 대해서는 논의가 필요할 것 같네요.
> > Toast 메시지 자체로만 보자면 배경 색이 너무 회색빛이 강한 것 같습니다. 텍스트 컬러를 white로 하고 백그라운드 컬러를 black에 opacity를 약간 죽여서 보여주는게 더 좋지 않을까 싶네요.
> 
> 컬러에 대한 얘기는 28일 이후 진행하면 좋을 것 같습니다. 이미 대부분의 뷰에 컬러가 반영되지 않았기 때문에, 이 부분에 대해서도 디자인을 확정하면서 함께 진행하면 좋을 것 같네요.

좋습니다!

2022-10-26 07:45 UTC, CreoHwan commented on Samsam/ViewController/RoomCodeViewController.swift
> +        UIPasteboard.general.string = code
> 복사하는 코드가 단 한줄짜리 코드였군요. 잘 배워갑니다.

감사합니다!

2022-10-26 07:48 UTC, taek0622 commented on Samsam/ViewController/RoomCodeViewController.swift
> +var code = "ASD12d"
> > Member
> 
> 감사합니다! [dac9e44](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/dac9e44ffd2582839812937a3ebb4e662220916f) [eadf776](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/eadf77667562fc9f2e62cd4cd27c082d0e254035)

확인했습니다. 리뷰 리졸브합니다.

2022-10-26 07:52 UTC, taek0622 commented on Samsam/ViewController/RoomCodeViewController.swift
> +        let attachmentString = NSAttributedString(attachment: attachment)
> > 질문; 이미지를 UILabel에 포함시킨 이유가 따로 있을까요? UILabel과 UIImageView를 Stack에 넣는 방법도 있었을 것 같은데, UILabel에 전부 포함시킨 특별한 이유가 있는지 궁금합니다~
> 
> 단순하게 이미지가 UILabel Text에서 다룰 수 있다면 편할 것 같아서 했습니다! Stack 방법도 있군요!

이미지에만 특별한 기능이 있는 것이 아니라면 현재와 같이 레이블 안에 포함시키는 것도 충분히 좋은 코드인 것 같습니다.
stack에 넣는 경우는 텍스트와 이미지가 서로 다른 동작을 할 경우에 참고하셔서 사용하시면 좋을 것 같네요.

2022-10-26 07:56 UTC, taek0622 commented on Samsam/ViewController/RoomCodeViewController.swift
> +    }
> > p3; Toast를 직접 구현하셨네요. 사실 Toast 메시지 자체가 iOS에서 그리 권장되는 방법이 아닌지라 이걸 적용시키는게 맞나 고민되긴 합니다. 다만, 사용자에게 메시지가 복사되었다는 것을 알리기 위한 수단으로 토스트만큼 사용자 경험을 방해하지 않으면서 보여주는 방법도 없는 것 같아서 이 부분에 대해서는 논의가 필요할 것 같네요.
> > Toast 메시지 자체로만 보자면 배경 색이 너무 회색빛이 강한 것 같습니다. 텍스트 컬러를 white로 하고 백그라운드 컬러를 black에 opacity를 약간 죽여서 보여주는게 더 좋지 않을까 싶네요.
> 
> 컬러에 대한 얘기는 28일 이후 진행하면 좋을 것 같습니다. 이미 대부분의 뷰에 컬러가 반영되지 않았기 때문에, 이 부분에 대해서도 디자인을 확정하면서 함께 진행하면 좋을 것 같네요.

컬러는 후에 이야기 해도 좋을 것 같네요. 다만 토스트 사용 자체에 대해서는 논의가 빠르게 필요해보입니다.

2022-10-26 07:58 UTC, taek0622 commented on Samsam/ViewController/RoomCodeViewController.swift
> +    }(UIImageView())
> > p1; 이 이미지 뷰는 어디에 사용되는 걸까요? 화면상으로 보았을때 UIImageView로 보이는 화면이 없는 것 같습니다.
> 
> 화면 가운데에 모여 있는 친구들을 다 contentViwe에 넣었습니다! 위치 조정 하는 것이 편할 것 같아서 그랬습니다!

해당 부분이 컴포넌트들을 가운데에 모으기 위함이라면, UIImageView보다는 UIView가 더 용도에 맞을 것 같습니다.

2022-10-26 08:04 UTC, CreoHwan commented on Samsam/ViewController/RoomCodeViewController.swift
> +    }(UIImageView())
> > > p1; 이 이미지 뷰는 어디에 사용되는 걸까요? 화면상으로 보았을때 UIImageView로 보이는 화면이 없는 것 같습니다.
> > 
> > 
> > 화면 가운데에 모여 있는 친구들을 다 contentViwe에 넣었습니다! 위치 조정 하는 것이 편할 것 같아서 그랬습니다!
> 
> 해당 부분이 컴포넌트들을 가운데에 모으기 위함이라면, UIImageView보다는 UIView가 더 용도에 맞을 것 같습니다.

감사합니다! 3e02365

2022-10-26 08:04 UTC, CreoHwan commented on Samsam/ViewController/RoomCodeViewController.swift
> +
> p3. 패딩값을 직접 숫자로 주게 되면, 기종에 따라 위치가 달라지게 됩니다. view의 중심에서 상단으로 얼마만큼 위로 띄우거나, 비율값으로 주는 등 다른 방법을 생각해보심이 좋을 것 같습니다.

감사합니다! 3e02365

2022-10-26 08:05 UTC, CreoHwan commented on Samsam/ViewController/RoomCodeViewController.swift
> +        let attachmentString = NSAttributedString(attachment: attachment)
> > > 질문; 이미지를 UILabel에 포함시킨 이유가 따로 있을까요? UILabel과 UIImageView를 Stack에 넣는 방법도 있었을 것 같은데, UILabel에 전부 포함시킨 특별한 이유가 있는지 궁금합니다~
> > 
> > 
> > 단순하게 이미지가 UILabel Text에서 다룰 수 있다면 편할 것 같아서 했습니다! Stack 방법도 있군요!
> 
> 이미지에만 특별한 기능이 있는 것이 아니라면 현재와 같이 레이블 안에 포함시키는 것도 충분히 좋은 코드인 것 같습니다. stack에 넣는 경우는 텍스트와 이미지가 서로 다른 동작을 할 경우에 참고하셔서 사용하시면 좋을 것 같네요.

감사합니다!

2022-10-26 08:06 UTC, CreoHwan commented on Samsam/ViewController/RoomCodeViewController.swift
> +    }
> 

좋습니다!

2022-10-26 08:12 UTC, CreoHwan commented on Samsam/ViewController/RoomCodeViewController.swift
> +    }
> p2. 들여쓰기가 잘못잡혀있는 것 같습니다. 확인부탁드려요
> 
> p5. 알림의 등장이 너무 서서히 나오는 것 같습니다. 알림의 등장은 duration을 0.5 낮추거나 instant로 즉각호출하고 , 종료는 2로 늘려 빠르게 확인하고 천천히 사라지는 방식이 어떨까요?

048c0e2 좋은 의견 감사합니다!

2022-10-26 08:15 UTC, CreoHwan commented on Samsam/ViewController/RoomCodeViewController.swift
> +        navigationController?.navigationBar.topItem?.title = "생성 완료"
> 



> p5. 현재 페이지에서는 적용되지 않는 부분이지만, navigationController.navigationBar.topItem.title로 작성 시, 네비게이션 뒤로가기 버튼을 클릭하면 "생성 완료'가 그대로 이전 뷰의 타이틀로 잡히는 문제가 있습니다. navigationItem.title로 작성을 하면 해당 부분의 문제가 해결되니 참고하시면 좋을 것 같습니다.

아하! 감사합니다! d4f6fda

2022-10-26 08:26 UTC, CreoHwan commented
@taek0622 @JUNY0110 확인부탁드립니다!

2022-10-26 08:40 UTC, taek0622 commented on Samsam/ViewController/RoomCodeViewController.swift
> +    }(UIImageView())
> > > > p1; 이 이미지 뷰는 어디에 사용되는 걸까요? 화면상으로 보았을때 UIImageView로 보이는 화면이 없는 것 같습니다.
> > > 
> > > 
> > > 화면 가운데에 모여 있는 친구들을 다 contentViwe에 넣었습니다! 위치 조정 하는 것이 편할 것 같아서 그랬습니다!
> > 
> > 
> > 해당 부분이 컴포넌트들을 가운데에 모으기 위함이라면, UIImageView보다는 UIView가 더 용도에 맞을 것 같습니다.
> 
> 감사합니다! [3e02365](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/3e0236569020f073925cd6f9e500060619ec798a)

확인했습니다. 리뷰 리졸브합니다.

2022-10-27 01:23 UTC, taek0622 reviewed
고생하셨습니다.
많은 기능이 있는 뷰가 아니라서 간단할거라 생각했는데, 생각보다 컴포넌트가 많았네요.
이름도 한번 다 바꾸시느라 고생하셨어요.

2022-10-27 01:23 UTC, taek0622 commented on Samsam/ViewController/RoomCodeViewController.swift
> +            height: 70
p1;
현재 해당 문제에 대해 인지하였으나, 당장 해결하기에 우선순위가 아니라고 판단하여 다음에 다시 확인하여 수정하는 걸로 결정했습니다.

2022-10-27 01:23 UTC, taek0622 commented on Samsam/ViewController/RoomCodeViewController.swift
> +    }
질문;
여기는 무엇을 위한 코드일까요?
UIView가 직접 들어가는 이유도 궁금합니다.

2022-10-27 05:33 UTC, CreoHwan commented on Samsam/ViewController/RoomCodeViewController.swift
> +    }
> 질문; 여기는 무엇을 위한 코드일까요? UIView가 직접 들어가는 이유도 궁금합니다.

animate 속성에 의해, 사용하려면 필요합니다!

2022-10-27 06:25 UTC, ikanic commented on Samsam/ViewController/RoomCodeViewController.swift
> +    }
> > 질문; 여기는 무엇을 위한 코드일까요? UIView가 직접 들어가는 이유도 궁금합니다.
> 
> animate 속성에 의해, 사용하려면 필요합니다!

확인했습니다~

2022-10-27 06:26 UTC, taek0622 approved these changes
고생하셨습니다.

2022-10-27 09:37 UTC, CreoHwan commented
@JUNY0110 확인 부탁드립니다!

2022-10-27 13:30 UTC, JUNY0110 commented on Samsam/ViewController/RoomCodeViewController.swift
> +        navigationController?.navigationBar.topItem?.title = "생성 완료"
> > p5. 현재 페이지에서는 적용되지 않는 부분이지만, navigationController.navigationBar.topItem.title로 작성 시, 네비게이션 뒤로가기 버튼을 클릭하면 "생성 완료'가 그대로 이전 뷰의 타이틀로 잡히는 문제가 있습니다. navigationItem.title로 작성을 하면 해당 부분의 문제가 해결되니 참고하시면 좋을 것 같습니다.
> 
> 아하! 감사합니다! [d4f6fda](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/d4f6fda14714fccd34e83e47081770aa8ae6630b)

확인했습니다! 저도 이 부분은 구현상으로는 알지만, '왜' 저렇게 되는지는 잘 몰라서 테스트 플라이트 이후 navigationBar.topItem.title과 navigationItem.title에 대해 공부해봐야겠어요.

2022-10-27 13:31 UTC, JUNY0110 approved these changes
확인했습니다! 고생하셨습니다.

2022-10-27 14:20 UTC, merged