Feat/87 multi image selection
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #93
Opened 2022-11-03 06:33 UTC by CreoHwan

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 기존에는 최근에 선택한 이미지가 밑으로 쌓임
- 기존 이미지 선택시 사진 변경만 가능, 삭제 불가능
- 기존에는 ImagePicker와 Phpicker 혼용
- 기존에는 사진 선택 없이도 다음 뷰로 넘어가짐
- 기존에는 사진 권한 설정을 잘 못했음

## Key Changes 🔥 (주요 구현/변경 사항)
- 최근에 선택한 이미지가 위쪽에 업로드 되도록 수정
- 기존 이미지 선택 시, 이미지 변경 or 이미지 삭제 기능 추가
- Phpicker만 사용, HEIF 문제 해결
- 이미지를 하나도 선택하지 않을 시, 다음 뷰로 넘어가지 않도록 기능 추가
- 사진 권한 설정
- 사진 불러오기 실패 시 알림창 띄우기

## ToDo 📆 (남은 작업)
- [ ] 기존 이미지가 누르고 싶게 생기도록 UI 변경에 관한 논의 필요

## ScreenShot 📷 (참고 사진)
- 기본 플로우
![기본 플로우](https://user-images.githubusercontent.com/92836045/199659725-a62dc2d4-d1bb-4c9a-b2ec-ab002d1911b2.gif)

- 이미지 불러오기 실패
![선택 불가](https://user-images.githubusercontent.com/92836045/199659755-b566526f-c9da-42b3-baf3-b1656ec86a7c.gif)

- 이미지 선택 없이 넘어갈 때
![선택 없이 넘어갈 때](https://user-images.githubusercontent.com/92836045/199659788-8473ce3b-9a26-40eb-8aab-dbef7a8411b4.gif)

- 권한 설정 거부한 상태에서, 이미지 업로드 버튼을 눌렀을 때
![처음부터 권한 설정](https://user-images.githubusercontent.com/92836045/199659832-4c8606e0-9c44-4c43-a3b9-ed572aee03d8.gif)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 섹션을 나누는 아주 좋은 방법을 알려주셔서 감사합니다.

- 실제 기기에서 확인한 결과, 권한 설정이 되어 있지 않아도, 앨범이 열림을 확인했습니다. 매번 확인해야할 것 같습니다.  하지만 이미지가 업로드 된 상태에서, 설정에서 권한을 거부로 바꾸고, 다시 앱으로 돌아오면, 기존의 이미지는 삭제됩니다. 그래서 권한 체크는 업로드 포토에만 했습니다.

- 실제 기기에서 확인한 결과, HEIF오류는 시뮬레이터에서만 발생합니다. 실제 기기에서는 잘 작동합니다.

- uploadPhoto와 changePhoto 에서 extension picker로 넘어가는 경우, 인자를 전달할 방법이 없어서, 어쩔 수 없이 ChangeNUM 변수 하나를 생성했습니다.

- extension에서 동일한 코드가 많이 보입니다. 
<img width="874" alt="스크린샷 2022-11-03 15 29 16" src="https://user-images.githubusercontent.com/92836045/199659377-9d51f6dd-d05b-4abc-9993-d9ec726d5d4d.png">
거의 다 똑같고, DispatchQueue.main.async만 다릅니다. 처음엔 함수를 2개 생성하여, if문을 돌려서, 업로드면 업로드함수, change면 change함수를 넣으려고 했습니다. 현재는 처음에 if문을 돌려서 판단하고 있습니다. (changeNUM = nil인 경우가 업로드입니다. else가 change입니다.) 하지만 고민해보니, 맨 처음에 if문을 한번만 돌리는 것이 효율적이라고 판단했습니다. 왜냐하면, 안쪽으로 함수를 선언해서 넣어버리면,  for result in results.reversed(), 즉 for문 마다 if문을 매번 돌려야하기 때분입니다.

## Reference 🔗
- sfsymbol에 관하여 reference 남깁니다!
- https://stackoverflow.com/questions/58256044/how-to-change-sf-symbol-icon-color-in-uikit
- https://rldd.tistory.com/391

## Close Issues 🔒 (닫을 Issue)
Close #No.

2022-11-03 07:51 UTC, JUNY0110 requested changes
PostingImageViewcontroller에 exampleImage라는 view가 미사용된 상태로 남아있습니다. 오래 전 코드라 리뷰를 남길 수 없어 코멘트로 남깁니다.

굉장히 많은 고민을 한 코드같네요. 고생하셨습니다.

2022-11-03 07:51 UTC, JUNY0110 commented on Samsam/ViewController/PostingImageButtonCell.swift
> +    }(UIImageView())
굿! 드디어 에셋에서 탈출했군요 ㅋㅋㅋ
symbol이미지에 대한 사이즈 조정을 이렇게 할 수 있는지는 처음 알았네요 감사합니다.

2022-11-03 07:51 UTC, JUNY0110 commented on Samsam/ViewController/PostingImageViewController.swift
p3.
Delegate가 없어도 정상작동할 것 같네요! DelegateFlowLayout이 대체해주고 있는 것 같습니다.

2022-11-03 07:51 UTC, JUNY0110 commented on Samsam/ViewController/PostingImageViewController.swift
>          }
설정창으로 이동하기 위한 URL코드인거겠죠?? 잘 배워갑니다.

Q.
`Bundle.main.infoDictionary!["CFBundleName"]`는 무슨 의미일까요?
appName이 plist의 `CFBundleName`와 일치하는지 확인하는 코드일까요?

2022-11-03 07:51 UTC, JUNY0110 commented on Samsam/ViewController/PostingImageViewController.swift
> +        changeNUM = nil
Q.
업로드를 할 때 changeNum = nil이 있어야하는 이유가 무엇일까요?

2022-11-03 07:51 UTC, JUNY0110 commented on Samsam/ViewController/PostingImageViewController.swift
> +        generator.impactOccurred()
Q.
generator는 어떤 용도의 코드일까요? 삭제해도 동일한 동작을 하여 질문합니다.

2022-11-03 07:51 UTC, JUNY0110 commented on Samsam/ViewController/PostingImageViewController.swift
> +            makeAlert(title: "",message: "사진을 최소 하나 이상 선택해야 합니다")
p4.
사진을 한 장 이상 선택해야 합니다.
라는 문구가 더 자연스러울 것 같습니다

2022-11-03 07:51 UTC, JUNY0110 commented on Samsam/ViewController/PostingWritingView.swift
> +//        }
p2.
주석을 남겨둔 이유가 있을까요??

2022-11-03 07:51 UTC, JUNY0110 commented on Samsam/ViewController/PostingWritingView.swift
> +    var photoImages: [cellItem]?
p2.
해당 변수는 사용되고 있지 않은 것 같습니다.

2022-11-03 08:16 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> +        changeNUM = nil
> Q. 업로드를 할 때 changeNum = nil이 있어야하는 이유가 무엇일까요?

extension에서 if문 조건이 changeNUM = nil 입니다! 업로드일 경우를 나누기 위해서 제가 그런 조건을 만들었습니다. 최소한의 프로퍼티 선언을 위해서 changeNUM을 이용했습니다!

2022-11-03 08:20 UTC, taek0622 requested changes
고생하셨습니다.
일부 수정이 필요한 부분에 리뷰남겼습니다.
또, 로직 부분은 한번에 확인하기 어려워 2번에 걸쳐서 다시 리뷰하겠습니다.

2022-11-03 08:20 UTC, ikanic commented on Samsam/ViewController/PostingImageButtonCell.swift
> +        $0.image = image
p4;
이 부분은 `$0.image = UIImage(systemName: "plus.circle", withConfiguration: imageConfig)?.withTintColor(.white, renderingMode: .alwaysOriginal)`처럼 바꿀 수 있을 것 같습니다.

2022-11-03 08:20 UTC, ikanic commented on Samsam/ViewController/PostingImageViewController.swift
> +struct cellItem {
p2;
struct의 이름은 대문자로 시작하는 규칙이 있습니다. 대문자로 시작하도록 수정 부탁드려요~

2022-11-03 08:20 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +
p1;
불필요한 공백이 들어가있네요. 삭제 부탁드립니다~

2022-11-03 08:20 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +        generator.impactOccurred()
> Q. generator는 어떤 용도의 코드일까요? 삭제해도 동일한 동작을 하여 질문합니다.

제가 아는 바로 UIImpactFeedbackGenerator는 HapticFeedback을 위한 부분인 것으로 알고 있습니다.
다만, 저도 궁금한 것은 이 부분에 HapticFeedback을 준 이유가 있을까요?

에디를 위한 UIImpactFeedbackGenerator 자체에 대한 레퍼런스도 아래에 첨부합니다.
- [Apple Developer Document - [UIKit] UIImpactFeedbackGenerator](https://developer.apple.com/documentation/uikit/uiimpactfeedbackgenerator)
- [ZeddiOS - iOS ) Haptic Feedback](https://zeddios.tistory.com/726)

2022-11-03 08:20 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
>          }
> 

이 부분에 대해 제가 알고 있는 내용을 말씀드려보자면 Bundle.main.infoDictionary!["CFBundleName"]은 현재 앱의 BundleName을 가져오는 부분입니다. 아래에 보시면 message에서 앱 네임을 불러와서 "기와집이 카메라에 접근이 허용되어 있지 않습니다."를 출력하려고 하신 것 같아보여요.
다만, 현재 코드에서 문제가 될만한 부분을 보자면 BundleName을 불러오면 정말 앱의 BundleName을 불러오게 됩니다. 예를 들어 저희 프로젝트 이름이 Samsam이라면 Samsam을 불러오게 되겠죠.
만약 저희 프로젝트 이름을 giwazip으로 변경한다면 BundleName을 불러와도 됩니다만, 저희 앱이름이 한글로 "기와집"을 표시하고 싶다면 BundleName이 아니라 DisplayName을 불러와야하기 때문에 해당 부분은 `CFBundlName`이 아닌, `CFBundleDisplayName`을 불러오는 것이 더 바람직해 보입니다.

해당 부분의 차이에 대한 간단한 레퍼런스를 아래에 하나 첨부합니다.
- [stack overflow - Get App Name in Swift](https://stackoverflow.com/questions/28254377/get-app-name-in-swift)

2022-11-03 08:20 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +    private var changeNUM: Int?
p1;
changeNum이 nil이 될 경우가 없을 것 같은데, 그렇다면 이 부분은 처음에 0으로 초기화하는 것이 더 좋을 것 같습니다.

2022-11-03 08:20 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +        changeNUM = nil
> Q. 업로드를 할 때 changeNum = nil이 있어야하는 이유가 무엇일까요?

저도 이부분 궁금합니다. 0과 같은 값이 아닌 nil이 되어야하는 이유가 있을까요?

2022-11-03 08:20 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +        if changeNUM == nil {
p1;
changeNUM이 0인 조건으로 변경되어도 될 것 같습니다.
nil 값 사용은 최대한 지양하는 것이 좋을 것 같아요.
또한 해당 부분부터 아래에 나오는 로직은 한번에 확인하기 어려워 2번에 걸쳐서 리뷰하겠습니다.

2022-11-03 08:20 UTC, taek0622 commented on Samsam/ViewController/PostingWritingView.swift
> +    var photoImages: [cellItem]?
p1;
사용되지 않는 변수입니다.
해당 부분이 데이터를 저장하기 위해 다른 뷰에서 데이터를 가져오기 위한 부분이라고 생각했는데, 실제로 사용이 되고 있지 않네요.

2022-11-03 08:20 UTC, taek0622 commented on Samsam/ViewController/PostingWritingView.swift
> +//        }
p1;
불필요한 주석 삭제 부탁드립니다.

2022-11-03 08:59 UTC, taek0622 requested changes
현재 struct의 path를 전혀 사용하고 있지 않습니다만, 코어데이터 구조상 path로 데이터를 저장하게 되어 있어서 테스트가 불가능한 것 같습니다. 해당 부분이 수정되지 않는다면 다른 테스트는 불가능할 것으로 보이네요.

2022-11-03 09:16 UTC, ikanic requested changes
로직 부분에 대하여도 리뷰 남겼습니다.
도중 도중에 아직 확인이 덜 된 부분이 있을 수도 있습니다. 감안하고 봐주시면 감사하겠습니다.

2022-11-03 09:16 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +            }
p1;
이 부분은 결과적으로 다른 부분이 배열에 이미지를 추가하는지, 혹은 배열에 있는 이미지를 변경하는지만 다릅니다.
그렇다면 해당 부분만 If문으로 구분하면 될 것 같네요.
충분히 이것보다 더 간단하게 가능할 것 같습니다.
다만 제가 직접 이 코드를 줄이는 것이 디너한테 과연 도움이 되는 것일까 의문이 들어 아래에 코드를 첨부하나, 접어두겠습니다.
필요하시다면 토글을 열어서 보셔도 좋지만, 보지 않고 디너가 직접 생각해보시는 방법도 좋을 것 같네요.
다만, 현재 제가 이 코드에 대한 완전한 이해를 하고 줄인 것은 아니기 때문에 이것보다 더 좋은 방법이 있을 수도 있으니, 참고 정도로만 사용하시면 좋을 것 같습니다.

<details>
<summary>코드 보기/숨기기</summary>
<div markdown="1">

```swift
for result in results {
            let itemProvider = result.itemProvider
            if itemProvider.canLoadObject(ofClass: UIImage.self) {
                itemProvider.loadObject(ofClass: UIImage.self) { [weak self] (image, error) in
                    DispatchQueue.main.async {
                        guard let image = image as? UIImage else { return }
                        if self!.changeNUM == nil {
                            self?.photoImages.insert(cellItem(image: image), at: 0)
                        } else {
                            self?.photoImages[self!.changeNUM!].image = image as! UIImage
                        }
                        self?.imageCellView.reloadData()
                    }
                    if let error = error {
                        DispatchQueue.main.async {
                            self?.makeAlert(title: "", message: "사진을 불러올 수 없습니다")
                        }
                    }
                }
            }
        }
```

</div>
</details>

2022-11-03 09:18 UTC, taek0622 requested changes
자잘한 스타일 오류 발견해서 추가 수정 요청드립니다.

2022-11-03 09:18 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +            makeAlert(title: "",message: "사진을 최소 하나 이상 선택해야 합니다")
p1;
title과 message 사이에 , 뒤에 오른쪽 공백이 필요합니다.

2022-11-04 01:49 UTC, CreoHwan commented on Samsam/ViewController/PostingImageButtonCell.swift
> +    }(UIImageView())
> 굿! 드디어 에셋에서 탈출했군요 ㅋㅋㅋ symbol이미지에 대한 사이즈 조정을 이렇게 할 수 있는지는 처음 알았네요 감사합니다.

SwiftUI는 간단한데 UIKit은 생각보다 복잡하더라고요!

2022-11-04 01:50 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> +struct cellItem {
> p2; struct의 이름은 대문자로 시작하는 규칙이 있습니다. 대문자로 시작하도록 수정 부탁드려요~

3db06cd 넵 감사합니다!

2022-11-04 01:53 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> +        changeNUM = nil
> > Q. 업로드를 할 때 changeNum = nil이 있어야하는 이유가 무엇일까요?
> 
> 저도 이부분 궁금합니다. 0과 같은 값이 아닌 nil이 되어야하는 이유가 있을까요?

5acd0af 처음에 선언할 때 nil 대신 -1 로 바꿨습니다!

2022-11-04 01:54 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> +            makeAlert(title: "",message: "사진을 최소 하나 이상 선택해야 합니다")
> 사진을 한 장 이상 선택해야 합니다

c1a8485 감사합니다!

2022-11-04 01:55 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> +            makeAlert(title: "",message: "사진을 최소 하나 이상 선택해야 합니다")
> p1; title과 message 사이에 , 뒤에 오른쪽 공백이 필요합니다.

c1a8485 감사합니다!

2022-11-04 01:56 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> +    private var changeNUM: Int?
> 

처음에 선언할 때 nil 대신 -1 로 바꿨습니다!

2022-11-04 01:56 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> +        if changeNUM == nil {
> p1; changeNUM이 0인 조건으로 변경되어도 될 것 같습니다. nil 값 사용은 최대한 지양하는 것이 좋을 것 같아요. 또한 해당 부분부터 아래에 나오는 로직은 한번에 확인하기 어려워 2번에 걸쳐서 리뷰하겠습니다.

처음에 선언할 때 nil 대신 -1 로 바꿨습니다!

2022-11-04 01:57 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> +    private var changeNUM: Int?
> p1; changeNum이 nil이 될 경우가 없을 것 같은데, 그렇다면 이 부분은 처음에 0으로 초기화하는 것이 더 좋을 것 같습니다.

5acd0af 처음에 선언할 때 -1로 바꿨습니다! 감사합니다!

2022-11-04 01:59 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> +
> p1; 불필요한 공백이 들어가있네요. 삭제 부탁드립니다~

1211588 감사합니다!

2022-11-04 02:19 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
>          }
> > 
> 
> 이 부분에 대해 제가 알고 있는 내용을 말씀드려보자면 Bundle.main.infoDictionary!["CFBundleName"]은 현재 앱의 BundleName을 가져오는 부분입니다. 아래에 보시면 message에서 앱 네임을 불러와서 "기와집이 카메라에 접근이 허용되어 있지 않습니다."를 출력하려고 하신 것 같아보여요. 다만, 현재 코드에서 문제가 될만한 부분을 보자면 BundleName을 불러오면 정말 앱의 BundleName을 불러오게 됩니다. 예를 들어 저희 프로젝트 이름이 Samsam이라면 Samsam을 불러오게 되겠죠. 만약 저희 프로젝트 이름을 giwazip으로 변경한다면 BundleName을 불러와도 됩니다만, 저희 앱이름이 한글로 "기와집"을 표시하고 싶다면 BundleName이 아니라 DisplayName을 불러와야하기 때문에 해당 부분은 `CFBundlName`이 아닌, `CFBundleDisplayName`을 불러오는 것이 더 바람직해 보입니다.
> 
> 해당 부분의 차이에 대한 간단한 레퍼런스를 아래에 하나 첨부합니다.
> 
> * [stack overflow - Get App Name in Swift](https://stackoverflow.com/questions/28254377/get-app-name-in-swift)

24d0025 현재는 displayname이 설정되어 있지 않아서, 일단 if문으로 2개를 돌렸습니다! 첫번째는 displayname이고 두번째는 그냥 name으로 뒀습니다!

2022-11-04 02:24 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> +            }
> 

22813e8 저도 고민했던 부분이라... 공감이 됩니다! if문을 돌리는 횟수가 크게 상관이 없을 것 같아서, 코드를 깔끔히 만들었습니다! 감사합니다!

2022-11-04 02:24 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> +            }
> p1; 이 부분은 결과적으로 다른 부분이 배열에 이미지를 추가하는지, 혹은 배열에 있는 이미지를 변경하는지만 다릅니다. 그렇다면 해당 부분만 If문으로 구분하면 될 것 같네요. 충분히 이것보다 더 간단하게 가능할 것 같습니다. 다만 제가 직접 이 코드를 줄이는 것이 디너한테 과연 도움이 되는 것일까 의문이 들어 아래에 코드를 첨부하나, 접어두겠습니다. 필요하시다면 토글을 열어서 보셔도 좋지만, 보지 않고 디너가 직접 생각해보시는 방법도 좋을 것 같네요. 다만, 현재 제가 이 코드에 대한 완전한 이해를 하고 줄인 것은 아니기 때문에 이것보다 더 좋은 방법이 있을 수도 있으니, 참고 정도로만 사용하시면 좋을 것 같습니다.
> 
> 코드 보기/숨기기
> ```swift
> for result in results {
>     let itemProvider = result.itemProvider
>     if itemProvider.canLoadObject(ofClass: UIImage.self) {
>         itemProvider.loadObject(ofClass: UIImage.self) { [weak self] (image, error) in
>             DispatchQueue.main.async {
>                 guard let image = image as? UIImage else { return }
>                 if self!.changeNUM == nil {
>                     self?.photoImages.insert(cellItem(image: image), at: 0)
>                 } else {
>                     self?.photoImages[self!.changeNUM!].image = image as! UIImage
>                 }
>                 self?.imageCellView.reloadData()
>             }
>             if let error = error {
>                 DispatchQueue.main.async {
>                     self?.makeAlert(title: "", message: "사진을 불러올 수 없습니다")
>                 }
>             }
>         }
>     }
> }
> ```

https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/22813e8b924f2fb858f40e36b8378c20fb381637 저도 고민했던 부분이라... 공감이 됩니다! if문을 돌리는 횟수가 크게 상관이 없을 것 같아서, 코드를 깔끔히 만들었습니다! 감사합니다!

2022-11-04 02:27 UTC, CreoHwan commented on Samsam/ViewController/PostingImageButtonCell.swift
> +        $0.image = image
> p4; 이 부분은 `$0.image = UIImage(systemName: "plus.circle", withConfiguration: imageConfig)?.withTintColor(.white, renderingMode: .alwaysOriginal)`처럼 바꿀 수 있을 것 같습니다.

22813e8 감사합니다!

2022-11-04 02:34 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> p3. Delegate가 없어도 정상작동할 것 같네요! DelegateFlowLayout이 대체해주고 있는 것 같습니다.

9432812 감사합니다! 저게 왜 들어가있는지.. 당황스럽네요. 꼼꼼히 하겠습니다!

2022-11-04 02:35 UTC, CreoHwan commented on Samsam/ViewController/PostingImageButtonCell.swift
> +        $0.image = image
ㅓㅏ

2022-11-04 02:47 UTC, CreoHwan commented on Samsam/ViewController/PostingImageViewController.swift
> +        generator.impactOccurred()
> > Q. generator는 어떤 용도의 코드일까요? 삭제해도 동일한 동작을 하여 질문합니다.
> 
> 제가 아는 바로 UIImpactFeedbackGenerator는 HapticFeedback을 위한 부분인 것으로 알고 있습니다. 다만, 저도 궁금한 것은 이 부분에 HapticFeedback을 준 이유가 있을까요?
> 
> 에디를 위한 UIImpactFeedbackGenerator 자체에 대한 레퍼런스도 아래에 첨부합니다.
> 
> * [Apple Developer Document - [UIKit] UIImpactFeedbackGenerator](https://developer.apple.com/documentation/uikit/uiimpactfeedbackgenerator)
> * [ZeddiOS - iOS ) Haptic Feedback](https://zeddios.tistory.com/726)

ba3d220 햅틱 미세한 진동을 주었는데... 왜 주었을까요? 삭제했습니다!

2022-11-04 02:50 UTC, CreoHwan commented on Samsam/ViewController/PostingWritingView.swift
> +//        }
> p1; 불필요한 주석 삭제 부탁드립니다.

2b60867 감사합니다! 다음 PR때 코어데이터 저장 구현하겠습니다!

2022-11-04 02:51 UTC, CreoHwan commented on Samsam/ViewController/PostingWritingView.swift
> +    var photoImages: [cellItem]?
> p1; 사용되지 않는 변수입니다. 해당 부분이 데이터를 저장하기 위해 다른 뷰에서 데이터를 가져오기 위한 부분이라고 생각했는데, 실제로 사용이 되고 있지 않네요.

현재는 Image뷰에서, Writing뷰로, 이미지만을 넘겨주고 있는데, 그 부부에서 쓰입니다. 추후 PR에서 받은 이미지를 코어 데이터에 저장하는 기능 구현하도록 하겠습니다!

2022-11-04 02:51 UTC, CreoHwan commented on Samsam/ViewController/PostingWritingView.swift
> +    var photoImages: [cellItem]?
> p2. 해당 변수는 사용되고 있지 않은 것 같습니다.

현재는 Image뷰에서, Writing뷰로, 이미지만을 넘겨주고 있는데, 그 부부에서 쓰입니다. 추후 PR에서 받은 이미지를 코어 데이터에 저장하는 기능 구현하도록 하겠습니다!

2022-11-04 02:52 UTC, CreoHwan commented on Samsam/ViewController/PostingWritingView.swift
> +//        }
> p2. 주석을 남겨둔 이유가 있을까요??

2b60867 삭제했습니다! 다음 번 작업에서 코어데이터 저장 기능 구현하도록 하겠습니다!

2022-11-04 02:52 UTC, CreoHwan commented
@taek0622 @JUNY0110 확인 부탁드립니다! 감사합니다 :)

2022-11-04 02:53 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
>          }
> > > 
> > 
> > 
> > 이 부분에 대해 제가 알고 있는 내용을 말씀드려보자면 Bundle.main.infoDictionary!["CFBundleName"]은 현재 앱의 BundleName을 가져오는 부분입니다. 아래에 보시면 message에서 앱 네임을 불러와서 "기와집이 카메라에 접근이 허용되어 있지 않습니다."를 출력하려고 하신 것 같아보여요. 다만, 현재 코드에서 문제가 될만한 부분을 보자면 BundleName을 불러오면 정말 앱의 BundleName을 불러오게 됩니다. 예를 들어 저희 프로젝트 이름이 Samsam이라면 Samsam을 불러오게 되겠죠. 만약 저희 프로젝트 이름을 giwazip으로 변경한다면 BundleName을 불러와도 됩니다만, 저희 앱이름이 한글로 "기와집"을 표시하고 싶다면 BundleName이 아니라 DisplayName을 불러와야하기 때문에 해당 부분은 `CFBundlName`이 아닌, `CFBundleDisplayName`을 불러오는 것이 더 바람직해 보입니다.
> > 해당 부분의 차이에 대한 간단한 레퍼런스를 아래에 하나 첨부합니다.
> > 
> > * [stack overflow - Get App Name in Swift](https://stackoverflow.com/questions/28254377/get-app-name-in-swift)
> 
> [24d0025](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/24d0025f272c3900c94ad6f546770a94c71b27a6) 현재는 displayname이 설정되어 있지 않아서, 일단 if문으로 2개를 돌렸습니다! 첫번째는 displayname이고 두번째는 그냥 name으로 뒀습니다!

확인했습니다. 리뷰 리졸브할게요~

2022-11-04 02:53 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +        generator.impactOccurred()
> > > Q. generator는 어떤 용도의 코드일까요? 삭제해도 동일한 동작을 하여 질문합니다.
> > 
> > 
> > 제가 아는 바로 UIImpactFeedbackGenerator는 HapticFeedback을 위한 부분인 것으로 알고 있습니다. 다만, 저도 궁금한 것은 이 부분에 HapticFeedback을 준 이유가 있을까요?
> > 에디를 위한 UIImpactFeedbackGenerator 자체에 대한 레퍼런스도 아래에 첨부합니다.
> > 
> > * [Apple Developer Document - [UIKit] UIImpactFeedbackGenerator](https://developer.apple.com/documentation/uikit/uiimpactfeedbackgenerator)
> > * [ZeddiOS - iOS ) Haptic Feedback](https://zeddios.tistory.com/726)
> 
> [ba3d220](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/ba3d220b6d1502cba708e1e98f58ff9ec35ba3cb) 햅틱 미세한 진동을 주었는데... 왜 주었을까요? 삭제했습니다!

확인했습니다.

2022-11-04 02:54 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +        changeNUM = nil
> > > Q. 업로드를 할 때 changeNum = nil이 있어야하는 이유가 무엇일까요?
> > 
> > 
> > 저도 이부분 궁금합니다. 0과 같은 값이 아닌 nil이 되어야하는 이유가 있을까요?
> 
> [5acd0af](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/5acd0af913c589a2524e6f303d60efc2a768baba) 처음에 선언할 때 nil 대신 -1 로 바꿨습니다!

확인했습니다.

2022-11-04 02:55 UTC, taek0622 commented on Samsam/ViewController/PostingImageButtonCell.swift
> +        $0.image = image
> > p4; 이 부분은 `$0.image = UIImage(systemName: "plus.circle", withConfiguration: imageConfig)?.withTintColor(.white, renderingMode: .alwaysOriginal)`처럼 바꿀 수 있을 것 같습니다.
> 
> [22813e8](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/22813e8b924f2fb858f40e36b8378c20fb381637) 감사합니다!

해당 커밋 번호가 이 파트가 맞을까요?

2022-11-04 02:55 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +struct cellItem {
> > p2; struct의 이름은 대문자로 시작하는 규칙이 있습니다. 대문자로 시작하도록 수정 부탁드려요~
> 
> [3db06cd](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/3db06cddc6c51070b6f7e7d11e2b4372649bbbb6) 넵 감사합니다!

확인했습니다. 리뷰 리졸브할게요~

2022-11-04 02:55 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +
> > p1; 불필요한 공백이 들어가있네요. 삭제 부탁드립니다~
> 
> [1211588](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/12115888a351af45190d6f81e26733f2fc59772d) 감사합니다!

확인했습니다. 리뷰 리졸브할게요~

2022-11-04 02:56 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +    private var changeNUM: Int?
> > p1; changeNum이 nil이 될 경우가 없을 것 같은데, 그렇다면 이 부분은 처음에 0으로 초기화하는 것이 더 좋을 것 같습니다.
> 
> [5acd0af](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/5acd0af913c589a2524e6f303d60efc2a768baba) 처음에 선언할 때 -1로 바꿨습니다! 감사합니다!

확인했습니다. 리뷰 리졸브할게요~

2022-11-04 02:56 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +        if changeNUM == nil {
> > p1; changeNUM이 0인 조건으로 변경되어도 될 것 같습니다. nil 값 사용은 최대한 지양하는 것이 좋을 것 같아요. 또한 해당 부분부터 아래에 나오는 로직은 한번에 확인하기 어려워 2번에 걸쳐서 리뷰하겠습니다.
> 
> [5acd0af](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/5acd0af913c589a2524e6f303d60efc2a768baba) 처음에 선언할 때 -1로 바꿨습니다! 감사합니다!

확인했습니다. 리뷰 리졸브할게요~

2022-11-04 02:56 UTC, taek0622 commented on Samsam/ViewController/PostingWritingView.swift
> +//        }
> > p1; 불필요한 주석 삭제 부탁드립니다.
> 
> [2b60867](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/2b608676145ab89181dafc48c0d93686ecddb83e) 감사합니다! 다음 PR때 코어데이터 저장 구현하겠습니다!

확인했습니다.

2022-11-04 02:57 UTC, taek0622 commented on Samsam/ViewController/PostingWritingView.swift
> +    var photoImages: [cellItem]?
> > p1; 사용되지 않는 변수입니다. 해당 부분이 데이터를 저장하기 위해 다른 뷰에서 데이터를 가져오기 위한 부분이라고 생각했는데, 실제로 사용이 되고 있지 않네요.
> 
> 현재는 Image뷰에서, Writing뷰로, 이미지만을 넘겨주고 있는데, 그 부부에서 쓰입니다. 추후 PR에서 받은 이미지를 코어 데이터에 저장하는 기능 구현하도록 하겠습니다!

확인했습니다.

2022-11-04 02:57 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +            }
> > p1; 이 부분은 결과적으로 다른 부분이 배열에 이미지를 추가하는지, 혹은 배열에 있는 이미지를 변경하는지만 다릅니다. 그렇다면 해당 부분만 If문으로 구분하면 될 것 같네요. 충분히 이것보다 더 간단하게 가능할 것 같습니다. 다만 제가 직접 이 코드를 줄이는 것이 디너한테 과연 도움이 되는 것일까 의문이 들어 아래에 코드를 첨부하나, 접어두겠습니다. 필요하시다면 토글을 열어서 보셔도 좋지만, 보지 않고 디너가 직접 생각해보시는 방법도 좋을 것 같네요. 다만, 현재 제가 이 코드에 대한 완전한 이해를 하고 줄인 것은 아니기 때문에 이것보다 더 좋은 방법이 있을 수도 있으니, 참고 정도로만 사용하시면 좋을 것 같습니다.
> > 코드 보기/숨기기
> > ```swift
> > for result in results {
> >     let itemProvider = result.itemProvider
> >     if itemProvider.canLoadObject(ofClass: UIImage.self) {
> >         itemProvider.loadObject(ofClass: UIImage.self) { [weak self] (image, error) in
> >             DispatchQueue.main.async {
> >                 guard let image = image as? UIImage else { return }
> >                 if self!.changeNUM == nil {
> >                     self?.photoImages.insert(cellItem(image: image), at: 0)
> >                 } else {
> >                     self?.photoImages[self!.changeNUM!].image = image as! UIImage
> >                 }
> >                 self?.imageCellView.reloadData()
> >             }
> >             if let error = error {
> >                 DispatchQueue.main.async {
> >                     self?.makeAlert(title: "", message: "사진을 불러올 수 없습니다")
> >                 }
> >             }
> >         }
> >     }
> > }
> > ```
> 
> 저도 고민했던 부분이라... 공감이 됩니다! if문을 돌리는 횟수가 크게 상관이 없을 것 같아서, 코드를 깔끔히 만들었습니다! 감사합니다!

확인했습니다.

2022-11-04 02:57 UTC, taek0622 commented on Samsam/ViewController/PostingImageViewController.swift
> +            makeAlert(title: "",message: "사진을 최소 하나 이상 선택해야 합니다")
> Member

확인했습니다. 리뷰 리졸브할게요~

2022-11-04 03:00 UTC, taek0622 commented on Samsam/ViewController/PostingImageButtonCell.swift
> +        $0.image = image
> > > p4; 이 부분은 `$0.image = UIImage(systemName: "plus.circle", withConfiguration: imageConfig)?.withTintColor(.white, renderingMode: .alwaysOriginal)`처럼 바꿀 수 있을 것 같습니다.
> > 
> > 
> > [22813e8](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/22813e8b924f2fb858f40e36b8378c20fb381637) 감사합니다!
> 
> 해당 커밋 번호가 이 파트가 맞을까요?

9432812 에서 수정확인했습니다. 리뷰 리졸브합니다.

2022-11-04 03:01 UTC, taek0622 approved these changes
고생하셨습니다.
수정 확인했습니다. 나머지 데이터와 관련된 부분은 새 PR에서 수정 부탁드려요~
감사합니다.

2022-11-05 03:09 UTC, JUNY0110 commented on Samsam/ViewController/PostingImageViewController.swift
> +        generator.impactOccurred()
> > > Q. generator는 어떤 용도의 코드일까요? 삭제해도 동일한 동작을 하여 질문합니다.
> > 
> > 
> > 제가 아는 바로 UIImpactFeedbackGenerator는 HapticFeedback을 위한 부분인 것으로 알고 있습니다. 다만, 저도 궁금한 것은 이 부분에 HapticFeedback을 준 이유가 있을까요?
> > 에디를 위한 UIImpactFeedbackGenerator 자체에 대한 레퍼런스도 아래에 첨부합니다.
> > 
> > * [Apple Developer Document - [UIKit] UIImpactFeedbackGenerator](https://developer.apple.com/documentation/uikit/uiimpactfeedbackgenerator)
> > * [ZeddiOS - iOS ) Haptic Feedback](https://zeddios.tistory.com/726)
> 
> [40bb083](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/40bb083c1d8c03573ea776cbc676599dda3acc82) 햅틱 미세한 진동을 주었는데... 왜 주었을까요? 삭제했습니다!

확인했습니다~

2022-11-05 03:10 UTC, JUNY0110 approved these changes
고생하셨습니다~

2022-11-05 04:32 UTC, merged