[Design] 시공상황뷰(WorkingHistioryView) 레이아웃 2차 추가
DeveloperAcademy-POSTECH/MacC-Team-Samsamhada pull request #94
Opened 2022-11-03 06:55 UTC by JUNY0110

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- Segmented Control의 Swipe기능을 위함
- UI 디자인을 헤치는 일부 디자인 일부 수정하기 위함
- UX를 높이기 위함.

## Key Changes 🔥 (주요 구현/변경 사항)
- Segmented Control
- Segmented Control Swipe를 위한 PageControl
- 누락된 Asset 추가 및 Dark모드 Color Asset 삭제
- Segmented Control Custom
- WorkingHistoryViewController의 Cell 이미지 사이즈 수정
- WorkingHistoryViewController의 Cell 이미지설명글 셀 사이즈 수정
- WorkingHistoryViewController의 Cell 이미지설명글 폰트 수정

## ToDo 📆 (남은 작업)
- [ ] Metro차트가 남았습니다... 
![image](https://user-images.githubusercontent.com/98405970/199661700-e3f6c94a-0cc7-439e-b8ba-b345b022a854.png)

## ScreenShot 📷 (참고 사진)
![Simulator Screen Recording - iPhone 13 Pro - 2022-11-03 at 15 51 17](https://user-images.githubusercontent.com/98405970/199662068-d1556465-4c16-47a9-bda0-891bd736dfb8.gif)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 이게 되네..

## Reference 🔗
- segmented Control참고자료1: https://ios-development.tistory.com/962
- segmented Control참고자료2: https://ios-development.tistory.com/963
- Priority 참고자료: https://velog.io/@sun02/사이즈-조절-우선순위-설정

## Close Issues 🔒 (닫을 Issue)
Close #No.

2022-11-03 15:02 UTC, taek0622 requested changes
고생하셨습니다.
수정이 필요해 보이는 부분 몇 군데 리뷰 남겼습니다.
확인 부탁드려요.
항상 감사합니다 에디~

2022-11-03 15:02 UTC, ikanic commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +    }()
p3;
배열을 이런 식으로 만든 이유가 있을까요?
현재 코드를 보고 실행해보았을 때,`private lazy var dataViewControllers: [UIViewController] = [workingHistoryView, inquiryHistoryView]`와 실행 결과에 차이가 없는 것 같습니다.
불필요한 클로저가 붙은 것 같아요.

2022-11-03 15:02 UTC, ikanic commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +    }()
p5;
해당 부분은 에디가 작성하신 것처럼도 작성할 수 있지만,
```swift
private lazy var pageViewController: UIPageViewController = {
    $0.setViewControllers([dataViewControllers[0]], direction: .forward, animated: true)
    return $0
}(UIPageViewController(transitionStyle: .scroll, navigationOrientation: .horizontal, options: nil))
```

이렇게도 작성할 수 있을 것 같습니다.
다른 뷰들과 동일하게 선언하려면 이런 방식도 사용할 수 있어요.
다만, 이 부분은 컨벤션으로 별도로 지정되어 있지도 않고, 취향의 차이인 것 같기도하여 수정하지 않으셔도 좋습니다.

2022-11-03 15:02 UTC, ikanic commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +            let direction: UIPageViewController.NavigationDirection = oldValue <= currentViewNumber ? .forward : .reverse
p4;
이 부분은 문법으로나 동작상으로는 아무 문제가 없습니다만, 코드의 가독성이 좋지 못한 것 같습니다.
현재와 같이 작성되어 있는 경우 다른 사람이 보았을 때, 혹은 조금 나중에 보았을 때 문법적으로 헷갈릴 가능성이 있어 보입니다.
해당 부분은 `let direction: UIPageViewController.NavigationDirection = (oldValue <= currentViewNumber ? .forward : .reverse)`과 같이 괄호로 범위를 더 명확히 하는 것이 어떨까요?

2022-11-03 15:02 UTC, ikanic commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +        self.segmentedControl.addTarget(self, action: #selector(changeValue(control: )), for: .valueChanged)
질문;
이 부분에 control이 비어있는 이유는 무엇일까요? 혹시 없어도 되는 부분이라면 제외시켜도 될 것 같습니다.

2022-11-03 15:02 UTC, ikanic commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +    }
질문;
이 부분은 전혀 모르겠습니다. 무슨 의미인지 파악이 안되요.
무슨 코드인지 설명 부탁드립니다.

2022-11-03 15:02 UTC, ikanic commented on Samsam/ViewController/HistoryView/WorkingHistoryView/UIComponent/WorkingHistoryViewContentHeader.swift
>          return $0
p4;
padding과 setHeight가 둘 다 살아있습니다. 둘 중에 하나는 죽여야 할 것 같습니다.

2022-11-04 07:26 UTC, CreoHwan commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +
Q: pageControlBackgroundView 이 친구를 따로 만드신 이유가 궁금합니다!

2022-11-04 07:59 UTC, CreoHwan commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +        segmentedControl.setBackgroundImage(image, for: .highlighted, barMetrics: .default)
질문;
.highlighted 친구는 어디에서 사용될까요??!

2022-11-04 10:38 UTC, JUNY0110 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +    }
> 질문;
> 이 부분은 전혀 모르겠습니다. 무슨 의미인지 파악이 안되요.
> 무슨 코드인지 설명 부탁드립니다.

별도 이야기 진행하여 답변드렸습니다.

2022-11-04 10:41 UTC, JUNY0110 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +            let direction: UIPageViewController.NavigationDirection = oldValue <= currentViewNumber ? .forward : .reverse
> p4;
> 이 부분은 문법으로나 동작상으로는 아무 문제가 없습니다만, 코드의 가독성이 좋지 못한 것 같습니다.
> 현재와 같이 작성되어 있는 경우 다른 사람이 보았을 때, 혹은 조금 나중에 보았을 때 문법적으로 헷갈릴 가능성이 있어 보입니다.
> 해당 부분은 `let direction: UIPageViewController.NavigationDirection = (oldValue <= currentViewNumber ? .forward : .reverse)`과 같이 괄호로 범위를 더 명확히 하는 것이 어떨까요?

ebee698
반영했습니다.

2022-11-04 10:41 UTC, JUNY0110 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +    }()
> p5; 해당 부분은 에디가 작성하신 것처럼도 작성할 수 있지만,
> 
> ```swift
> private lazy var pageViewController: UIPageViewController = {
>     $0.setViewControllers([dataViewControllers[0]], direction: .forward, animated: true)
>     return $0
> }(UIPageViewController(transitionStyle: .scroll, navigationOrientation: .horizontal, options: nil))
> ```
> 
> 이렇게도 작성할 수 있을 것 같습니다. 다른 뷰들과 동일하게 선언하려면 이런 방식도 사용할 수 있어요. 다만, 이 부분은 컨벤션으로 별도로 지정되어 있지도 않고, 취향의 차이인 것 같기도하여 수정하지 않으셔도 좋습니다.

2fed13d
어떻게 해야하는지 고민이었는데, 감사합니다. 반영했습니다.

2022-11-04 10:42 UTC, JUNY0110 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +    }()
> p3;
> 배열을 이런 식으로 만든 이유가 있을까요?
> 현재 코드를 보고 실행해보았을 때,`private lazy var dataViewControllers: [UIViewController] = [workingHistoryView, inquiryHistoryView]`와 실행 결과에 차이가 없는 것 같습니다.
> 불필요한 클로저가 붙은 것 같아요.

2fed13d
잔여 코드가 남았던 것 같네요. 수정했습니다.

2022-11-04 10:42 UTC, JUNY0110 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +        self.segmentedControl.addTarget(self, action: #selector(changeValue(control: )), for: .valueChanged)
050aff5
반영했습니다.

2022-11-04 10:44 UTC, JUNY0110 commented on Samsam/ViewController/HistoryView/WorkingHistoryView/UIComponent/WorkingHistoryViewContentHeader.swift
>          return $0
> p4;
> padding과 setHeight가 둘 다 살아있습니다. 둘 중에 하나는 죽여야 할 것 같습니다.

fb543ba 기어이.. 남기셨군요 반영했습니다.

2022-11-04 10:52 UTC, JUNY0110 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +
> Q: pageControlBackgroundView 이 친구를 따로 만드신 이유가 궁금합니다!

먼저 해당 뷰는 없어도 정상 작동합니다. 해당 뷰를 만든 이유는 페이지컨트롤을 안정적으로 구현하기 위함입니다.
페이지 컨트롤이 안정적으로 구현되기 위해서는 배경뷰가 존재해야하고, 배경뷰가 없으면 동작하지 않기 때문입니다.
그래서 pageControlBackgroundView에 addChild로 자식관계로 PageViewController가 존재하고, PageViewController의 뷰에서 화면 전환이 이루어집니다.

2022-11-04 11:03 UTC, JUNY0110 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +        segmentedControl.setBackgroundImage(image, for: .highlighted, barMetrics: .default)
> 질문;
> .highlighted 친구는 어디에서 사용될까요??!

707e075
해당 코드는 없어도 동작상 차이가 없어 삭제하였습니다.

2022-11-04 13:09 UTC, taek0622 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +    }()
> > p5; 해당 부분은 에디가 작성하신 것처럼도 작성할 수 있지만,
> > ```swift
> > private lazy var pageViewController: UIPageViewController = {
> >     $0.setViewControllers([dataViewControllers[0]], direction: .forward, animated: true)
> >     return $0
> > }(UIPageViewController(transitionStyle: .scroll, navigationOrientation: .horizontal, options: nil))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 이렇게도 작성할 수 있을 것 같습니다. 다른 뷰들과 동일하게 선언하려면 이런 방식도 사용할 수 있어요. 다만, 이 부분은 컨벤션으로 별도로 지정되어 있지도 않고, 취향의 차이인 것 같기도하여 수정하지 않으셔도 좋습니다.
> 
> [2fed13d](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/2fed13d91ca4cf19e3ff952b4a11cb1b397d999f) 어떻게 해야하는지 고민이었는데, 감사합니다. 반영했습니다.

확인했습니다. 이렇게 해볼 시도를 해보셨다는 것에 에디가 많이 성장한 것 같아서 뿌듯하네요.
화이팅~!

2022-11-04 13:09 UTC, taek0622 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +            let direction: UIPageViewController.NavigationDirection = oldValue <= currentViewNumber ? .forward : .reverse
> > p4;
> > 이 부분은 문법으로나 동작상으로는 아무 문제가 없습니다만, 코드의 가독성이 좋지 못한 것 같습니다.
> > 현재와 같이 작성되어 있는 경우 다른 사람이 보았을 때, 혹은 조금 나중에 보았을 때 문법적으로 헷갈릴 가능성이 있어 보입니다.
> > 해당 부분은 `let direction: UIPageViewController.NavigationDirection = (oldValue <= currentViewNumber ? .forward : .reverse)`과 같이 괄호로 범위를 더 명확히 하는 것이 어떨까요?
> 
> [ebee698](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/ebee698ec5543771fd9ac27c411aa00c2d42d511) 반영했습니다.

확인했습니다. 코드의 의미가 한결 명확해진 것 같네요.

2022-11-04 13:10 UTC, taek0622 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +        self.segmentedControl.addTarget(self, action: #selector(changeValue(control: )), for: .valueChanged)
> [050aff5](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/050aff56858b5cfcf7481de2a2e751134e1b634a) 반영했습니다.

확인했습니다. 리뷰 리졸브합니다~

2022-11-04 13:10 UTC, taek0622 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +    }
> > 질문;
> > 이 부분은 전혀 모르겠습니다. 무슨 의미인지 파악이 안되요.
> > 무슨 코드인지 설명 부탁드립니다.
> 
> 별도 이야기 진행하여 답변드렸습니다.

별도 설명 들었습니다. 제가 생각한 의미가 정반대의 의미였더라구요 ㅎㅎ
좋은 설명 감사합니다 에디~

2022-11-04 13:11 UTC, taek0622 commented on Samsam/ViewController/HistoryView/WorkingHistoryView/UIComponent/WorkingHistoryViewContentHeader.swift
>          return $0
> > p4;
> > padding과 setHeight가 둘 다 살아있습니다. 둘 중에 하나는 죽여야 할 것 같습니다.
> 
> [fb543ba](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/fb543ba86afc845d187de170bc4e0751a72fcf0d) 기어이.. 남기셨군요 반영했습니다.

예, 기어이 남겼답니당~ ㅎㅎ
그치만.. 남긴다고 이미 말했었는 걸.. ㅎㅎ
그리고 사실 이미 남기고 말한 걸 ㅎㅎ

2022-11-04 13:33 UTC, taek0622 approved these changes
고생하셨습니다.
그동안도 너무 고생하셨지만, 이번 뷰는 특히 기능도 가장 많고, 또 처음 시도해보는 것들도 많아서 힘드셨을텐데 정말 너무 잘해주셔서 감사해요.
덕분에 에디의 태스크는 항상 걱정없이 믿고 맡길 수 있는 것 같아요.

한군데 약간 수정되면 좋을 것 같은 부분과 코멘트, 질문, 그리고 에디의 멋진 코드 감상을 약간 남겼답니다.
우선 어프루브를 드리지만, 제가 제안한 수정 사항에 대해 한번 생각해보고 에디는 어떤 생각인지 코멘트 남겨주시면 좋을 것 같아요.

진짜 너무 고생하셨습니다. 항상 감사해요 에디

2022-11-04 13:33 UTC, ikanic commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +                          options: nil))
p4;
사소하긴 하지만 하나 말씀드려 보자면 해당 부분이 `nil`값이라면 options의 default 값 자체가 nil이기 때문에 생략이 가능할 것 같습니다.
불필요한 옵션이므로 삭제하는 것이 더 좋을 것 같아요.

2022-11-04 13:33 UTC, taek0622 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +        super.viewWillAppear(animated)
comment;
이 부분에 대해서 항상 궁금했습니다.
`viewWillAppear`를 override하기 때문에 `super`를 통해 슈퍼 클래스를 호출한다는 의미 자체는 알고 있었지만, 그래서 `viewWillAppear`는 `super`를 통해 무엇을 호출하는 것인가, 없어도 정상 동작을 하는데 왜 필요한가 하고 항상 궁금했고, 고민했었습니다.
이 부분에 대해 검색해보아도 "정확히 무엇이 호출되는지는 모르나 슈퍼클래스를 호출하지 않으면 예기치 못한 동작을 발생시킬 수 있기 때문에 무조건 해야한다." 라는 설명만 있어서 여전히 정확하게 무엇을 호출하는지는 잘 모르겠습니다.
그래서 이 부분에 대해서 에디와 이야기해보고 싶어요.

여튼, 저는 그래서 이 부분을 빼먹을 때가 많았는데, 에디는 항상 포함시키더라구요.
아주 좋은 부분인 것 같습니다. 에디 덕에 저도 한번씩 빼먹었다는 것을 깨닫고 다시 넣을 때가 많아요.
에디의 코드는 항상 보면서 다시 한번 생각하게 해주어서 좋은 것 같습니다.
항상 감사합니다. 에디~

2022-11-04 13:33 UTC, ikanic commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +        let image = UIImage()
질문;
이 부분은 Image가 비어있는 것 같은데, 왜 비어있는 것일까요?
아래에서 사용은 되고 있는 것 같은데 어떤 식으로 사용되고 있는 것인지 궁금합니다.

2022-11-04 13:33 UTC, ikanic commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +        else { return }
comment;
코드가 수정이 되고나니 훨씬 의미가 명확하게 보이고 좋네요.
가독성도 훨씬 좋아진 것 같습니다.
덕분에 약간 애매하게 이해하고 있던 부분이었는데, 이제 명확하게 한 눈에 보이는 것 같아요.
이렇게 수정할 수 있다고는 생각을 못하고 있었는데, 이렇게도 할 수 있군요.
또 하나 배우고 갑니다. 너무 멋져요 에디~

2022-11-04 15:56 UTC, JUNY0110 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +        super.viewWillAppear(animated)
> comment; 이 부분에 대해서 항상 궁금했습니다. `viewWillAppear`를 override하기 때문에 `super`를 통해 슈퍼 클래스를 호출한다는 의미 자체는 알고 있었지만, 그래서 `viewWillAppear`는 `super`를 통해 무엇을 호출하는 것인가, 없어도 정상 동작을 하는데 왜 필요한가 하고 항상 궁금했고, 고민했었습니다. 이 부분에 대해 검색해보아도 "정확히 무엇이 호출되는지는 모르나 슈퍼클래스를 호출하지 않으면 예기치 못한 동작을 발생시킬 수 있기 때문에 무조건 해야한다." 라는 설명만 있어서 여전히 정확하게 무엇을 호출하는지는 잘 모르겠습니다. 그래서 이 부분에 대해서 에디와 이야기해보고 싶어요.
> 
> 여튼, 저는 그래서 이 부분을 빼먹을 때가 많았는데, 에디는 항상 포함시키더라구요. 아주 좋은 부분인 것 같습니다. 에디 덕에 저도 한번씩 빼먹었다는 것을 깨닫고 다시 넣을 때가 많아요. 에디의 코드는 항상 보면서 다시 한번 생각하게 해주어서 좋은 것 같습니다. 항상 감사합니다. 에디~

호출되는것은 당연히 viewWillAppear에 대한 내부구현코드입니다. 그리고 `super`를 통해 어떤 함수를 상속받는지 명확히 해주기 위함입니다. 해주는 게 좋아요

2022-11-04 15:56 UTC, JUNY0110 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +        let image = UIImage()
> 질문;
> 이 부분은 Image가 비어있는 것 같은데, 왜 비어있는 것일까요?
> 아래에서 사용은 되고 있는 것 같은데 어떤 식으로 사용되고 있는 것인지 궁금합니다.

세그먼트컨트롤의 배경이 아무것도 없기 때문에 배경을 날리기 위해 빈 이미지를 삽입하는 방식입니다.

2022-11-04 15:59 UTC, JUNY0110 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +                          options: nil))
> p4;
> 사소하긴 하지만 하나 말씀드려 보자면 해당 부분이 `nil`값이라면 options의 default 값 자체가 nil이기 때문에 생략이 가능할 것 같습니다.
> 불필요한 옵션이므로 삭제하는 것이 더 좋을 것 같아요.

ba539dd

2022-11-04 15:59 UTC, taek0622 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +    }()
> > p3;
> > 배열을 이런 식으로 만든 이유가 있을까요?
> > 현재 코드를 보고 실행해보았을 때,`private lazy var dataViewControllers: [UIViewController] = [workingHistoryView, inquiryHistoryView]`와 실행 결과에 차이가 없는 것 같습니다.
> > 불필요한 클로저가 붙은 것 같아요.
> 
> [2fed13d](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/2fed13d91ca4cf19e3ff952b4a11cb1b397d999f) 잔여 코드가 남았던 것 같네요. 수정했습니다.

확인했습니다. 리뷰 리졸브합니다.

2022-11-04 16:00 UTC, taek0622 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +                          options: nil))
> > p4;
> > 사소하긴 하지만 하나 말씀드려 보자면 해당 부분이 `nil`값이라면 options의 default 값 자체가 nil이기 때문에 생략이 가능할 것 같습니다.
> > 불필요한 옵션이므로 삭제하는 것이 더 좋을 것 같아요.
> 
> [ba539dd](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Samsamhada/commit/ba539dd9f79d8a7b5d5f1e1fb2f19833f9e11096) 반영했습니다.

확인했습니다. 리뷰 리졸브합니다.

2022-11-04 16:05 UTC, taek0622 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +        super.viewWillAppear(animated)
> > comment; 이 부분에 대해서 항상 궁금했습니다. `viewWillAppear`를 override하기 때문에 `super`를 통해 슈퍼 클래스를 호출한다는 의미 자체는 알고 있었지만, 그래서 `viewWillAppear`는 `super`를 통해 무엇을 호출하는 것인가, 없어도 정상 동작을 하는데 왜 필요한가 하고 항상 궁금했고, 고민했었습니다. 이 부분에 대해 검색해보아도 "정확히 무엇이 호출되는지는 모르나 슈퍼클래스를 호출하지 않으면 예기치 못한 동작을 발생시킬 수 있기 때문에 무조건 해야한다." 라는 설명만 있어서 여전히 정확하게 무엇을 호출하는지는 잘 모르겠습니다. 그래서 이 부분에 대해서 에디와 이야기해보고 싶어요.
> > 여튼, 저는 그래서 이 부분을 빼먹을 때가 많았는데, 에디는 항상 포함시키더라구요. 아주 좋은 부분인 것 같습니다. 에디 덕에 저도 한번씩 빼먹었다는 것을 깨닫고 다시 넣을 때가 많아요. 에디의 코드는 항상 보면서 다시 한번 생각하게 해주어서 좋은 것 같습니다. 항상 감사합니다. 에디~
> 
> 호출되는것은 당연히 viewWillAppear에 대한 내부구현코드입니다. 그리고 `super`를 통해 어떤 함수를 상속받는지 명확히 해주기 위함입니다. 해주는 게 좋아요

정확히 하자면 내부구현이라기보단 기본 viewWillAppear에 대한 코드가 되겠네요.
이 부분에 대해서는 알고 있습니다. 다만, 궁금했던 부분은 그래서 `super`를 통해서 슈퍼클래스에서 받아오는 부분이 어느 부분인가 였습니다만, 해당 부분에 대한 답은 기술적으로는 상관 없으나 그냥 그렇게 해야한다. 라는 답이 있었기 때문에 의문이 들었는데요.
이 부분에 대한 완전하진 않지만 궁금증을 해소할 정도의 답을 얻었기 때문에 해당 레퍼런스를 아래에 첨부합니다.

### 레퍼런스
- [stack overflow - What does [super viewWillAppear] do, and when is it required?](https://stackoverflow.com/questions/3348204/what-does-super-viewwillappear-do-and-when-is-it-required)

2022-11-04 16:07 UTC, ikanic commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +        let image = UIImage()
> > 질문;
> > 이 부분은 Image가 비어있는 것 같은데, 왜 비어있는 것일까요?
> > 아래에서 사용은 되고 있는 것 같은데 어떤 식으로 사용되고 있는 것인지 궁금합니다.
> 
> 세그먼트컨트롤의 배경이 아무것도 없기 때문에 배경을 날리기 위해 빈 이미지를 삽입하는 방식입니다.

그냥 UIImage()를 하면 문제가 발생하지는 않나요? 저런 식으로 사용할 수 있는지는 처음 알았네요. 좋은 방법 같습니다.
다만, 이 경우 UIImage()가 nil이 되는건 아닌지, 또 이로 인해 문제가 발생하지는 않는지 궁금합니다.

2022-11-04 17:49 UTC, JUNY0110 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +        let image = UIImage()
> > > 질문;
> > > 이 부분은 Image가 비어있는 것 같은데, 왜 비어있는 것일까요?
> > > 아래에서 사용은 되고 있는 것 같은데 어떤 식으로 사용되고 있는 것인지 궁금합니다.
> > 
> > 
> > 세그먼트컨트롤의 배경이 아무것도 없기 때문에 배경을 날리기 위해 빈 이미지를 삽입하는 방식입니다.
> 
> 그냥 UIImage()를 하면 문제가 발생하지는 않나요? 저런 식으로 사용할 수 있는지는 처음 알았네요. 좋은 방법 같습니다. 다만, 이 경우 UIImage()가 nil이 되는건 아닌지, 또 이로 인해 문제가 발생하지는 않는지 궁금합니다.

setBackgroundImage의 Documents를 보면,
`func setBackgroundImage(_ backgroundImage: UIImage?, for state: UIControl.State, barMetrics: UIBarMetrics)`라고 명시되어있습니다. 즉 setBackgroundImage를 사용했을 때 UIImage 사용 시 nil값이 가능하도록 설계되어있기 때문에, image = UIImage()로 사용이 가능하며, 문제가 발생하지 않을 것으로 보입니다.

2022-11-04 17:52 UTC, JUNY0110 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +        super.viewWillAppear(animated)
> > > comment; 이 부분에 대해서 항상 궁금했습니다. `viewWillAppear`를 override하기 때문에 `super`를 통해 슈퍼 클래스를 호출한다는 의미 자체는 알고 있었지만, 그래서 `viewWillAppear`는 `super`를 통해 무엇을 호출하는 것인가, 없어도 정상 동작을 하는데 왜 필요한가 하고 항상 궁금했고, 고민했었습니다. 이 부분에 대해 검색해보아도 "정확히 무엇이 호출되는지는 모르나 슈퍼클래스를 호출하지 않으면 예기치 못한 동작을 발생시킬 수 있기 때문에 무조건 해야한다." 라는 설명만 있어서 여전히 정확하게 무엇을 호출하는지는 잘 모르겠습니다. 그래서 이 부분에 대해서 에디와 이야기해보고 싶어요.
> > > 여튼, 저는 그래서 이 부분을 빼먹을 때가 많았는데, 에디는 항상 포함시키더라구요. 아주 좋은 부분인 것 같습니다. 에디 덕에 저도 한번씩 빼먹었다는 것을 깨닫고 다시 넣을 때가 많아요. 에디의 코드는 항상 보면서 다시 한번 생각하게 해주어서 좋은 것 같습니다. 항상 감사합니다. 에디~
> > 
> > 
> > 호출되는것은 당연히 viewWillAppear에 대한 내부구현코드입니다. 그리고 `super`를 통해 어떤 함수를 상속받는지 명확히 해주기 위함입니다. 해주는 게 좋아요
> 
> 정확히 하자면 내부구현이라기보단 기본 viewWillAppear에 대한 코드가 되겠네요. 이 부분에 대해서는 알고 있습니다. 다만, 궁금했던 부분은 그래서 `super`를 통해서 슈퍼클래스에서 받아오는 부분이 어느 부분인가 였습니다만, 해당 부분에 대한 답은 기술적으로는 상관 없으나 그냥 그렇게 해야한다. 라는 답이 있었기 때문에 의문이 들었는데요. 이 부분에 대한 완전하진 않지만 궁금증을 해소할 정도의 답을 얻었기 때문에 해당 레퍼런스를 아래에 첨부합니다.
> 
> ### 레퍼런스
> * [stack overflow - What does [super viewWillAppear] do, and when is it required?](https://stackoverflow.com/questions/3348204/what-does-super-viewwillappear-do-and-when-is-it-required)

덕분에 alloc과 dealloc에 대해 알게 되었네요. 
관련 자료 링크입니다. https://sibalja.tistory.com/14

2022-11-04 18:31 UTC, taek0622 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +        let image = UIImage()
> https://developer.apple.com/documentation/watchkit/wkinterfacegroup/1619663-setbackgroundimage

확인했습니다. 첨부해주신 자료가 정말 많은 도움이 되는 것 같습니다. 자료 감사합니다~

2022-11-04 18:32 UTC, taek0622 commented on Samsam/ViewController/HistoryView/SegmentedControlViewcontroller.swift
> +        super.viewWillAppear(animated)
> > > > comment; 이 부분에 대해서 항상 궁금했습니다. `viewWillAppear`를 override하기 때문에 `super`를 통해 슈퍼 클래스를 호출한다는 의미 자체는 알고 있었지만, 그래서 `viewWillAppear`는 `super`를 통해 무엇을 호출하는 것인가, 없어도 정상 동작을 하는데 왜 필요한가 하고 항상 궁금했고, 고민했었습니다. 이 부분에 대해 검색해보아도 "정확히 무엇이 호출되는지는 모르나 슈퍼클래스를 호출하지 않으면 예기치 못한 동작을 발생시킬 수 있기 때문에 무조건 해야한다." 라는 설명만 있어서 여전히 정확하게 무엇을 호출하는지는 잘 모르겠습니다. 그래서 이 부분에 대해서 에디와 이야기해보고 싶어요.
> > > > 여튼, 저는 그래서 이 부분을 빼먹을 때가 많았는데, 에디는 항상 포함시키더라구요. 아주 좋은 부분인 것 같습니다. 에디 덕에 저도 한번씩 빼먹었다는 것을 깨닫고 다시 넣을 때가 많아요. 에디의 코드는 항상 보면서 다시 한번 생각하게 해주어서 좋은 것 같습니다. 항상 감사합니다. 에디~
> > > 
> > > 
> > > 호출되는것은 당연히 viewWillAppear에 대한 내부구현코드입니다. 그리고 `super`를 통해 어떤 함수를 상속받는지 명확히 해주기 위함입니다. 해주는 게 좋아요
> > 
> > 
> > 정확히 하자면 내부구현이라기보단 기본 viewWillAppear에 대한 코드가 되겠네요. 이 부분에 대해서는 알고 있습니다. 다만, 궁금했던 부분은 그래서 `super`를 통해서 슈퍼클래스에서 받아오는 부분이 어느 부분인가 였습니다만, 해당 부분에 대한 답은 기술적으로는 상관 없으나 그냥 그렇게 해야한다. 라는 답이 있었기 때문에 의문이 들었는데요. 이 부분에 대한 완전하진 않지만 궁금증을 해소할 정도의 답을 얻었기 때문에 해당 레퍼런스를 아래에 첨부합니다.
> > ### 레퍼런스
> > 
> > * [stack overflow - What does [super viewWillAppear] do, and when is it required?](https://stackoverflow.com/questions/3348204/what-does-super-viewwillappear-do-and-when-is-it-required)
> 
> 덕분에 alloc과 dealloc에 대해 알게 되었네요. 관련 자료 링크입니다. https://sibalja.tistory.com/14

UIKit에서의 생명주기에 대해 다시 한 번 공부해볼 수 있었습니다. 정말 고생하셨어요.

2022-11-05 03:11 UTC, merged